# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from db_server import db_service_pb2 as db__service__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in db_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class UpcServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ResolveUpc = channel.unary_unary(
                '/grocery.database.UpcService/ResolveUpc',
                request_serializer=db__service__pb2.UpcRequest.SerializeToString,
                response_deserializer=db__service__pb2.UpcResponse.FromString,
                _registered_method=True)


class UpcServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ResolveUpc(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UpcServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ResolveUpc': grpc.unary_unary_rpc_method_handler(
                    servicer.ResolveUpc,
                    request_deserializer=db__service__pb2.UpcRequest.FromString,
                    response_serializer=db__service__pb2.UpcResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'grocery.database.UpcService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('grocery.database.UpcService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class UpcService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ResolveUpc(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/grocery.database.UpcService/ResolveUpc',
            db__service__pb2.UpcRequest.SerializeToString,
            db__service__pb2.UpcResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class CatalogServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListProducts = channel.unary_unary(
                '/grocery.database.CatalogService/ListProducts',
                request_serializer=db__service__pb2.ListProductsRequest.SerializeToString,
                response_deserializer=db__service__pb2.ListProductsResponse.FromString,
                _registered_method=True)
        self.ListVariantsForProduct = channel.unary_unary(
                '/grocery.database.CatalogService/ListVariantsForProduct',
                request_serializer=db__service__pb2.ListVariantsForProductRequest.SerializeToString,
                response_deserializer=db__service__pb2.ListVariantsForProductResponse.FromString,
                _registered_method=True)


class CatalogServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ListProducts(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListVariantsForProduct(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CatalogServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListProducts': grpc.unary_unary_rpc_method_handler(
                    servicer.ListProducts,
                    request_deserializer=db__service__pb2.ListProductsRequest.FromString,
                    response_serializer=db__service__pb2.ListProductsResponse.SerializeToString,
            ),
            'ListVariantsForProduct': grpc.unary_unary_rpc_method_handler(
                    servicer.ListVariantsForProduct,
                    request_deserializer=db__service__pb2.ListVariantsForProductRequest.FromString,
                    response_serializer=db__service__pb2.ListVariantsForProductResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'grocery.database.CatalogService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('grocery.database.CatalogService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CatalogService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ListProducts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/grocery.database.CatalogService/ListProducts',
            db__service__pb2.ListProductsRequest.SerializeToString,
            db__service__pb2.ListProductsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListVariantsForProduct(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/grocery.database.CatalogService/ListVariantsForProduct',
            db__service__pb2.ListVariantsForProductRequest.SerializeToString,
            db__service__pb2.ListVariantsForProductResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class ObservationServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreatePriceObservation = channel.unary_unary(
                '/grocery.database.ObservationService/CreatePriceObservation',
                request_serializer=db__service__pb2.PriceObservationRequest.SerializeToString,
                response_deserializer=db__service__pb2.PriceObservationResponse.FromString,
                _registered_method=True)


class ObservationServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreatePriceObservation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ObservationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreatePriceObservation': grpc.unary_unary_rpc_method_handler(
                    servicer.CreatePriceObservation,
                    request_deserializer=db__service__pb2.PriceObservationRequest.FromString,
                    response_serializer=db__service__pb2.PriceObservationResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'grocery.database.ObservationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('grocery.database.ObservationService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ObservationService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreatePriceObservation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/grocery.database.ObservationService/CreatePriceObservation',
            db__service__pb2.PriceObservationRequest.SerializeToString,
            db__service__pb2.PriceObservationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
