// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: db_service.proto

package com.example.grocerystoreorganizer.grpc;

/**
 * Protobuf enum {@code grocery.database.ComparisonMode}
 */
public enum ComparisonMode
    implements com.google.protobuf.Internal.EnumLite {
  /**
   * <code>CHEAPEST_PRICE = 0;</code>
   */
  CHEAPEST_PRICE(0),
  /**
   * <code>BEST_UNIT_VALUE = 1;</code>
   */
  BEST_UNIT_VALUE(1),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>CHEAPEST_PRICE = 0;</code>
   */
  public static final int CHEAPEST_PRICE_VALUE = 0;
  /**
   * <code>BEST_UNIT_VALUE = 1;</code>
   */
  public static final int BEST_UNIT_VALUE_VALUE = 1;


  @java.lang.Override
  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The number of the enum to look for.
   * @return The enum associated with the given number.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static ComparisonMode valueOf(int value) {
    return forNumber(value);
  }

  public static ComparisonMode forNumber(int value) {
    switch (value) {
      case 0: return CHEAPEST_PRICE;
      case 1: return BEST_UNIT_VALUE;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<ComparisonMode>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      ComparisonMode> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<ComparisonMode>() {
          @java.lang.Override
          public ComparisonMode findValueByNumber(int number) {
            return ComparisonMode.forNumber(number);
          }
        };

  public static com.google.protobuf.Internal.EnumVerifier 
      internalGetVerifier() {
    return ComparisonModeVerifier.INSTANCE;
  }

  private static final class ComparisonModeVerifier implements 
       com.google.protobuf.Internal.EnumVerifier { 
          static final com.google.protobuf.Internal.EnumVerifier           INSTANCE = new ComparisonModeVerifier();
          @java.lang.Override
          public boolean isInRange(int number) {
            return ComparisonMode.forNumber(number) != null;
          }
        };

  private final int value;

  private ComparisonMode(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:grocery.database.ComparisonMode)
}

