// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: db_service.proto

package com.example.grocerystoreorganizer.grpc;

public final class DbServiceProto {
  private DbServiceProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
