// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: db_service.proto

package com.example.grocerystoreorganizer.grpc;

/**
 * Protobuf type {@code grocery.database.GroceryListOptimizationItem}
 */
public  final class GroceryListOptimizationItem extends
    com.google.protobuf.GeneratedMessageLite<
        GroceryListOptimizationItem, GroceryListOptimizationItem.Builder> implements
    // @@protoc_insertion_point(message_implements:grocery.database.GroceryListOptimizationItem)
    GroceryListOptimizationItemOrBuilder {
  private GroceryListOptimizationItem() {
    productName_ = "";
    preferredUpc_ = "";
  }
  private int bitField0_;
  public static final int ITEMID_FIELD_NUMBER = 1;
  private int itemId_;
  /**
   * <code>int32 itemId = 1;</code>
   * @return The itemId.
   */
  @java.lang.Override
  public int getItemId() {
    return itemId_;
  }
  /**
   * <code>int32 itemId = 1;</code>
   * @param value The itemId to set.
   */
  private void setItemId(int value) {
    
    itemId_ = value;
  }
  /**
   * <code>int32 itemId = 1;</code>
   */
  private void clearItemId() {
    
    itemId_ = 0;
  }

  public static final int PRODUCTNAME_FIELD_NUMBER = 2;
  private java.lang.String productName_;
  /**
   * <code>string productName = 2;</code>
   * @return The productName.
   */
  @java.lang.Override
  public java.lang.String getProductName() {
    return productName_;
  }
  /**
   * <code>string productName = 2;</code>
   * @return The bytes for productName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getProductNameBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(productName_);
  }
  /**
   * <code>string productName = 2;</code>
   * @param value The productName to set.
   */
  private void setProductName(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    productName_ = value;
  }
  /**
   * <code>string productName = 2;</code>
   */
  private void clearProductName() {
    
    productName_ = getDefaultInstance().getProductName();
  }
  /**
   * <code>string productName = 2;</code>
   * @param value The bytes for productName to set.
   */
  private void setProductNameBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    productName_ = value.toStringUtf8();
    
  }

  public static final int DESIREDCOUNT_FIELD_NUMBER = 3;
  private int desiredCount_;
  /**
   * <code>int32 desiredCount = 3;</code>
   * @return The desiredCount.
   */
  @java.lang.Override
  public int getDesiredCount() {
    return desiredCount_;
  }
  /**
   * <code>int32 desiredCount = 3;</code>
   * @param value The desiredCount to set.
   */
  private void setDesiredCount(int value) {
    
    desiredCount_ = value;
  }
  /**
   * <code>int32 desiredCount = 3;</code>
   */
  private void clearDesiredCount() {
    
    desiredCount_ = 0;
  }

  public static final int COMPARISONMODE_FIELD_NUMBER = 4;
  private int comparisonMode_;
  /**
   * <code>.grocery.database.ComparisonMode comparisonMode = 4;</code>
   * @return The enum numeric value on the wire for comparisonMode.
   */
  @java.lang.Override
  public int getComparisonModeValue() {
    return comparisonMode_;
  }
  /**
   * <code>.grocery.database.ComparisonMode comparisonMode = 4;</code>
   * @return The comparisonMode.
   */
  @java.lang.Override
  public com.example.grocerystoreorganizer.grpc.ComparisonMode getComparisonMode() {
    com.example.grocerystoreorganizer.grpc.ComparisonMode result = com.example.grocerystoreorganizer.grpc.ComparisonMode.forNumber(comparisonMode_);
    return result == null ? com.example.grocerystoreorganizer.grpc.ComparisonMode.UNRECOGNIZED : result;
  }
  /**
   * <code>.grocery.database.ComparisonMode comparisonMode = 4;</code>
   * @param value The enum numeric value on the wire for comparisonMode to set.
   */
  private void setComparisonModeValue(int value) {
      comparisonMode_ = value;
  }
  /**
   * <code>.grocery.database.ComparisonMode comparisonMode = 4;</code>
   * @param value The comparisonMode to set.
   */
  private void setComparisonMode(com.example.grocerystoreorganizer.grpc.ComparisonMode value) {
    comparisonMode_ = value.getNumber();
    
  }
  /**
   * <code>.grocery.database.ComparisonMode comparisonMode = 4;</code>
   */
  private void clearComparisonMode() {
    
    comparisonMode_ = 0;
  }

  public static final int PREFERREDUPC_FIELD_NUMBER = 5;
  private java.lang.String preferredUpc_;
  /**
   * <code>optional string preferredUpc = 5;</code>
   * @return Whether the preferredUpc field is set.
   */
  @java.lang.Override
  public boolean hasPreferredUpc() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>optional string preferredUpc = 5;</code>
   * @return The preferredUpc.
   */
  @java.lang.Override
  public java.lang.String getPreferredUpc() {
    return preferredUpc_;
  }
  /**
   * <code>optional string preferredUpc = 5;</code>
   * @return The bytes for preferredUpc.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getPreferredUpcBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(preferredUpc_);
  }
  /**
   * <code>optional string preferredUpc = 5;</code>
   * @param value The preferredUpc to set.
   */
  private void setPreferredUpc(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  bitField0_ |= 0x00000001;
    preferredUpc_ = value;
  }
  /**
   * <code>optional string preferredUpc = 5;</code>
   */
  private void clearPreferredUpc() {
    bitField0_ = (bitField0_ & ~0x00000001);
    preferredUpc_ = getDefaultInstance().getPreferredUpc();
  }
  /**
   * <code>optional string preferredUpc = 5;</code>
   * @param value The bytes for preferredUpc to set.
   */
  private void setPreferredUpcBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    preferredUpc_ = value.toStringUtf8();
    bitField0_ |= 0x00000001;
  }

  public static com.example.grocerystoreorganizer.grpc.GroceryListOptimizationItem parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.example.grocerystoreorganizer.grpc.GroceryListOptimizationItem parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.example.grocerystoreorganizer.grpc.GroceryListOptimizationItem parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.example.grocerystoreorganizer.grpc.GroceryListOptimizationItem parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.example.grocerystoreorganizer.grpc.GroceryListOptimizationItem parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.example.grocerystoreorganizer.grpc.GroceryListOptimizationItem parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.example.grocerystoreorganizer.grpc.GroceryListOptimizationItem parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.example.grocerystoreorganizer.grpc.GroceryListOptimizationItem parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.example.grocerystoreorganizer.grpc.GroceryListOptimizationItem parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static com.example.grocerystoreorganizer.grpc.GroceryListOptimizationItem parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.example.grocerystoreorganizer.grpc.GroceryListOptimizationItem parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.example.grocerystoreorganizer.grpc.GroceryListOptimizationItem parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(com.example.grocerystoreorganizer.grpc.GroceryListOptimizationItem prototype) {
    return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code grocery.database.GroceryListOptimizationItem}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.example.grocerystoreorganizer.grpc.GroceryListOptimizationItem, Builder> implements
      // @@protoc_insertion_point(builder_implements:grocery.database.GroceryListOptimizationItem)
      com.example.grocerystoreorganizer.grpc.GroceryListOptimizationItemOrBuilder {
    // Construct using com.example.grocerystoreorganizer.grpc.GroceryListOptimizationItem.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>int32 itemId = 1;</code>
     * @return The itemId.
     */
    @java.lang.Override
    public int getItemId() {
      return instance.getItemId();
    }
    /**
     * <code>int32 itemId = 1;</code>
     * @param value The itemId to set.
     * @return This builder for chaining.
     */
    public Builder setItemId(int value) {
      copyOnWrite();
      instance.setItemId(value);
      return this;
    }
    /**
     * <code>int32 itemId = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearItemId() {
      copyOnWrite();
      instance.clearItemId();
      return this;
    }

    /**
     * <code>string productName = 2;</code>
     * @return The productName.
     */
    @java.lang.Override
    public java.lang.String getProductName() {
      return instance.getProductName();
    }
    /**
     * <code>string productName = 2;</code>
     * @return The bytes for productName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getProductNameBytes() {
      return instance.getProductNameBytes();
    }
    /**
     * <code>string productName = 2;</code>
     * @param value The productName to set.
     * @return This builder for chaining.
     */
    public Builder setProductName(
        java.lang.String value) {
      copyOnWrite();
      instance.setProductName(value);
      return this;
    }
    /**
     * <code>string productName = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearProductName() {
      copyOnWrite();
      instance.clearProductName();
      return this;
    }
    /**
     * <code>string productName = 2;</code>
     * @param value The bytes for productName to set.
     * @return This builder for chaining.
     */
    public Builder setProductNameBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setProductNameBytes(value);
      return this;
    }

    /**
     * <code>int32 desiredCount = 3;</code>
     * @return The desiredCount.
     */
    @java.lang.Override
    public int getDesiredCount() {
      return instance.getDesiredCount();
    }
    /**
     * <code>int32 desiredCount = 3;</code>
     * @param value The desiredCount to set.
     * @return This builder for chaining.
     */
    public Builder setDesiredCount(int value) {
      copyOnWrite();
      instance.setDesiredCount(value);
      return this;
    }
    /**
     * <code>int32 desiredCount = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearDesiredCount() {
      copyOnWrite();
      instance.clearDesiredCount();
      return this;
    }

    /**
     * <code>.grocery.database.ComparisonMode comparisonMode = 4;</code>
     * @return The enum numeric value on the wire for comparisonMode.
     */
    @java.lang.Override
    public int getComparisonModeValue() {
      return instance.getComparisonModeValue();
    }
    /**
     * <code>.grocery.database.ComparisonMode comparisonMode = 4;</code>
     * @param value The comparisonMode to set.
     * @return This builder for chaining.
     */
    public Builder setComparisonModeValue(int value) {
      copyOnWrite();
      instance.setComparisonModeValue(value);
      return this;
    }
    /**
     * <code>.grocery.database.ComparisonMode comparisonMode = 4;</code>
     * @return The comparisonMode.
     */
    @java.lang.Override
    public com.example.grocerystoreorganizer.grpc.ComparisonMode getComparisonMode() {
      return instance.getComparisonMode();
    }
    /**
     * <code>.grocery.database.ComparisonMode comparisonMode = 4;</code>
     * @param value The enum numeric value on the wire for comparisonMode to set.
     * @return This builder for chaining.
     */
    public Builder setComparisonMode(com.example.grocerystoreorganizer.grpc.ComparisonMode value) {
      copyOnWrite();
      instance.setComparisonMode(value);
      return this;
    }
    /**
     * <code>.grocery.database.ComparisonMode comparisonMode = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearComparisonMode() {
      copyOnWrite();
      instance.clearComparisonMode();
      return this;
    }

    /**
     * <code>optional string preferredUpc = 5;</code>
     * @return Whether the preferredUpc field is set.
     */
    @java.lang.Override
    public boolean hasPreferredUpc() {
      return instance.hasPreferredUpc();
    }
    /**
     * <code>optional string preferredUpc = 5;</code>
     * @return The preferredUpc.
     */
    @java.lang.Override
    public java.lang.String getPreferredUpc() {
      return instance.getPreferredUpc();
    }
    /**
     * <code>optional string preferredUpc = 5;</code>
     * @return The bytes for preferredUpc.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getPreferredUpcBytes() {
      return instance.getPreferredUpcBytes();
    }
    /**
     * <code>optional string preferredUpc = 5;</code>
     * @param value The preferredUpc to set.
     * @return This builder for chaining.
     */
    public Builder setPreferredUpc(
        java.lang.String value) {
      copyOnWrite();
      instance.setPreferredUpc(value);
      return this;
    }
    /**
     * <code>optional string preferredUpc = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearPreferredUpc() {
      copyOnWrite();
      instance.clearPreferredUpc();
      return this;
    }
    /**
     * <code>optional string preferredUpc = 5;</code>
     * @param value The bytes for preferredUpc to set.
     * @return This builder for chaining.
     */
    public Builder setPreferredUpcBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setPreferredUpcBytes(value);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:grocery.database.GroceryListOptimizationItem)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.example.grocerystoreorganizer.grpc.GroceryListOptimizationItem();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "bitField0_",
            "itemId_",
            "productName_",
            "desiredCount_",
            "comparisonMode_",
            "preferredUpc_",
          };
          java.lang.String info =
              "\u0000\u0005\u0000\u0001\u0001\u0005\u0005\u0000\u0000\u0000\u0001\u0004\u0002\u0208" +
              "\u0003\u0004\u0004\f\u0005\u1208\u0000";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<com.example.grocerystoreorganizer.grpc.GroceryListOptimizationItem> parser = PARSER;
        if (parser == null) {
          synchronized (com.example.grocerystoreorganizer.grpc.GroceryListOptimizationItem.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<com.example.grocerystoreorganizer.grpc.GroceryListOptimizationItem>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:grocery.database.GroceryListOptimizationItem)
  private static final com.example.grocerystoreorganizer.grpc.GroceryListOptimizationItem DEFAULT_INSTANCE;
  static {
    GroceryListOptimizationItem defaultInstance = new GroceryListOptimizationItem();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      GroceryListOptimizationItem.class, defaultInstance);
  }

  public static com.example.grocerystoreorganizer.grpc.GroceryListOptimizationItem getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<GroceryListOptimizationItem> PARSER;

  public static com.google.protobuf.Parser<GroceryListOptimizationItem> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

