// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: db_service.proto

package com.example.grocerystoreorganizer.grpc;

public interface GroceryListOptimizationItemOrBuilder extends
    // @@protoc_insertion_point(interface_extends:grocery.database.GroceryListOptimizationItem)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>int32 itemId = 1;</code>
   * @return The itemId.
   */
  int getItemId();

  /**
   * <code>string productName = 2;</code>
   * @return The productName.
   */
  java.lang.String getProductName();
  /**
   * <code>string productName = 2;</code>
   * @return The bytes for productName.
   */
  com.google.protobuf.ByteString
      getProductNameBytes();

  /**
   * <code>int32 desiredCount = 3;</code>
   * @return The desiredCount.
   */
  int getDesiredCount();

  /**
   * <code>.grocery.database.ComparisonMode comparisonMode = 4;</code>
   * @return The enum numeric value on the wire for comparisonMode.
   */
  int getComparisonModeValue();
  /**
   * <code>.grocery.database.ComparisonMode comparisonMode = 4;</code>
   * @return The comparisonMode.
   */
  com.example.grocerystoreorganizer.grpc.ComparisonMode getComparisonMode();

  /**
   * <code>optional string preferredUpc = 5;</code>
   * @return Whether the preferredUpc field is set.
   */
  boolean hasPreferredUpc();
  /**
   * <code>optional string preferredUpc = 5;</code>
   * @return The preferredUpc.
   */
  java.lang.String getPreferredUpc();
  /**
   * <code>optional string preferredUpc = 5;</code>
   * @return The bytes for preferredUpc.
   */
  com.google.protobuf.ByteString
      getPreferredUpcBytes();
}
