// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: db_service.proto

package com.example.grocerystoreorganizer.grpc;

public interface ListVariantsForProductRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:grocery.database.ListVariantsForProductRequest)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>string productName = 1;</code>
   * @return The productName.
   */
  java.lang.String getProductName();
  /**
   * <code>string productName = 1;</code>
   * @return The bytes for productName.
   */
  com.google.protobuf.ByteString
      getProductNameBytes();

  /**
   * <code>optional string updatedAfter = 2;</code>
   * @return Whether the updatedAfter field is set.
   */
  boolean hasUpdatedAfter();
  /**
   * <code>optional string updatedAfter = 2;</code>
   * @return The updatedAfter.
   */
  java.lang.String getUpdatedAfter();
  /**
   * <code>optional string updatedAfter = 2;</code>
   * @return The bytes for updatedAfter.
   */
  com.google.protobuf.ByteString
      getUpdatedAfterBytes();
}
