// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: db_service.proto

package com.example.grocerystoreorganizer.grpc;

/**
 * Protobuf type {@code grocery.database.ListProductsResponse}
 */
public  final class ListProductsResponse extends
    com.google.protobuf.GeneratedMessageLite<
        ListProductsResponse, ListProductsResponse.Builder> implements
    // @@protoc_insertion_point(message_implements:grocery.database.ListProductsResponse)
    ListProductsResponseOrBuilder {
  private ListProductsResponse() {
    products_ = emptyProtobufList();
    nextSyncToken_ = "";
  }
  public static final int PRODUCTS_FIELD_NUMBER = 1;
  private com.google.protobuf.Internal.ProtobufList<com.example.grocerystoreorganizer.grpc.ProductInfo> products_;
  /**
   * <code>repeated .grocery.database.ProductInfo products = 1;</code>
   */
  @java.lang.Override
  public java.util.List<com.example.grocerystoreorganizer.grpc.ProductInfo> getProductsList() {
    return products_;
  }
  /**
   * <code>repeated .grocery.database.ProductInfo products = 1;</code>
   */
  public java.util.List<? extends com.example.grocerystoreorganizer.grpc.ProductInfoOrBuilder> 
      getProductsOrBuilderList() {
    return products_;
  }
  /**
   * <code>repeated .grocery.database.ProductInfo products = 1;</code>
   */
  @java.lang.Override
  public int getProductsCount() {
    return products_.size();
  }
  /**
   * <code>repeated .grocery.database.ProductInfo products = 1;</code>
   */
  @java.lang.Override
  public com.example.grocerystoreorganizer.grpc.ProductInfo getProducts(int index) {
    return products_.get(index);
  }
  /**
   * <code>repeated .grocery.database.ProductInfo products = 1;</code>
   */
  public com.example.grocerystoreorganizer.grpc.ProductInfoOrBuilder getProductsOrBuilder(
      int index) {
    return products_.get(index);
  }
  private void ensureProductsIsMutable() {
    com.google.protobuf.Internal.ProtobufList<com.example.grocerystoreorganizer.grpc.ProductInfo> tmp = products_;
    if (!tmp.isModifiable()) {
      products_ =
          com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
     }
  }

  /**
   * <code>repeated .grocery.database.ProductInfo products = 1;</code>
   */
  private void setProducts(
      int index, com.example.grocerystoreorganizer.grpc.ProductInfo value) {
    value.getClass();
  ensureProductsIsMutable();
    products_.set(index, value);
  }
  /**
   * <code>repeated .grocery.database.ProductInfo products = 1;</code>
   */
  private void addProducts(com.example.grocerystoreorganizer.grpc.ProductInfo value) {
    value.getClass();
  ensureProductsIsMutable();
    products_.add(value);
  }
  /**
   * <code>repeated .grocery.database.ProductInfo products = 1;</code>
   */
  private void addProducts(
      int index, com.example.grocerystoreorganizer.grpc.ProductInfo value) {
    value.getClass();
  ensureProductsIsMutable();
    products_.add(index, value);
  }
  /**
   * <code>repeated .grocery.database.ProductInfo products = 1;</code>
   */
  private void addAllProducts(
      java.lang.Iterable<? extends com.example.grocerystoreorganizer.grpc.ProductInfo> values) {
    ensureProductsIsMutable();
    com.google.protobuf.AbstractMessageLite.addAll(
        values, products_);
  }
  /**
   * <code>repeated .grocery.database.ProductInfo products = 1;</code>
   */
  private void clearProducts() {
    products_ = emptyProtobufList();
  }
  /**
   * <code>repeated .grocery.database.ProductInfo products = 1;</code>
   */
  private void removeProducts(int index) {
    ensureProductsIsMutable();
    products_.remove(index);
  }

  public static final int NEXTSYNCTOKEN_FIELD_NUMBER = 2;
  private java.lang.String nextSyncToken_;
  /**
   * <code>string nextSyncToken = 2;</code>
   * @return The nextSyncToken.
   */
  @java.lang.Override
  public java.lang.String getNextSyncToken() {
    return nextSyncToken_;
  }
  /**
   * <code>string nextSyncToken = 2;</code>
   * @return The bytes for nextSyncToken.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNextSyncTokenBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(nextSyncToken_);
  }
  /**
   * <code>string nextSyncToken = 2;</code>
   * @param value The nextSyncToken to set.
   */
  private void setNextSyncToken(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    nextSyncToken_ = value;
  }
  /**
   * <code>string nextSyncToken = 2;</code>
   */
  private void clearNextSyncToken() {
    
    nextSyncToken_ = getDefaultInstance().getNextSyncToken();
  }
  /**
   * <code>string nextSyncToken = 2;</code>
   * @param value The bytes for nextSyncToken to set.
   */
  private void setNextSyncTokenBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    nextSyncToken_ = value.toStringUtf8();
    
  }

  public static com.example.grocerystoreorganizer.grpc.ListProductsResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.example.grocerystoreorganizer.grpc.ListProductsResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.example.grocerystoreorganizer.grpc.ListProductsResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.example.grocerystoreorganizer.grpc.ListProductsResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.example.grocerystoreorganizer.grpc.ListProductsResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.example.grocerystoreorganizer.grpc.ListProductsResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.example.grocerystoreorganizer.grpc.ListProductsResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.example.grocerystoreorganizer.grpc.ListProductsResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.example.grocerystoreorganizer.grpc.ListProductsResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static com.example.grocerystoreorganizer.grpc.ListProductsResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.example.grocerystoreorganizer.grpc.ListProductsResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.example.grocerystoreorganizer.grpc.ListProductsResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(com.example.grocerystoreorganizer.grpc.ListProductsResponse prototype) {
    return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code grocery.database.ListProductsResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.example.grocerystoreorganizer.grpc.ListProductsResponse, Builder> implements
      // @@protoc_insertion_point(builder_implements:grocery.database.ListProductsResponse)
      com.example.grocerystoreorganizer.grpc.ListProductsResponseOrBuilder {
    // Construct using com.example.grocerystoreorganizer.grpc.ListProductsResponse.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>repeated .grocery.database.ProductInfo products = 1;</code>
     */
    @java.lang.Override
    public java.util.List<com.example.grocerystoreorganizer.grpc.ProductInfo> getProductsList() {
      return java.util.Collections.unmodifiableList(
          instance.getProductsList());
    }
    /**
     * <code>repeated .grocery.database.ProductInfo products = 1;</code>
     */
    @java.lang.Override
    public int getProductsCount() {
      return instance.getProductsCount();
    }/**
     * <code>repeated .grocery.database.ProductInfo products = 1;</code>
     */
    @java.lang.Override
    public com.example.grocerystoreorganizer.grpc.ProductInfo getProducts(int index) {
      return instance.getProducts(index);
    }
    /**
     * <code>repeated .grocery.database.ProductInfo products = 1;</code>
     */
    public Builder setProducts(
        int index, com.example.grocerystoreorganizer.grpc.ProductInfo value) {
      copyOnWrite();
      instance.setProducts(index, value);
      return this;
    }
    /**
     * <code>repeated .grocery.database.ProductInfo products = 1;</code>
     */
    public Builder setProducts(
        int index, com.example.grocerystoreorganizer.grpc.ProductInfo.Builder builderForValue) {
      copyOnWrite();
      instance.setProducts(index,
          builderForValue.build());
      return this;
    }
    /**
     * <code>repeated .grocery.database.ProductInfo products = 1;</code>
     */
    public Builder addProducts(com.example.grocerystoreorganizer.grpc.ProductInfo value) {
      copyOnWrite();
      instance.addProducts(value);
      return this;
    }
    /**
     * <code>repeated .grocery.database.ProductInfo products = 1;</code>
     */
    public Builder addProducts(
        int index, com.example.grocerystoreorganizer.grpc.ProductInfo value) {
      copyOnWrite();
      instance.addProducts(index, value);
      return this;
    }
    /**
     * <code>repeated .grocery.database.ProductInfo products = 1;</code>
     */
    public Builder addProducts(
        com.example.grocerystoreorganizer.grpc.ProductInfo.Builder builderForValue) {
      copyOnWrite();
      instance.addProducts(builderForValue.build());
      return this;
    }
    /**
     * <code>repeated .grocery.database.ProductInfo products = 1;</code>
     */
    public Builder addProducts(
        int index, com.example.grocerystoreorganizer.grpc.ProductInfo.Builder builderForValue) {
      copyOnWrite();
      instance.addProducts(index,
          builderForValue.build());
      return this;
    }
    /**
     * <code>repeated .grocery.database.ProductInfo products = 1;</code>
     */
    public Builder addAllProducts(
        java.lang.Iterable<? extends com.example.grocerystoreorganizer.grpc.ProductInfo> values) {
      copyOnWrite();
      instance.addAllProducts(values);
      return this;
    }
    /**
     * <code>repeated .grocery.database.ProductInfo products = 1;</code>
     */
    public Builder clearProducts() {
      copyOnWrite();
      instance.clearProducts();
      return this;
    }
    /**
     * <code>repeated .grocery.database.ProductInfo products = 1;</code>
     */
    public Builder removeProducts(int index) {
      copyOnWrite();
      instance.removeProducts(index);
      return this;
    }

    /**
     * <code>string nextSyncToken = 2;</code>
     * @return The nextSyncToken.
     */
    @java.lang.Override
    public java.lang.String getNextSyncToken() {
      return instance.getNextSyncToken();
    }
    /**
     * <code>string nextSyncToken = 2;</code>
     * @return The bytes for nextSyncToken.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNextSyncTokenBytes() {
      return instance.getNextSyncTokenBytes();
    }
    /**
     * <code>string nextSyncToken = 2;</code>
     * @param value The nextSyncToken to set.
     * @return This builder for chaining.
     */
    public Builder setNextSyncToken(
        java.lang.String value) {
      copyOnWrite();
      instance.setNextSyncToken(value);
      return this;
    }
    /**
     * <code>string nextSyncToken = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearNextSyncToken() {
      copyOnWrite();
      instance.clearNextSyncToken();
      return this;
    }
    /**
     * <code>string nextSyncToken = 2;</code>
     * @param value The bytes for nextSyncToken to set.
     * @return This builder for chaining.
     */
    public Builder setNextSyncTokenBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setNextSyncTokenBytes(value);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:grocery.database.ListProductsResponse)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.example.grocerystoreorganizer.grpc.ListProductsResponse();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "products_",
            com.example.grocerystoreorganizer.grpc.ProductInfo.class,
            "nextSyncToken_",
          };
          java.lang.String info =
              "\u0000\u0002\u0000\u0000\u0001\u0002\u0002\u0000\u0001\u0000\u0001\u001b\u0002\u0208" +
              "";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<com.example.grocerystoreorganizer.grpc.ListProductsResponse> parser = PARSER;
        if (parser == null) {
          synchronized (com.example.grocerystoreorganizer.grpc.ListProductsResponse.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<com.example.grocerystoreorganizer.grpc.ListProductsResponse>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:grocery.database.ListProductsResponse)
  private static final com.example.grocerystoreorganizer.grpc.ListProductsResponse DEFAULT_INSTANCE;
  static {
    ListProductsResponse defaultInstance = new ListProductsResponse();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      ListProductsResponse.class, defaultInstance);
  }

  public static com.example.grocerystoreorganizer.grpc.ListProductsResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<ListProductsResponse> PARSER;

  public static com.google.protobuf.Parser<ListProductsResponse> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

