// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: db_service.proto

package com.example.grocerystoreorganizer.grpc;

/**
 * Protobuf type {@code grocery.database.ListVariantsForProductRequest}
 */
public  final class ListVariantsForProductRequest extends
    com.google.protobuf.GeneratedMessageLite<
        ListVariantsForProductRequest, ListVariantsForProductRequest.Builder> implements
    // @@protoc_insertion_point(message_implements:grocery.database.ListVariantsForProductRequest)
    ListVariantsForProductRequestOrBuilder {
  private ListVariantsForProductRequest() {
    productName_ = "";
    updatedAfter_ = "";
  }
  private int bitField0_;
  public static final int PRODUCTNAME_FIELD_NUMBER = 1;
  private java.lang.String productName_;
  /**
   * <code>string productName = 1;</code>
   * @return The productName.
   */
  @java.lang.Override
  public java.lang.String getProductName() {
    return productName_;
  }
  /**
   * <code>string productName = 1;</code>
   * @return The bytes for productName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getProductNameBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(productName_);
  }
  /**
   * <code>string productName = 1;</code>
   * @param value The productName to set.
   */
  private void setProductName(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    productName_ = value;
  }
  /**
   * <code>string productName = 1;</code>
   */
  private void clearProductName() {
    
    productName_ = getDefaultInstance().getProductName();
  }
  /**
   * <code>string productName = 1;</code>
   * @param value The bytes for productName to set.
   */
  private void setProductNameBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    productName_ = value.toStringUtf8();
    
  }

  public static final int UPDATEDAFTER_FIELD_NUMBER = 2;
  private java.lang.String updatedAfter_;
  /**
   * <code>optional string updatedAfter = 2;</code>
   * @return Whether the updatedAfter field is set.
   */
  @java.lang.Override
  public boolean hasUpdatedAfter() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>optional string updatedAfter = 2;</code>
   * @return The updatedAfter.
   */
  @java.lang.Override
  public java.lang.String getUpdatedAfter() {
    return updatedAfter_;
  }
  /**
   * <code>optional string updatedAfter = 2;</code>
   * @return The bytes for updatedAfter.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getUpdatedAfterBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(updatedAfter_);
  }
  /**
   * <code>optional string updatedAfter = 2;</code>
   * @param value The updatedAfter to set.
   */
  private void setUpdatedAfter(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  bitField0_ |= 0x00000001;
    updatedAfter_ = value;
  }
  /**
   * <code>optional string updatedAfter = 2;</code>
   */
  private void clearUpdatedAfter() {
    bitField0_ = (bitField0_ & ~0x00000001);
    updatedAfter_ = getDefaultInstance().getUpdatedAfter();
  }
  /**
   * <code>optional string updatedAfter = 2;</code>
   * @param value The bytes for updatedAfter to set.
   */
  private void setUpdatedAfterBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    updatedAfter_ = value.toStringUtf8();
    bitField0_ |= 0x00000001;
  }

  public static com.example.grocerystoreorganizer.grpc.ListVariantsForProductRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.example.grocerystoreorganizer.grpc.ListVariantsForProductRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.example.grocerystoreorganizer.grpc.ListVariantsForProductRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.example.grocerystoreorganizer.grpc.ListVariantsForProductRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.example.grocerystoreorganizer.grpc.ListVariantsForProductRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.example.grocerystoreorganizer.grpc.ListVariantsForProductRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.example.grocerystoreorganizer.grpc.ListVariantsForProductRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.example.grocerystoreorganizer.grpc.ListVariantsForProductRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.example.grocerystoreorganizer.grpc.ListVariantsForProductRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static com.example.grocerystoreorganizer.grpc.ListVariantsForProductRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.example.grocerystoreorganizer.grpc.ListVariantsForProductRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.example.grocerystoreorganizer.grpc.ListVariantsForProductRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(com.example.grocerystoreorganizer.grpc.ListVariantsForProductRequest prototype) {
    return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code grocery.database.ListVariantsForProductRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.example.grocerystoreorganizer.grpc.ListVariantsForProductRequest, Builder> implements
      // @@protoc_insertion_point(builder_implements:grocery.database.ListVariantsForProductRequest)
      com.example.grocerystoreorganizer.grpc.ListVariantsForProductRequestOrBuilder {
    // Construct using com.example.grocerystoreorganizer.grpc.ListVariantsForProductRequest.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>string productName = 1;</code>
     * @return The productName.
     */
    @java.lang.Override
    public java.lang.String getProductName() {
      return instance.getProductName();
    }
    /**
     * <code>string productName = 1;</code>
     * @return The bytes for productName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getProductNameBytes() {
      return instance.getProductNameBytes();
    }
    /**
     * <code>string productName = 1;</code>
     * @param value The productName to set.
     * @return This builder for chaining.
     */
    public Builder setProductName(
        java.lang.String value) {
      copyOnWrite();
      instance.setProductName(value);
      return this;
    }
    /**
     * <code>string productName = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearProductName() {
      copyOnWrite();
      instance.clearProductName();
      return this;
    }
    /**
     * <code>string productName = 1;</code>
     * @param value The bytes for productName to set.
     * @return This builder for chaining.
     */
    public Builder setProductNameBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setProductNameBytes(value);
      return this;
    }

    /**
     * <code>optional string updatedAfter = 2;</code>
     * @return Whether the updatedAfter field is set.
     */
    @java.lang.Override
    public boolean hasUpdatedAfter() {
      return instance.hasUpdatedAfter();
    }
    /**
     * <code>optional string updatedAfter = 2;</code>
     * @return The updatedAfter.
     */
    @java.lang.Override
    public java.lang.String getUpdatedAfter() {
      return instance.getUpdatedAfter();
    }
    /**
     * <code>optional string updatedAfter = 2;</code>
     * @return The bytes for updatedAfter.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getUpdatedAfterBytes() {
      return instance.getUpdatedAfterBytes();
    }
    /**
     * <code>optional string updatedAfter = 2;</code>
     * @param value The updatedAfter to set.
     * @return This builder for chaining.
     */
    public Builder setUpdatedAfter(
        java.lang.String value) {
      copyOnWrite();
      instance.setUpdatedAfter(value);
      return this;
    }
    /**
     * <code>optional string updatedAfter = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearUpdatedAfter() {
      copyOnWrite();
      instance.clearUpdatedAfter();
      return this;
    }
    /**
     * <code>optional string updatedAfter = 2;</code>
     * @param value The bytes for updatedAfter to set.
     * @return This builder for chaining.
     */
    public Builder setUpdatedAfterBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setUpdatedAfterBytes(value);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:grocery.database.ListVariantsForProductRequest)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.example.grocerystoreorganizer.grpc.ListVariantsForProductRequest();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "bitField0_",
            "productName_",
            "updatedAfter_",
          };
          java.lang.String info =
              "\u0000\u0002\u0000\u0001\u0001\u0002\u0002\u0000\u0000\u0000\u0001\u0208\u0002\u1208" +
              "\u0000";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<com.example.grocerystoreorganizer.grpc.ListVariantsForProductRequest> parser = PARSER;
        if (parser == null) {
          synchronized (com.example.grocerystoreorganizer.grpc.ListVariantsForProductRequest.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<com.example.grocerystoreorganizer.grpc.ListVariantsForProductRequest>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:grocery.database.ListVariantsForProductRequest)
  private static final com.example.grocerystoreorganizer.grpc.ListVariantsForProductRequest DEFAULT_INSTANCE;
  static {
    ListVariantsForProductRequest defaultInstance = new ListVariantsForProductRequest();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      ListVariantsForProductRequest.class, defaultInstance);
  }

  public static com.example.grocerystoreorganizer.grpc.ListVariantsForProductRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<ListVariantsForProductRequest> PARSER;

  public static com.google.protobuf.Parser<ListVariantsForProductRequest> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

