// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: db_service.proto

package com.example.grocerystoreorganizer.grpc;

public interface ListVariantsForProductResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:grocery.database.ListVariantsForProductResponse)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>repeated .grocery.database.UpcInfo variants = 1;</code>
   */
  java.util.List<com.example.grocerystoreorganizer.grpc.UpcInfo> 
      getVariantsList();
  /**
   * <code>repeated .grocery.database.UpcInfo variants = 1;</code>
   */
  com.example.grocerystoreorganizer.grpc.UpcInfo getVariants(int index);
  /**
   * <code>repeated .grocery.database.UpcInfo variants = 1;</code>
   */
  int getVariantsCount();

  /**
   * <code>string nextSyncToken = 2;</code>
   * @return The nextSyncToken.
   */
  java.lang.String getNextSyncToken();
  /**
   * <code>string nextSyncToken = 2;</code>
   * @return The bytes for nextSyncToken.
   */
  com.google.protobuf.ByteString
      getNextSyncTokenBytes();
}
