// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: db_service.proto

package com.example.grocerystoreorganizer.grpc;

public interface ListProductsResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:grocery.database.ListProductsResponse)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>repeated .grocery.database.ProductInfo products = 1;</code>
   */
  java.util.List<com.example.grocerystoreorganizer.grpc.ProductInfo> 
      getProductsList();
  /**
   * <code>repeated .grocery.database.ProductInfo products = 1;</code>
   */
  com.example.grocerystoreorganizer.grpc.ProductInfo getProducts(int index);
  /**
   * <code>repeated .grocery.database.ProductInfo products = 1;</code>
   */
  int getProductsCount();

  /**
   * <code>string nextSyncToken = 2;</code>
   * @return The nextSyncToken.
   */
  java.lang.String getNextSyncToken();
  /**
   * <code>string nextSyncToken = 2;</code>
   * @return The bytes for nextSyncToken.
   */
  com.google.protobuf.ByteString
      getNextSyncTokenBytes();
}
