// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: db_service.proto

package com.example.grocerystoreorganizer.grpc;

/**
 * Protobuf type {@code grocery.database.ListVariantsForProductResponse}
 */
public  final class ListVariantsForProductResponse extends
    com.google.protobuf.GeneratedMessageLite<
        ListVariantsForProductResponse, ListVariantsForProductResponse.Builder> implements
    // @@protoc_insertion_point(message_implements:grocery.database.ListVariantsForProductResponse)
    ListVariantsForProductResponseOrBuilder {
  private ListVariantsForProductResponse() {
    variants_ = emptyProtobufList();
    nextSyncToken_ = "";
  }
  public static final int VARIANTS_FIELD_NUMBER = 1;
  private com.google.protobuf.Internal.ProtobufList<com.example.grocerystoreorganizer.grpc.UpcInfo> variants_;
  /**
   * <code>repeated .grocery.database.UpcInfo variants = 1;</code>
   */
  @java.lang.Override
  public java.util.List<com.example.grocerystoreorganizer.grpc.UpcInfo> getVariantsList() {
    return variants_;
  }
  /**
   * <code>repeated .grocery.database.UpcInfo variants = 1;</code>
   */
  public java.util.List<? extends com.example.grocerystoreorganizer.grpc.UpcInfoOrBuilder> 
      getVariantsOrBuilderList() {
    return variants_;
  }
  /**
   * <code>repeated .grocery.database.UpcInfo variants = 1;</code>
   */
  @java.lang.Override
  public int getVariantsCount() {
    return variants_.size();
  }
  /**
   * <code>repeated .grocery.database.UpcInfo variants = 1;</code>
   */
  @java.lang.Override
  public com.example.grocerystoreorganizer.grpc.UpcInfo getVariants(int index) {
    return variants_.get(index);
  }
  /**
   * <code>repeated .grocery.database.UpcInfo variants = 1;</code>
   */
  public com.example.grocerystoreorganizer.grpc.UpcInfoOrBuilder getVariantsOrBuilder(
      int index) {
    return variants_.get(index);
  }
  private void ensureVariantsIsMutable() {
    com.google.protobuf.Internal.ProtobufList<com.example.grocerystoreorganizer.grpc.UpcInfo> tmp = variants_;
    if (!tmp.isModifiable()) {
      variants_ =
          com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
     }
  }

  /**
   * <code>repeated .grocery.database.UpcInfo variants = 1;</code>
   */
  private void setVariants(
      int index, com.example.grocerystoreorganizer.grpc.UpcInfo value) {
    value.getClass();
  ensureVariantsIsMutable();
    variants_.set(index, value);
  }
  /**
   * <code>repeated .grocery.database.UpcInfo variants = 1;</code>
   */
  private void addVariants(com.example.grocerystoreorganizer.grpc.UpcInfo value) {
    value.getClass();
  ensureVariantsIsMutable();
    variants_.add(value);
  }
  /**
   * <code>repeated .grocery.database.UpcInfo variants = 1;</code>
   */
  private void addVariants(
      int index, com.example.grocerystoreorganizer.grpc.UpcInfo value) {
    value.getClass();
  ensureVariantsIsMutable();
    variants_.add(index, value);
  }
  /**
   * <code>repeated .grocery.database.UpcInfo variants = 1;</code>
   */
  private void addAllVariants(
      java.lang.Iterable<? extends com.example.grocerystoreorganizer.grpc.UpcInfo> values) {
    ensureVariantsIsMutable();
    com.google.protobuf.AbstractMessageLite.addAll(
        values, variants_);
  }
  /**
   * <code>repeated .grocery.database.UpcInfo variants = 1;</code>
   */
  private void clearVariants() {
    variants_ = emptyProtobufList();
  }
  /**
   * <code>repeated .grocery.database.UpcInfo variants = 1;</code>
   */
  private void removeVariants(int index) {
    ensureVariantsIsMutable();
    variants_.remove(index);
  }

  public static final int NEXTSYNCTOKEN_FIELD_NUMBER = 2;
  private java.lang.String nextSyncToken_;
  /**
   * <code>string nextSyncToken = 2;</code>
   * @return The nextSyncToken.
   */
  @java.lang.Override
  public java.lang.String getNextSyncToken() {
    return nextSyncToken_;
  }
  /**
   * <code>string nextSyncToken = 2;</code>
   * @return The bytes for nextSyncToken.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNextSyncTokenBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(nextSyncToken_);
  }
  /**
   * <code>string nextSyncToken = 2;</code>
   * @param value The nextSyncToken to set.
   */
  private void setNextSyncToken(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    nextSyncToken_ = value;
  }
  /**
   * <code>string nextSyncToken = 2;</code>
   */
  private void clearNextSyncToken() {
    
    nextSyncToken_ = getDefaultInstance().getNextSyncToken();
  }
  /**
   * <code>string nextSyncToken = 2;</code>
   * @param value The bytes for nextSyncToken to set.
   */
  private void setNextSyncTokenBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    nextSyncToken_ = value.toStringUtf8();
    
  }

  public static com.example.grocerystoreorganizer.grpc.ListVariantsForProductResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.example.grocerystoreorganizer.grpc.ListVariantsForProductResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.example.grocerystoreorganizer.grpc.ListVariantsForProductResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.example.grocerystoreorganizer.grpc.ListVariantsForProductResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.example.grocerystoreorganizer.grpc.ListVariantsForProductResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.example.grocerystoreorganizer.grpc.ListVariantsForProductResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.example.grocerystoreorganizer.grpc.ListVariantsForProductResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.example.grocerystoreorganizer.grpc.ListVariantsForProductResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.example.grocerystoreorganizer.grpc.ListVariantsForProductResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static com.example.grocerystoreorganizer.grpc.ListVariantsForProductResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.example.grocerystoreorganizer.grpc.ListVariantsForProductResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.example.grocerystoreorganizer.grpc.ListVariantsForProductResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(com.example.grocerystoreorganizer.grpc.ListVariantsForProductResponse prototype) {
    return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code grocery.database.ListVariantsForProductResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.example.grocerystoreorganizer.grpc.ListVariantsForProductResponse, Builder> implements
      // @@protoc_insertion_point(builder_implements:grocery.database.ListVariantsForProductResponse)
      com.example.grocerystoreorganizer.grpc.ListVariantsForProductResponseOrBuilder {
    // Construct using com.example.grocerystoreorganizer.grpc.ListVariantsForProductResponse.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>repeated .grocery.database.UpcInfo variants = 1;</code>
     */
    @java.lang.Override
    public java.util.List<com.example.grocerystoreorganizer.grpc.UpcInfo> getVariantsList() {
      return java.util.Collections.unmodifiableList(
          instance.getVariantsList());
    }
    /**
     * <code>repeated .grocery.database.UpcInfo variants = 1;</code>
     */
    @java.lang.Override
    public int getVariantsCount() {
      return instance.getVariantsCount();
    }/**
     * <code>repeated .grocery.database.UpcInfo variants = 1;</code>
     */
    @java.lang.Override
    public com.example.grocerystoreorganizer.grpc.UpcInfo getVariants(int index) {
      return instance.getVariants(index);
    }
    /**
     * <code>repeated .grocery.database.UpcInfo variants = 1;</code>
     */
    public Builder setVariants(
        int index, com.example.grocerystoreorganizer.grpc.UpcInfo value) {
      copyOnWrite();
      instance.setVariants(index, value);
      return this;
    }
    /**
     * <code>repeated .grocery.database.UpcInfo variants = 1;</code>
     */
    public Builder setVariants(
        int index, com.example.grocerystoreorganizer.grpc.UpcInfo.Builder builderForValue) {
      copyOnWrite();
      instance.setVariants(index,
          builderForValue.build());
      return this;
    }
    /**
     * <code>repeated .grocery.database.UpcInfo variants = 1;</code>
     */
    public Builder addVariants(com.example.grocerystoreorganizer.grpc.UpcInfo value) {
      copyOnWrite();
      instance.addVariants(value);
      return this;
    }
    /**
     * <code>repeated .grocery.database.UpcInfo variants = 1;</code>
     */
    public Builder addVariants(
        int index, com.example.grocerystoreorganizer.grpc.UpcInfo value) {
      copyOnWrite();
      instance.addVariants(index, value);
      return this;
    }
    /**
     * <code>repeated .grocery.database.UpcInfo variants = 1;</code>
     */
    public Builder addVariants(
        com.example.grocerystoreorganizer.grpc.UpcInfo.Builder builderForValue) {
      copyOnWrite();
      instance.addVariants(builderForValue.build());
      return this;
    }
    /**
     * <code>repeated .grocery.database.UpcInfo variants = 1;</code>
     */
    public Builder addVariants(
        int index, com.example.grocerystoreorganizer.grpc.UpcInfo.Builder builderForValue) {
      copyOnWrite();
      instance.addVariants(index,
          builderForValue.build());
      return this;
    }
    /**
     * <code>repeated .grocery.database.UpcInfo variants = 1;</code>
     */
    public Builder addAllVariants(
        java.lang.Iterable<? extends com.example.grocerystoreorganizer.grpc.UpcInfo> values) {
      copyOnWrite();
      instance.addAllVariants(values);
      return this;
    }
    /**
     * <code>repeated .grocery.database.UpcInfo variants = 1;</code>
     */
    public Builder clearVariants() {
      copyOnWrite();
      instance.clearVariants();
      return this;
    }
    /**
     * <code>repeated .grocery.database.UpcInfo variants = 1;</code>
     */
    public Builder removeVariants(int index) {
      copyOnWrite();
      instance.removeVariants(index);
      return this;
    }

    /**
     * <code>string nextSyncToken = 2;</code>
     * @return The nextSyncToken.
     */
    @java.lang.Override
    public java.lang.String getNextSyncToken() {
      return instance.getNextSyncToken();
    }
    /**
     * <code>string nextSyncToken = 2;</code>
     * @return The bytes for nextSyncToken.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNextSyncTokenBytes() {
      return instance.getNextSyncTokenBytes();
    }
    /**
     * <code>string nextSyncToken = 2;</code>
     * @param value The nextSyncToken to set.
     * @return This builder for chaining.
     */
    public Builder setNextSyncToken(
        java.lang.String value) {
      copyOnWrite();
      instance.setNextSyncToken(value);
      return this;
    }
    /**
     * <code>string nextSyncToken = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearNextSyncToken() {
      copyOnWrite();
      instance.clearNextSyncToken();
      return this;
    }
    /**
     * <code>string nextSyncToken = 2;</code>
     * @param value The bytes for nextSyncToken to set.
     * @return This builder for chaining.
     */
    public Builder setNextSyncTokenBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setNextSyncTokenBytes(value);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:grocery.database.ListVariantsForProductResponse)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.example.grocerystoreorganizer.grpc.ListVariantsForProductResponse();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "variants_",
            com.example.grocerystoreorganizer.grpc.UpcInfo.class,
            "nextSyncToken_",
          };
          java.lang.String info =
              "\u0000\u0002\u0000\u0000\u0001\u0002\u0002\u0000\u0001\u0000\u0001\u001b\u0002\u0208" +
              "";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<com.example.grocerystoreorganizer.grpc.ListVariantsForProductResponse> parser = PARSER;
        if (parser == null) {
          synchronized (com.example.grocerystoreorganizer.grpc.ListVariantsForProductResponse.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<com.example.grocerystoreorganizer.grpc.ListVariantsForProductResponse>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:grocery.database.ListVariantsForProductResponse)
  private static final com.example.grocerystoreorganizer.grpc.ListVariantsForProductResponse DEFAULT_INSTANCE;
  static {
    ListVariantsForProductResponse defaultInstance = new ListVariantsForProductResponse();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      ListVariantsForProductResponse.class, defaultInstance);
  }

  public static com.example.grocerystoreorganizer.grpc.ListVariantsForProductResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<ListVariantsForProductResponse> PARSER;

  public static com.google.protobuf.Parser<ListVariantsForProductResponse> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

