// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: db_service.proto

package com.example.grocerystoreorganizer.grpc;

public interface ListProductsRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:grocery.database.ListProductsRequest)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>optional string updatedAfter = 1;</code>
   * @return Whether the updatedAfter field is set.
   */
  boolean hasUpdatedAfter();
  /**
   * <code>optional string updatedAfter = 1;</code>
   * @return The updatedAfter.
   */
  java.lang.String getUpdatedAfter();
  /**
   * <code>optional string updatedAfter = 1;</code>
   * @return The bytes for updatedAfter.
   */
  com.google.protobuf.ByteString
      getUpdatedAfterBytes();
}
