// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: db_service.proto

package com.example.grocerystoreorganizer.grpc;

public interface OptimizedStoreOrBuilder extends
    // @@protoc_insertion_point(interface_extends:grocery.database.OptimizedStore)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>uint32 storeId = 1;</code>
   * @return The storeId.
   */
  int getStoreId();

  /**
   * <code>optional string storeName = 2;</code>
   * @return Whether the storeName field is set.
   */
  boolean hasStoreName();
  /**
   * <code>optional string storeName = 2;</code>
   * @return The storeName.
   */
  java.lang.String getStoreName();
  /**
   * <code>optional string storeName = 2;</code>
   * @return The bytes for storeName.
   */
  com.google.protobuf.ByteString
      getStoreNameBytes();

  /**
   * <code>string storeAddress = 3;</code>
   * @return The storeAddress.
   */
  java.lang.String getStoreAddress();
  /**
   * <code>string storeAddress = 3;</code>
   * @return The bytes for storeAddress.
   */
  com.google.protobuf.ByteString
      getStoreAddressBytes();

  /**
   * <code>.grocery.database.Coordinate location = 4;</code>
   * @return Whether the location field is set.
   */
  boolean hasLocation();
  /**
   * <code>.grocery.database.Coordinate location = 4;</code>
   * @return The location.
   */
  com.example.grocerystoreorganizer.grpc.Coordinate getLocation();
}
