// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: db_service.proto

package com.example.grocerystoreorganizer.grpc;

public interface OptimizeGroceryListRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:grocery.database.OptimizeGroceryListRequest)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>repeated .grocery.database.GroceryListOptimizationItem items = 1;</code>
   */
  java.util.List<com.example.grocerystoreorganizer.grpc.GroceryListOptimizationItem> 
      getItemsList();
  /**
   * <code>repeated .grocery.database.GroceryListOptimizationItem items = 1;</code>
   */
  com.example.grocerystoreorganizer.grpc.GroceryListOptimizationItem getItems(int index);
  /**
   * <code>repeated .grocery.database.GroceryListOptimizationItem items = 1;</code>
   */
  int getItemsCount();
}
