// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: db_service.proto

package com.example.grocerystoreorganizer.grpc;

public interface OptimizeGroceryListResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:grocery.database.OptimizeGroceryListResponse)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>repeated .grocery.database.OptimizedItemMatch matches = 1;</code>
   */
  java.util.List<com.example.grocerystoreorganizer.grpc.OptimizedItemMatch> 
      getMatchesList();
  /**
   * <code>repeated .grocery.database.OptimizedItemMatch matches = 1;</code>
   */
  com.example.grocerystoreorganizer.grpc.OptimizedItemMatch getMatches(int index);
  /**
   * <code>repeated .grocery.database.OptimizedItemMatch matches = 1;</code>
   */
  int getMatchesCount();

  /**
   * <code>repeated .grocery.database.UnmatchedOptimizationItem unmatched = 2;</code>
   */
  java.util.List<com.example.grocerystoreorganizer.grpc.UnmatchedOptimizationItem> 
      getUnmatchedList();
  /**
   * <code>repeated .grocery.database.UnmatchedOptimizationItem unmatched = 2;</code>
   */
  com.example.grocerystoreorganizer.grpc.UnmatchedOptimizationItem getUnmatched(int index);
  /**
   * <code>repeated .grocery.database.UnmatchedOptimizationItem unmatched = 2;</code>
   */
  int getUnmatchedCount();
}
