// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: db_service.proto

package com.example.grocerystoreorganizer.grpc;

/**
 * Protobuf type {@code grocery.database.OptimizedVariant}
 */
public  final class OptimizedVariant extends
    com.google.protobuf.GeneratedMessageLite<
        OptimizedVariant, OptimizedVariant.Builder> implements
    // @@protoc_insertion_point(message_implements:grocery.database.OptimizedVariant)
    OptimizedVariantOrBuilder {
  private OptimizedVariant() {
    upc_ = "";
    productName_ = "";
    variantLabel_ = "";
    brand_ = "";
    flavor_ = "";
  }
  private int bitField0_;
  public static final int UPC_FIELD_NUMBER = 1;
  private java.lang.String upc_;
  /**
   * <code>string upc = 1;</code>
   * @return The upc.
   */
  @java.lang.Override
  public java.lang.String getUpc() {
    return upc_;
  }
  /**
   * <code>string upc = 1;</code>
   * @return The bytes for upc.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getUpcBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(upc_);
  }
  /**
   * <code>string upc = 1;</code>
   * @param value The upc to set.
   */
  private void setUpc(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    upc_ = value;
  }
  /**
   * <code>string upc = 1;</code>
   */
  private void clearUpc() {
    
    upc_ = getDefaultInstance().getUpc();
  }
  /**
   * <code>string upc = 1;</code>
   * @param value The bytes for upc to set.
   */
  private void setUpcBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    upc_ = value.toStringUtf8();
    
  }

  public static final int PRODUCTNAME_FIELD_NUMBER = 2;
  private java.lang.String productName_;
  /**
   * <code>string productName = 2;</code>
   * @return The productName.
   */
  @java.lang.Override
  public java.lang.String getProductName() {
    return productName_;
  }
  /**
   * <code>string productName = 2;</code>
   * @return The bytes for productName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getProductNameBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(productName_);
  }
  /**
   * <code>string productName = 2;</code>
   * @param value The productName to set.
   */
  private void setProductName(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    productName_ = value;
  }
  /**
   * <code>string productName = 2;</code>
   */
  private void clearProductName() {
    
    productName_ = getDefaultInstance().getProductName();
  }
  /**
   * <code>string productName = 2;</code>
   * @param value The bytes for productName to set.
   */
  private void setProductNameBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    productName_ = value.toStringUtf8();
    
  }

  public static final int VARIANTLABEL_FIELD_NUMBER = 3;
  private java.lang.String variantLabel_;
  /**
   * <code>string variantLabel = 3;</code>
   * @return The variantLabel.
   */
  @java.lang.Override
  public java.lang.String getVariantLabel() {
    return variantLabel_;
  }
  /**
   * <code>string variantLabel = 3;</code>
   * @return The bytes for variantLabel.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getVariantLabelBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(variantLabel_);
  }
  /**
   * <code>string variantLabel = 3;</code>
   * @param value The variantLabel to set.
   */
  private void setVariantLabel(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    variantLabel_ = value;
  }
  /**
   * <code>string variantLabel = 3;</code>
   */
  private void clearVariantLabel() {
    
    variantLabel_ = getDefaultInstance().getVariantLabel();
  }
  /**
   * <code>string variantLabel = 3;</code>
   * @param value The bytes for variantLabel to set.
   */
  private void setVariantLabelBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    variantLabel_ = value.toStringUtf8();
    
  }

  public static final int PACKCOUNT_FIELD_NUMBER = 4;
  private int packCount_;
  /**
   * <code>int32 packCount = 4;</code>
   * @return The packCount.
   */
  @java.lang.Override
  public int getPackCount() {
    return packCount_;
  }
  /**
   * <code>int32 packCount = 4;</code>
   * @param value The packCount to set.
   */
  private void setPackCount(int value) {
    
    packCount_ = value;
  }
  /**
   * <code>int32 packCount = 4;</code>
   */
  private void clearPackCount() {
    
    packCount_ = 0;
  }

  public static final int NETQUANTITY_FIELD_NUMBER = 5;
  private double netQuantity_;
  /**
   * <code>double netQuantity = 5;</code>
   * @return The netQuantity.
   */
  @java.lang.Override
  public double getNetQuantity() {
    return netQuantity_;
  }
  /**
   * <code>double netQuantity = 5;</code>
   * @param value The netQuantity to set.
   */
  private void setNetQuantity(double value) {
    
    netQuantity_ = value;
  }
  /**
   * <code>double netQuantity = 5;</code>
   */
  private void clearNetQuantity() {
    
    netQuantity_ = 0D;
  }

  public static final int QUANTITYUNIT_FIELD_NUMBER = 6;
  private int quantityUnit_;
  /**
   * <code>.grocery.database.ProductUnit quantityUnit = 6;</code>
   * @return The enum numeric value on the wire for quantityUnit.
   */
  @java.lang.Override
  public int getQuantityUnitValue() {
    return quantityUnit_;
  }
  /**
   * <code>.grocery.database.ProductUnit quantityUnit = 6;</code>
   * @return The quantityUnit.
   */
  @java.lang.Override
  public com.example.grocerystoreorganizer.grpc.ProductUnit getQuantityUnit() {
    com.example.grocerystoreorganizer.grpc.ProductUnit result = com.example.grocerystoreorganizer.grpc.ProductUnit.forNumber(quantityUnit_);
    return result == null ? com.example.grocerystoreorganizer.grpc.ProductUnit.UNRECOGNIZED : result;
  }
  /**
   * <code>.grocery.database.ProductUnit quantityUnit = 6;</code>
   * @param value The enum numeric value on the wire for quantityUnit to set.
   */
  private void setQuantityUnitValue(int value) {
      quantityUnit_ = value;
  }
  /**
   * <code>.grocery.database.ProductUnit quantityUnit = 6;</code>
   * @param value The quantityUnit to set.
   */
  private void setQuantityUnit(com.example.grocerystoreorganizer.grpc.ProductUnit value) {
    quantityUnit_ = value.getNumber();
    
  }
  /**
   * <code>.grocery.database.ProductUnit quantityUnit = 6;</code>
   */
  private void clearQuantityUnit() {
    
    quantityUnit_ = 0;
  }

  public static final int BRAND_FIELD_NUMBER = 7;
  private java.lang.String brand_;
  /**
   * <code>optional string brand = 7;</code>
   * @return Whether the brand field is set.
   */
  @java.lang.Override
  public boolean hasBrand() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>optional string brand = 7;</code>
   * @return The brand.
   */
  @java.lang.Override
  public java.lang.String getBrand() {
    return brand_;
  }
  /**
   * <code>optional string brand = 7;</code>
   * @return The bytes for brand.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getBrandBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(brand_);
  }
  /**
   * <code>optional string brand = 7;</code>
   * @param value The brand to set.
   */
  private void setBrand(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  bitField0_ |= 0x00000001;
    brand_ = value;
  }
  /**
   * <code>optional string brand = 7;</code>
   */
  private void clearBrand() {
    bitField0_ = (bitField0_ & ~0x00000001);
    brand_ = getDefaultInstance().getBrand();
  }
  /**
   * <code>optional string brand = 7;</code>
   * @param value The bytes for brand to set.
   */
  private void setBrandBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    brand_ = value.toStringUtf8();
    bitField0_ |= 0x00000001;
  }

  public static final int FLAVOR_FIELD_NUMBER = 8;
  private java.lang.String flavor_;
  /**
   * <code>optional string flavor = 8;</code>
   * @return Whether the flavor field is set.
   */
  @java.lang.Override
  public boolean hasFlavor() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>optional string flavor = 8;</code>
   * @return The flavor.
   */
  @java.lang.Override
  public java.lang.String getFlavor() {
    return flavor_;
  }
  /**
   * <code>optional string flavor = 8;</code>
   * @return The bytes for flavor.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getFlavorBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(flavor_);
  }
  /**
   * <code>optional string flavor = 8;</code>
   * @param value The flavor to set.
   */
  private void setFlavor(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  bitField0_ |= 0x00000002;
    flavor_ = value;
  }
  /**
   * <code>optional string flavor = 8;</code>
   */
  private void clearFlavor() {
    bitField0_ = (bitField0_ & ~0x00000002);
    flavor_ = getDefaultInstance().getFlavor();
  }
  /**
   * <code>optional string flavor = 8;</code>
   * @param value The bytes for flavor to set.
   */
  private void setFlavorBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    flavor_ = value.toStringUtf8();
    bitField0_ |= 0x00000002;
  }

  public static final int PACKAGINGSTYLE_FIELD_NUMBER = 9;
  private int packagingStyle_;
  /**
   * <code>optional .grocery.database.PackagingStyle packagingStyle = 9;</code>
   * @return Whether the packagingStyle field is set.
   */
  @java.lang.Override
  public boolean hasPackagingStyle() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <code>optional .grocery.database.PackagingStyle packagingStyle = 9;</code>
   * @return The enum numeric value on the wire for packagingStyle.
   */
  @java.lang.Override
  public int getPackagingStyleValue() {
    return packagingStyle_;
  }
  /**
   * <code>optional .grocery.database.PackagingStyle packagingStyle = 9;</code>
   * @return The packagingStyle.
   */
  @java.lang.Override
  public com.example.grocerystoreorganizer.grpc.PackagingStyle getPackagingStyle() {
    com.example.grocerystoreorganizer.grpc.PackagingStyle result = com.example.grocerystoreorganizer.grpc.PackagingStyle.forNumber(packagingStyle_);
    return result == null ? com.example.grocerystoreorganizer.grpc.PackagingStyle.UNRECOGNIZED : result;
  }
  /**
   * <code>optional .grocery.database.PackagingStyle packagingStyle = 9;</code>
   * @param value The enum numeric value on the wire for packagingStyle to set.
   */
  private void setPackagingStyleValue(int value) {
    bitField0_ |= 0x00000004;  packagingStyle_ = value;
  }
  /**
   * <code>optional .grocery.database.PackagingStyle packagingStyle = 9;</code>
   * @param value The packagingStyle to set.
   */
  private void setPackagingStyle(com.example.grocerystoreorganizer.grpc.PackagingStyle value) {
    packagingStyle_ = value.getNumber();
    bitField0_ |= 0x00000004;
  }
  /**
   * <code>optional .grocery.database.PackagingStyle packagingStyle = 9;</code>
   */
  private void clearPackagingStyle() {
    bitField0_ = (bitField0_ & ~0x00000004);
    packagingStyle_ = 0;
  }

  public static com.example.grocerystoreorganizer.grpc.OptimizedVariant parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.example.grocerystoreorganizer.grpc.OptimizedVariant parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.example.grocerystoreorganizer.grpc.OptimizedVariant parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.example.grocerystoreorganizer.grpc.OptimizedVariant parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.example.grocerystoreorganizer.grpc.OptimizedVariant parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.example.grocerystoreorganizer.grpc.OptimizedVariant parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.example.grocerystoreorganizer.grpc.OptimizedVariant parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.example.grocerystoreorganizer.grpc.OptimizedVariant parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.example.grocerystoreorganizer.grpc.OptimizedVariant parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static com.example.grocerystoreorganizer.grpc.OptimizedVariant parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.example.grocerystoreorganizer.grpc.OptimizedVariant parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.example.grocerystoreorganizer.grpc.OptimizedVariant parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(com.example.grocerystoreorganizer.grpc.OptimizedVariant prototype) {
    return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code grocery.database.OptimizedVariant}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.example.grocerystoreorganizer.grpc.OptimizedVariant, Builder> implements
      // @@protoc_insertion_point(builder_implements:grocery.database.OptimizedVariant)
      com.example.grocerystoreorganizer.grpc.OptimizedVariantOrBuilder {
    // Construct using com.example.grocerystoreorganizer.grpc.OptimizedVariant.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>string upc = 1;</code>
     * @return The upc.
     */
    @java.lang.Override
    public java.lang.String getUpc() {
      return instance.getUpc();
    }
    /**
     * <code>string upc = 1;</code>
     * @return The bytes for upc.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getUpcBytes() {
      return instance.getUpcBytes();
    }
    /**
     * <code>string upc = 1;</code>
     * @param value The upc to set.
     * @return This builder for chaining.
     */
    public Builder setUpc(
        java.lang.String value) {
      copyOnWrite();
      instance.setUpc(value);
      return this;
    }
    /**
     * <code>string upc = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearUpc() {
      copyOnWrite();
      instance.clearUpc();
      return this;
    }
    /**
     * <code>string upc = 1;</code>
     * @param value The bytes for upc to set.
     * @return This builder for chaining.
     */
    public Builder setUpcBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setUpcBytes(value);
      return this;
    }

    /**
     * <code>string productName = 2;</code>
     * @return The productName.
     */
    @java.lang.Override
    public java.lang.String getProductName() {
      return instance.getProductName();
    }
    /**
     * <code>string productName = 2;</code>
     * @return The bytes for productName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getProductNameBytes() {
      return instance.getProductNameBytes();
    }
    /**
     * <code>string productName = 2;</code>
     * @param value The productName to set.
     * @return This builder for chaining.
     */
    public Builder setProductName(
        java.lang.String value) {
      copyOnWrite();
      instance.setProductName(value);
      return this;
    }
    /**
     * <code>string productName = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearProductName() {
      copyOnWrite();
      instance.clearProductName();
      return this;
    }
    /**
     * <code>string productName = 2;</code>
     * @param value The bytes for productName to set.
     * @return This builder for chaining.
     */
    public Builder setProductNameBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setProductNameBytes(value);
      return this;
    }

    /**
     * <code>string variantLabel = 3;</code>
     * @return The variantLabel.
     */
    @java.lang.Override
    public java.lang.String getVariantLabel() {
      return instance.getVariantLabel();
    }
    /**
     * <code>string variantLabel = 3;</code>
     * @return The bytes for variantLabel.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getVariantLabelBytes() {
      return instance.getVariantLabelBytes();
    }
    /**
     * <code>string variantLabel = 3;</code>
     * @param value The variantLabel to set.
     * @return This builder for chaining.
     */
    public Builder setVariantLabel(
        java.lang.String value) {
      copyOnWrite();
      instance.setVariantLabel(value);
      return this;
    }
    /**
     * <code>string variantLabel = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearVariantLabel() {
      copyOnWrite();
      instance.clearVariantLabel();
      return this;
    }
    /**
     * <code>string variantLabel = 3;</code>
     * @param value The bytes for variantLabel to set.
     * @return This builder for chaining.
     */
    public Builder setVariantLabelBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setVariantLabelBytes(value);
      return this;
    }

    /**
     * <code>int32 packCount = 4;</code>
     * @return The packCount.
     */
    @java.lang.Override
    public int getPackCount() {
      return instance.getPackCount();
    }
    /**
     * <code>int32 packCount = 4;</code>
     * @param value The packCount to set.
     * @return This builder for chaining.
     */
    public Builder setPackCount(int value) {
      copyOnWrite();
      instance.setPackCount(value);
      return this;
    }
    /**
     * <code>int32 packCount = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearPackCount() {
      copyOnWrite();
      instance.clearPackCount();
      return this;
    }

    /**
     * <code>double netQuantity = 5;</code>
     * @return The netQuantity.
     */
    @java.lang.Override
    public double getNetQuantity() {
      return instance.getNetQuantity();
    }
    /**
     * <code>double netQuantity = 5;</code>
     * @param value The netQuantity to set.
     * @return This builder for chaining.
     */
    public Builder setNetQuantity(double value) {
      copyOnWrite();
      instance.setNetQuantity(value);
      return this;
    }
    /**
     * <code>double netQuantity = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearNetQuantity() {
      copyOnWrite();
      instance.clearNetQuantity();
      return this;
    }

    /**
     * <code>.grocery.database.ProductUnit quantityUnit = 6;</code>
     * @return The enum numeric value on the wire for quantityUnit.
     */
    @java.lang.Override
    public int getQuantityUnitValue() {
      return instance.getQuantityUnitValue();
    }
    /**
     * <code>.grocery.database.ProductUnit quantityUnit = 6;</code>
     * @param value The quantityUnit to set.
     * @return This builder for chaining.
     */
    public Builder setQuantityUnitValue(int value) {
      copyOnWrite();
      instance.setQuantityUnitValue(value);
      return this;
    }
    /**
     * <code>.grocery.database.ProductUnit quantityUnit = 6;</code>
     * @return The quantityUnit.
     */
    @java.lang.Override
    public com.example.grocerystoreorganizer.grpc.ProductUnit getQuantityUnit() {
      return instance.getQuantityUnit();
    }
    /**
     * <code>.grocery.database.ProductUnit quantityUnit = 6;</code>
     * @param value The enum numeric value on the wire for quantityUnit to set.
     * @return This builder for chaining.
     */
    public Builder setQuantityUnit(com.example.grocerystoreorganizer.grpc.ProductUnit value) {
      copyOnWrite();
      instance.setQuantityUnit(value);
      return this;
    }
    /**
     * <code>.grocery.database.ProductUnit quantityUnit = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearQuantityUnit() {
      copyOnWrite();
      instance.clearQuantityUnit();
      return this;
    }

    /**
     * <code>optional string brand = 7;</code>
     * @return Whether the brand field is set.
     */
    @java.lang.Override
    public boolean hasBrand() {
      return instance.hasBrand();
    }
    /**
     * <code>optional string brand = 7;</code>
     * @return The brand.
     */
    @java.lang.Override
    public java.lang.String getBrand() {
      return instance.getBrand();
    }
    /**
     * <code>optional string brand = 7;</code>
     * @return The bytes for brand.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getBrandBytes() {
      return instance.getBrandBytes();
    }
    /**
     * <code>optional string brand = 7;</code>
     * @param value The brand to set.
     * @return This builder for chaining.
     */
    public Builder setBrand(
        java.lang.String value) {
      copyOnWrite();
      instance.setBrand(value);
      return this;
    }
    /**
     * <code>optional string brand = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearBrand() {
      copyOnWrite();
      instance.clearBrand();
      return this;
    }
    /**
     * <code>optional string brand = 7;</code>
     * @param value The bytes for brand to set.
     * @return This builder for chaining.
     */
    public Builder setBrandBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setBrandBytes(value);
      return this;
    }

    /**
     * <code>optional string flavor = 8;</code>
     * @return Whether the flavor field is set.
     */
    @java.lang.Override
    public boolean hasFlavor() {
      return instance.hasFlavor();
    }
    /**
     * <code>optional string flavor = 8;</code>
     * @return The flavor.
     */
    @java.lang.Override
    public java.lang.String getFlavor() {
      return instance.getFlavor();
    }
    /**
     * <code>optional string flavor = 8;</code>
     * @return The bytes for flavor.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getFlavorBytes() {
      return instance.getFlavorBytes();
    }
    /**
     * <code>optional string flavor = 8;</code>
     * @param value The flavor to set.
     * @return This builder for chaining.
     */
    public Builder setFlavor(
        java.lang.String value) {
      copyOnWrite();
      instance.setFlavor(value);
      return this;
    }
    /**
     * <code>optional string flavor = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearFlavor() {
      copyOnWrite();
      instance.clearFlavor();
      return this;
    }
    /**
     * <code>optional string flavor = 8;</code>
     * @param value The bytes for flavor to set.
     * @return This builder for chaining.
     */
    public Builder setFlavorBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setFlavorBytes(value);
      return this;
    }

    /**
     * <code>optional .grocery.database.PackagingStyle packagingStyle = 9;</code>
     * @return Whether the packagingStyle field is set.
     */
    @java.lang.Override
    public boolean hasPackagingStyle() {
      return instance.hasPackagingStyle();
    }
    /**
     * <code>optional .grocery.database.PackagingStyle packagingStyle = 9;</code>
     * @return The enum numeric value on the wire for packagingStyle.
     */
    @java.lang.Override
    public int getPackagingStyleValue() {
      return instance.getPackagingStyleValue();
    }
    /**
     * <code>optional .grocery.database.PackagingStyle packagingStyle = 9;</code>
     * @param value The packagingStyle to set.
     * @return This builder for chaining.
     */
    public Builder setPackagingStyleValue(int value) {
      copyOnWrite();
      instance.setPackagingStyleValue(value);
      return this;
    }
    /**
     * <code>optional .grocery.database.PackagingStyle packagingStyle = 9;</code>
     * @return The packagingStyle.
     */
    @java.lang.Override
    public com.example.grocerystoreorganizer.grpc.PackagingStyle getPackagingStyle() {
      return instance.getPackagingStyle();
    }
    /**
     * <code>optional .grocery.database.PackagingStyle packagingStyle = 9;</code>
     * @param value The enum numeric value on the wire for packagingStyle to set.
     * @return This builder for chaining.
     */
    public Builder setPackagingStyle(com.example.grocerystoreorganizer.grpc.PackagingStyle value) {
      copyOnWrite();
      instance.setPackagingStyle(value);
      return this;
    }
    /**
     * <code>optional .grocery.database.PackagingStyle packagingStyle = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearPackagingStyle() {
      copyOnWrite();
      instance.clearPackagingStyle();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:grocery.database.OptimizedVariant)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.example.grocerystoreorganizer.grpc.OptimizedVariant();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "bitField0_",
            "upc_",
            "productName_",
            "variantLabel_",
            "packCount_",
            "netQuantity_",
            "quantityUnit_",
            "brand_",
            "flavor_",
            "packagingStyle_",
          };
          java.lang.String info =
              "\u0000\t\u0000\u0001\u0001\t\t\u0000\u0000\u0000\u0001\u0208\u0002\u0208\u0003\u0208" +
              "\u0004\u0004\u0005\u0000\u0006\f\u0007\u1208\u0000\b\u1208\u0001\t\u100c\u0002";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<com.example.grocerystoreorganizer.grpc.OptimizedVariant> parser = PARSER;
        if (parser == null) {
          synchronized (com.example.grocerystoreorganizer.grpc.OptimizedVariant.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<com.example.grocerystoreorganizer.grpc.OptimizedVariant>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:grocery.database.OptimizedVariant)
  private static final com.example.grocerystoreorganizer.grpc.OptimizedVariant DEFAULT_INSTANCE;
  static {
    OptimizedVariant defaultInstance = new OptimizedVariant();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      OptimizedVariant.class, defaultInstance);
  }

  public static com.example.grocerystoreorganizer.grpc.OptimizedVariant getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<OptimizedVariant> PARSER;

  public static com.google.protobuf.Parser<OptimizedVariant> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

