// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: db_service.proto

package com.example.grocerystoreorganizer.grpc;

public interface OptimizedItemMatchOrBuilder extends
    // @@protoc_insertion_point(interface_extends:grocery.database.OptimizedItemMatch)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>int32 itemId = 1;</code>
   * @return The itemId.
   */
  int getItemId();

  /**
   * <code>.grocery.database.ComparisonMode comparisonMode = 2;</code>
   * @return The enum numeric value on the wire for comparisonMode.
   */
  int getComparisonModeValue();
  /**
   * <code>.grocery.database.ComparisonMode comparisonMode = 2;</code>
   * @return The comparisonMode.
   */
  com.example.grocerystoreorganizer.grpc.ComparisonMode getComparisonMode();

  /**
   * <code>int32 desiredCount = 3;</code>
   * @return The desiredCount.
   */
  int getDesiredCount();

  /**
   * <code>.grocery.database.OptimizedStore store = 4;</code>
   * @return Whether the store field is set.
   */
  boolean hasStore();
  /**
   * <code>.grocery.database.OptimizedStore store = 4;</code>
   * @return The store.
   */
  com.example.grocerystoreorganizer.grpc.OptimizedStore getStore();

  /**
   * <code>.grocery.database.OptimizedVariant variant = 5;</code>
   * @return Whether the variant field is set.
   */
  boolean hasVariant();
  /**
   * <code>.grocery.database.OptimizedVariant variant = 5;</code>
   * @return The variant.
   */
  com.example.grocerystoreorganizer.grpc.OptimizedVariant getVariant();

  /**
   * <code>uint32 priceObservationId = 6;</code>
   * @return The priceObservationId.
   */
  int getPriceObservationId();

  /**
   * <code>double observedPriceTotal = 7;</code>
   * @return The observedPriceTotal.
   */
  double getObservedPriceTotal();

  /**
   * <code>string observedAt = 8;</code>
   * @return The observedAt.
   */
  java.lang.String getObservedAt();
  /**
   * <code>string observedAt = 8;</code>
   * @return The bytes for observedAt.
   */
  com.google.protobuf.ByteString
      getObservedAtBytes();

  /**
   * <code>double estimatedTotalPrice = 9;</code>
   * @return The estimatedTotalPrice.
   */
  double getEstimatedTotalPrice();
}
