// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: db_service.proto

package com.example.grocerystoreorganizer.grpc;

public interface OptimizedVariantOrBuilder extends
    // @@protoc_insertion_point(interface_extends:grocery.database.OptimizedVariant)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>string upc = 1;</code>
   * @return The upc.
   */
  java.lang.String getUpc();
  /**
   * <code>string upc = 1;</code>
   * @return The bytes for upc.
   */
  com.google.protobuf.ByteString
      getUpcBytes();

  /**
   * <code>string productName = 2;</code>
   * @return The productName.
   */
  java.lang.String getProductName();
  /**
   * <code>string productName = 2;</code>
   * @return The bytes for productName.
   */
  com.google.protobuf.ByteString
      getProductNameBytes();

  /**
   * <code>string variantLabel = 3;</code>
   * @return The variantLabel.
   */
  java.lang.String getVariantLabel();
  /**
   * <code>string variantLabel = 3;</code>
   * @return The bytes for variantLabel.
   */
  com.google.protobuf.ByteString
      getVariantLabelBytes();

  /**
   * <code>int32 packCount = 4;</code>
   * @return The packCount.
   */
  int getPackCount();

  /**
   * <code>double netQuantity = 5;</code>
   * @return The netQuantity.
   */
  double getNetQuantity();

  /**
   * <code>.grocery.database.ProductUnit quantityUnit = 6;</code>
   * @return The enum numeric value on the wire for quantityUnit.
   */
  int getQuantityUnitValue();
  /**
   * <code>.grocery.database.ProductUnit quantityUnit = 6;</code>
   * @return The quantityUnit.
   */
  com.example.grocerystoreorganizer.grpc.ProductUnit getQuantityUnit();

  /**
   * <code>optional string brand = 7;</code>
   * @return Whether the brand field is set.
   */
  boolean hasBrand();
  /**
   * <code>optional string brand = 7;</code>
   * @return The brand.
   */
  java.lang.String getBrand();
  /**
   * <code>optional string brand = 7;</code>
   * @return The bytes for brand.
   */
  com.google.protobuf.ByteString
      getBrandBytes();

  /**
   * <code>optional string flavor = 8;</code>
   * @return Whether the flavor field is set.
   */
  boolean hasFlavor();
  /**
   * <code>optional string flavor = 8;</code>
   * @return The flavor.
   */
  java.lang.String getFlavor();
  /**
   * <code>optional string flavor = 8;</code>
   * @return The bytes for flavor.
   */
  com.google.protobuf.ByteString
      getFlavorBytes();

  /**
   * <code>optional .grocery.database.PackagingStyle packagingStyle = 9;</code>
   * @return Whether the packagingStyle field is set.
   */
  boolean hasPackagingStyle();
  /**
   * <code>optional .grocery.database.PackagingStyle packagingStyle = 9;</code>
   * @return The enum numeric value on the wire for packagingStyle.
   */
  int getPackagingStyleValue();
  /**
   * <code>optional .grocery.database.PackagingStyle packagingStyle = 9;</code>
   * @return The packagingStyle.
   */
  com.example.grocerystoreorganizer.grpc.PackagingStyle getPackagingStyle();
}
