// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: db_service.proto

package com.example.grocerystoreorganizer.grpc;

/**
 * Protobuf type {@code grocery.database.OptimizeGroceryListResponse}
 */
public  final class OptimizeGroceryListResponse extends
    com.google.protobuf.GeneratedMessageLite<
        OptimizeGroceryListResponse, OptimizeGroceryListResponse.Builder> implements
    // @@protoc_insertion_point(message_implements:grocery.database.OptimizeGroceryListResponse)
    OptimizeGroceryListResponseOrBuilder {
  private OptimizeGroceryListResponse() {
    matches_ = emptyProtobufList();
    unmatched_ = emptyProtobufList();
  }
  public static final int MATCHES_FIELD_NUMBER = 1;
  private com.google.protobuf.Internal.ProtobufList<com.example.grocerystoreorganizer.grpc.OptimizedItemMatch> matches_;
  /**
   * <code>repeated .grocery.database.OptimizedItemMatch matches = 1;</code>
   */
  @java.lang.Override
  public java.util.List<com.example.grocerystoreorganizer.grpc.OptimizedItemMatch> getMatchesList() {
    return matches_;
  }
  /**
   * <code>repeated .grocery.database.OptimizedItemMatch matches = 1;</code>
   */
  public java.util.List<? extends com.example.grocerystoreorganizer.grpc.OptimizedItemMatchOrBuilder> 
      getMatchesOrBuilderList() {
    return matches_;
  }
  /**
   * <code>repeated .grocery.database.OptimizedItemMatch matches = 1;</code>
   */
  @java.lang.Override
  public int getMatchesCount() {
    return matches_.size();
  }
  /**
   * <code>repeated .grocery.database.OptimizedItemMatch matches = 1;</code>
   */
  @java.lang.Override
  public com.example.grocerystoreorganizer.grpc.OptimizedItemMatch getMatches(int index) {
    return matches_.get(index);
  }
  /**
   * <code>repeated .grocery.database.OptimizedItemMatch matches = 1;</code>
   */
  public com.example.grocerystoreorganizer.grpc.OptimizedItemMatchOrBuilder getMatchesOrBuilder(
      int index) {
    return matches_.get(index);
  }
  private void ensureMatchesIsMutable() {
    com.google.protobuf.Internal.ProtobufList<com.example.grocerystoreorganizer.grpc.OptimizedItemMatch> tmp = matches_;
    if (!tmp.isModifiable()) {
      matches_ =
          com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
     }
  }

  /**
   * <code>repeated .grocery.database.OptimizedItemMatch matches = 1;</code>
   */
  private void setMatches(
      int index, com.example.grocerystoreorganizer.grpc.OptimizedItemMatch value) {
    value.getClass();
  ensureMatchesIsMutable();
    matches_.set(index, value);
  }
  /**
   * <code>repeated .grocery.database.OptimizedItemMatch matches = 1;</code>
   */
  private void addMatches(com.example.grocerystoreorganizer.grpc.OptimizedItemMatch value) {
    value.getClass();
  ensureMatchesIsMutable();
    matches_.add(value);
  }
  /**
   * <code>repeated .grocery.database.OptimizedItemMatch matches = 1;</code>
   */
  private void addMatches(
      int index, com.example.grocerystoreorganizer.grpc.OptimizedItemMatch value) {
    value.getClass();
  ensureMatchesIsMutable();
    matches_.add(index, value);
  }
  /**
   * <code>repeated .grocery.database.OptimizedItemMatch matches = 1;</code>
   */
  private void addAllMatches(
      java.lang.Iterable<? extends com.example.grocerystoreorganizer.grpc.OptimizedItemMatch> values) {
    ensureMatchesIsMutable();
    com.google.protobuf.AbstractMessageLite.addAll(
        values, matches_);
  }
  /**
   * <code>repeated .grocery.database.OptimizedItemMatch matches = 1;</code>
   */
  private void clearMatches() {
    matches_ = emptyProtobufList();
  }
  /**
   * <code>repeated .grocery.database.OptimizedItemMatch matches = 1;</code>
   */
  private void removeMatches(int index) {
    ensureMatchesIsMutable();
    matches_.remove(index);
  }

  public static final int UNMATCHED_FIELD_NUMBER = 2;
  private com.google.protobuf.Internal.ProtobufList<com.example.grocerystoreorganizer.grpc.UnmatchedOptimizationItem> unmatched_;
  /**
   * <code>repeated .grocery.database.UnmatchedOptimizationItem unmatched = 2;</code>
   */
  @java.lang.Override
  public java.util.List<com.example.grocerystoreorganizer.grpc.UnmatchedOptimizationItem> getUnmatchedList() {
    return unmatched_;
  }
  /**
   * <code>repeated .grocery.database.UnmatchedOptimizationItem unmatched = 2;</code>
   */
  public java.util.List<? extends com.example.grocerystoreorganizer.grpc.UnmatchedOptimizationItemOrBuilder> 
      getUnmatchedOrBuilderList() {
    return unmatched_;
  }
  /**
   * <code>repeated .grocery.database.UnmatchedOptimizationItem unmatched = 2;</code>
   */
  @java.lang.Override
  public int getUnmatchedCount() {
    return unmatched_.size();
  }
  /**
   * <code>repeated .grocery.database.UnmatchedOptimizationItem unmatched = 2;</code>
   */
  @java.lang.Override
  public com.example.grocerystoreorganizer.grpc.UnmatchedOptimizationItem getUnmatched(int index) {
    return unmatched_.get(index);
  }
  /**
   * <code>repeated .grocery.database.UnmatchedOptimizationItem unmatched = 2;</code>
   */
  public com.example.grocerystoreorganizer.grpc.UnmatchedOptimizationItemOrBuilder getUnmatchedOrBuilder(
      int index) {
    return unmatched_.get(index);
  }
  private void ensureUnmatchedIsMutable() {
    com.google.protobuf.Internal.ProtobufList<com.example.grocerystoreorganizer.grpc.UnmatchedOptimizationItem> tmp = unmatched_;
    if (!tmp.isModifiable()) {
      unmatched_ =
          com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
     }
  }

  /**
   * <code>repeated .grocery.database.UnmatchedOptimizationItem unmatched = 2;</code>
   */
  private void setUnmatched(
      int index, com.example.grocerystoreorganizer.grpc.UnmatchedOptimizationItem value) {
    value.getClass();
  ensureUnmatchedIsMutable();
    unmatched_.set(index, value);
  }
  /**
   * <code>repeated .grocery.database.UnmatchedOptimizationItem unmatched = 2;</code>
   */
  private void addUnmatched(com.example.grocerystoreorganizer.grpc.UnmatchedOptimizationItem value) {
    value.getClass();
  ensureUnmatchedIsMutable();
    unmatched_.add(value);
  }
  /**
   * <code>repeated .grocery.database.UnmatchedOptimizationItem unmatched = 2;</code>
   */
  private void addUnmatched(
      int index, com.example.grocerystoreorganizer.grpc.UnmatchedOptimizationItem value) {
    value.getClass();
  ensureUnmatchedIsMutable();
    unmatched_.add(index, value);
  }
  /**
   * <code>repeated .grocery.database.UnmatchedOptimizationItem unmatched = 2;</code>
   */
  private void addAllUnmatched(
      java.lang.Iterable<? extends com.example.grocerystoreorganizer.grpc.UnmatchedOptimizationItem> values) {
    ensureUnmatchedIsMutable();
    com.google.protobuf.AbstractMessageLite.addAll(
        values, unmatched_);
  }
  /**
   * <code>repeated .grocery.database.UnmatchedOptimizationItem unmatched = 2;</code>
   */
  private void clearUnmatched() {
    unmatched_ = emptyProtobufList();
  }
  /**
   * <code>repeated .grocery.database.UnmatchedOptimizationItem unmatched = 2;</code>
   */
  private void removeUnmatched(int index) {
    ensureUnmatchedIsMutable();
    unmatched_.remove(index);
  }

  public static com.example.grocerystoreorganizer.grpc.OptimizeGroceryListResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.example.grocerystoreorganizer.grpc.OptimizeGroceryListResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.example.grocerystoreorganizer.grpc.OptimizeGroceryListResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.example.grocerystoreorganizer.grpc.OptimizeGroceryListResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.example.grocerystoreorganizer.grpc.OptimizeGroceryListResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.example.grocerystoreorganizer.grpc.OptimizeGroceryListResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.example.grocerystoreorganizer.grpc.OptimizeGroceryListResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.example.grocerystoreorganizer.grpc.OptimizeGroceryListResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.example.grocerystoreorganizer.grpc.OptimizeGroceryListResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static com.example.grocerystoreorganizer.grpc.OptimizeGroceryListResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.example.grocerystoreorganizer.grpc.OptimizeGroceryListResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.example.grocerystoreorganizer.grpc.OptimizeGroceryListResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(com.example.grocerystoreorganizer.grpc.OptimizeGroceryListResponse prototype) {
    return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code grocery.database.OptimizeGroceryListResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.example.grocerystoreorganizer.grpc.OptimizeGroceryListResponse, Builder> implements
      // @@protoc_insertion_point(builder_implements:grocery.database.OptimizeGroceryListResponse)
      com.example.grocerystoreorganizer.grpc.OptimizeGroceryListResponseOrBuilder {
    // Construct using com.example.grocerystoreorganizer.grpc.OptimizeGroceryListResponse.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>repeated .grocery.database.OptimizedItemMatch matches = 1;</code>
     */
    @java.lang.Override
    public java.util.List<com.example.grocerystoreorganizer.grpc.OptimizedItemMatch> getMatchesList() {
      return java.util.Collections.unmodifiableList(
          instance.getMatchesList());
    }
    /**
     * <code>repeated .grocery.database.OptimizedItemMatch matches = 1;</code>
     */
    @java.lang.Override
    public int getMatchesCount() {
      return instance.getMatchesCount();
    }/**
     * <code>repeated .grocery.database.OptimizedItemMatch matches = 1;</code>
     */
    @java.lang.Override
    public com.example.grocerystoreorganizer.grpc.OptimizedItemMatch getMatches(int index) {
      return instance.getMatches(index);
    }
    /**
     * <code>repeated .grocery.database.OptimizedItemMatch matches = 1;</code>
     */
    public Builder setMatches(
        int index, com.example.grocerystoreorganizer.grpc.OptimizedItemMatch value) {
      copyOnWrite();
      instance.setMatches(index, value);
      return this;
    }
    /**
     * <code>repeated .grocery.database.OptimizedItemMatch matches = 1;</code>
     */
    public Builder setMatches(
        int index, com.example.grocerystoreorganizer.grpc.OptimizedItemMatch.Builder builderForValue) {
      copyOnWrite();
      instance.setMatches(index,
          builderForValue.build());
      return this;
    }
    /**
     * <code>repeated .grocery.database.OptimizedItemMatch matches = 1;</code>
     */
    public Builder addMatches(com.example.grocerystoreorganizer.grpc.OptimizedItemMatch value) {
      copyOnWrite();
      instance.addMatches(value);
      return this;
    }
    /**
     * <code>repeated .grocery.database.OptimizedItemMatch matches = 1;</code>
     */
    public Builder addMatches(
        int index, com.example.grocerystoreorganizer.grpc.OptimizedItemMatch value) {
      copyOnWrite();
      instance.addMatches(index, value);
      return this;
    }
    /**
     * <code>repeated .grocery.database.OptimizedItemMatch matches = 1;</code>
     */
    public Builder addMatches(
        com.example.grocerystoreorganizer.grpc.OptimizedItemMatch.Builder builderForValue) {
      copyOnWrite();
      instance.addMatches(builderForValue.build());
      return this;
    }
    /**
     * <code>repeated .grocery.database.OptimizedItemMatch matches = 1;</code>
     */
    public Builder addMatches(
        int index, com.example.grocerystoreorganizer.grpc.OptimizedItemMatch.Builder builderForValue) {
      copyOnWrite();
      instance.addMatches(index,
          builderForValue.build());
      return this;
    }
    /**
     * <code>repeated .grocery.database.OptimizedItemMatch matches = 1;</code>
     */
    public Builder addAllMatches(
        java.lang.Iterable<? extends com.example.grocerystoreorganizer.grpc.OptimizedItemMatch> values) {
      copyOnWrite();
      instance.addAllMatches(values);
      return this;
    }
    /**
     * <code>repeated .grocery.database.OptimizedItemMatch matches = 1;</code>
     */
    public Builder clearMatches() {
      copyOnWrite();
      instance.clearMatches();
      return this;
    }
    /**
     * <code>repeated .grocery.database.OptimizedItemMatch matches = 1;</code>
     */
    public Builder removeMatches(int index) {
      copyOnWrite();
      instance.removeMatches(index);
      return this;
    }

    /**
     * <code>repeated .grocery.database.UnmatchedOptimizationItem unmatched = 2;</code>
     */
    @java.lang.Override
    public java.util.List<com.example.grocerystoreorganizer.grpc.UnmatchedOptimizationItem> getUnmatchedList() {
      return java.util.Collections.unmodifiableList(
          instance.getUnmatchedList());
    }
    /**
     * <code>repeated .grocery.database.UnmatchedOptimizationItem unmatched = 2;</code>
     */
    @java.lang.Override
    public int getUnmatchedCount() {
      return instance.getUnmatchedCount();
    }/**
     * <code>repeated .grocery.database.UnmatchedOptimizationItem unmatched = 2;</code>
     */
    @java.lang.Override
    public com.example.grocerystoreorganizer.grpc.UnmatchedOptimizationItem getUnmatched(int index) {
      return instance.getUnmatched(index);
    }
    /**
     * <code>repeated .grocery.database.UnmatchedOptimizationItem unmatched = 2;</code>
     */
    public Builder setUnmatched(
        int index, com.example.grocerystoreorganizer.grpc.UnmatchedOptimizationItem value) {
      copyOnWrite();
      instance.setUnmatched(index, value);
      return this;
    }
    /**
     * <code>repeated .grocery.database.UnmatchedOptimizationItem unmatched = 2;</code>
     */
    public Builder setUnmatched(
        int index, com.example.grocerystoreorganizer.grpc.UnmatchedOptimizationItem.Builder builderForValue) {
      copyOnWrite();
      instance.setUnmatched(index,
          builderForValue.build());
      return this;
    }
    /**
     * <code>repeated .grocery.database.UnmatchedOptimizationItem unmatched = 2;</code>
     */
    public Builder addUnmatched(com.example.grocerystoreorganizer.grpc.UnmatchedOptimizationItem value) {
      copyOnWrite();
      instance.addUnmatched(value);
      return this;
    }
    /**
     * <code>repeated .grocery.database.UnmatchedOptimizationItem unmatched = 2;</code>
     */
    public Builder addUnmatched(
        int index, com.example.grocerystoreorganizer.grpc.UnmatchedOptimizationItem value) {
      copyOnWrite();
      instance.addUnmatched(index, value);
      return this;
    }
    /**
     * <code>repeated .grocery.database.UnmatchedOptimizationItem unmatched = 2;</code>
     */
    public Builder addUnmatched(
        com.example.grocerystoreorganizer.grpc.UnmatchedOptimizationItem.Builder builderForValue) {
      copyOnWrite();
      instance.addUnmatched(builderForValue.build());
      return this;
    }
    /**
     * <code>repeated .grocery.database.UnmatchedOptimizationItem unmatched = 2;</code>
     */
    public Builder addUnmatched(
        int index, com.example.grocerystoreorganizer.grpc.UnmatchedOptimizationItem.Builder builderForValue) {
      copyOnWrite();
      instance.addUnmatched(index,
          builderForValue.build());
      return this;
    }
    /**
     * <code>repeated .grocery.database.UnmatchedOptimizationItem unmatched = 2;</code>
     */
    public Builder addAllUnmatched(
        java.lang.Iterable<? extends com.example.grocerystoreorganizer.grpc.UnmatchedOptimizationItem> values) {
      copyOnWrite();
      instance.addAllUnmatched(values);
      return this;
    }
    /**
     * <code>repeated .grocery.database.UnmatchedOptimizationItem unmatched = 2;</code>
     */
    public Builder clearUnmatched() {
      copyOnWrite();
      instance.clearUnmatched();
      return this;
    }
    /**
     * <code>repeated .grocery.database.UnmatchedOptimizationItem unmatched = 2;</code>
     */
    public Builder removeUnmatched(int index) {
      copyOnWrite();
      instance.removeUnmatched(index);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:grocery.database.OptimizeGroceryListResponse)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.example.grocerystoreorganizer.grpc.OptimizeGroceryListResponse();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "matches_",
            com.example.grocerystoreorganizer.grpc.OptimizedItemMatch.class,
            "unmatched_",
            com.example.grocerystoreorganizer.grpc.UnmatchedOptimizationItem.class,
          };
          java.lang.String info =
              "\u0000\u0002\u0000\u0000\u0001\u0002\u0002\u0000\u0002\u0000\u0001\u001b\u0002\u001b" +
              "";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<com.example.grocerystoreorganizer.grpc.OptimizeGroceryListResponse> parser = PARSER;
        if (parser == null) {
          synchronized (com.example.grocerystoreorganizer.grpc.OptimizeGroceryListResponse.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<com.example.grocerystoreorganizer.grpc.OptimizeGroceryListResponse>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:grocery.database.OptimizeGroceryListResponse)
  private static final com.example.grocerystoreorganizer.grpc.OptimizeGroceryListResponse DEFAULT_INSTANCE;
  static {
    OptimizeGroceryListResponse defaultInstance = new OptimizeGroceryListResponse();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      OptimizeGroceryListResponse.class, defaultInstance);
  }

  public static com.example.grocerystoreorganizer.grpc.OptimizeGroceryListResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<OptimizeGroceryListResponse> PARSER;

  public static com.google.protobuf.Parser<OptimizeGroceryListResponse> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

