// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: db_service.proto

package com.example.grocerystoreorganizer.grpc;

/**
 * Protobuf enum {@code grocery.database.PackagingStyle}
 */
public enum PackagingStyle
    implements com.google.protobuf.Internal.EnumLite {
  /**
   * <code>PACKAGING_UNSPECIFIED = 0;</code>
   */
  PACKAGING_UNSPECIFIED(0),
  /**
   * <code>LOOSE = 1;</code>
   */
  LOOSE(1),
  /**
   * <code>CAN = 2;</code>
   */
  CAN(2),
  /**
   * <code>BOTTLE = 3;</code>
   */
  BOTTLE(3),
  /**
   * <code>BOX = 4;</code>
   */
  BOX(4),
  /**
   * <code>BAG = 5;</code>
   */
  BAG(5),
  /**
   * <code>CARTON = 6;</code>
   */
  CARTON(6),
  /**
   * <code>BUNCH = 7;</code>
   */
  BUNCH(7),
  /**
   * <code>OTHER = 8;</code>
   */
  OTHER(8),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>PACKAGING_UNSPECIFIED = 0;</code>
   */
  public static final int PACKAGING_UNSPECIFIED_VALUE = 0;
  /**
   * <code>LOOSE = 1;</code>
   */
  public static final int LOOSE_VALUE = 1;
  /**
   * <code>CAN = 2;</code>
   */
  public static final int CAN_VALUE = 2;
  /**
   * <code>BOTTLE = 3;</code>
   */
  public static final int BOTTLE_VALUE = 3;
  /**
   * <code>BOX = 4;</code>
   */
  public static final int BOX_VALUE = 4;
  /**
   * <code>BAG = 5;</code>
   */
  public static final int BAG_VALUE = 5;
  /**
   * <code>CARTON = 6;</code>
   */
  public static final int CARTON_VALUE = 6;
  /**
   * <code>BUNCH = 7;</code>
   */
  public static final int BUNCH_VALUE = 7;
  /**
   * <code>OTHER = 8;</code>
   */
  public static final int OTHER_VALUE = 8;


  @java.lang.Override
  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The number of the enum to look for.
   * @return The enum associated with the given number.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static PackagingStyle valueOf(int value) {
    return forNumber(value);
  }

  public static PackagingStyle forNumber(int value) {
    switch (value) {
      case 0: return PACKAGING_UNSPECIFIED;
      case 1: return LOOSE;
      case 2: return CAN;
      case 3: return BOTTLE;
      case 4: return BOX;
      case 5: return BAG;
      case 6: return CARTON;
      case 7: return BUNCH;
      case 8: return OTHER;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<PackagingStyle>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      PackagingStyle> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<PackagingStyle>() {
          @java.lang.Override
          public PackagingStyle findValueByNumber(int number) {
            return PackagingStyle.forNumber(number);
          }
        };

  public static com.google.protobuf.Internal.EnumVerifier 
      internalGetVerifier() {
    return PackagingStyleVerifier.INSTANCE;
  }

  private static final class PackagingStyleVerifier implements 
       com.google.protobuf.Internal.EnumVerifier { 
          static final com.google.protobuf.Internal.EnumVerifier           INSTANCE = new PackagingStyleVerifier();
          @java.lang.Override
          public boolean isInRange(int number) {
            return PackagingStyle.forNumber(number) != null;
          }
        };

  private final int value;

  private PackagingStyle(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:grocery.database.PackagingStyle)
}

