// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: db_service.proto

package com.example.grocerystoreorganizer.grpc;

public interface ParsePriceTagImageRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:grocery.database.ParsePriceTagImageRequest)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>bytes imageJpeg = 1;</code>
   * @return The imageJpeg.
   */
  com.google.protobuf.ByteString getImageJpeg();

  /**
   * <code>optional string imageFilename = 2;</code>
   * @return Whether the imageFilename field is set.
   */
  boolean hasImageFilename();
  /**
   * <code>optional string imageFilename = 2;</code>
   * @return The imageFilename.
   */
  java.lang.String getImageFilename();
  /**
   * <code>optional string imageFilename = 2;</code>
   * @return The bytes for imageFilename.
   */
  com.google.protobuf.ByteString
      getImageFilenameBytes();
}
