// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: db_service.proto

package com.example.grocerystoreorganizer.grpc;

public interface ParsePriceTagImageResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:grocery.database.ParsePriceTagImageResponse)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>bool ambiguous = 1;</code>
   * @return The ambiguous.
   */
  boolean getAmbiguous();

  /**
   * <code>bool unparsable = 2;</code>
   * @return The unparsable.
   */
  boolean getUnparsable();

  /**
   * <code>bool upcParsable = 3;</code>
   * @return The upcParsable.
   */
  boolean getUpcParsable();

  /**
   * <code>optional string upc = 4;</code>
   * @return Whether the upc field is set.
   */
  boolean hasUpc();
  /**
   * <code>optional string upc = 4;</code>
   * @return The upc.
   */
  java.lang.String getUpc();
  /**
   * <code>optional string upc = 4;</code>
   * @return The bytes for upc.
   */
  com.google.protobuf.ByteString
      getUpcBytes();

  /**
   * <code>optional double priceTotal = 5;</code>
   * @return Whether the priceTotal field is set.
   */
  boolean hasPriceTotal();
  /**
   * <code>optional double priceTotal = 5;</code>
   * @return The priceTotal.
   */
  double getPriceTotal();

  /**
   * <code>optional int32 packCount = 6;</code>
   * @return Whether the packCount field is set.
   */
  boolean hasPackCount();
  /**
   * <code>optional int32 packCount = 6;</code>
   * @return The packCount.
   */
  int getPackCount();

  /**
   * <code>optional double netQuantity = 7;</code>
   * @return Whether the netQuantity field is set.
   */
  boolean hasNetQuantity();
  /**
   * <code>optional double netQuantity = 7;</code>
   * @return The netQuantity.
   */
  double getNetQuantity();

  /**
   * <code>optional .grocery.database.ProductUnit quantityUnit = 8;</code>
   * @return Whether the quantityUnit field is set.
   */
  boolean hasQuantityUnit();
  /**
   * <code>optional .grocery.database.ProductUnit quantityUnit = 8;</code>
   * @return The enum numeric value on the wire for quantityUnit.
   */
  int getQuantityUnitValue();
  /**
   * <code>optional .grocery.database.ProductUnit quantityUnit = 8;</code>
   * @return The quantityUnit.
   */
  com.example.grocerystoreorganizer.grpc.ProductUnit getQuantityUnit();

  /**
   * <code>bool isVariableWeight = 9;</code>
   * @return The isVariableWeight.
   */
  boolean getIsVariableWeight();

  /**
   * <code>optional string message = 10;</code>
   * @return Whether the message field is set.
   */
  boolean hasMessage();
  /**
   * <code>optional string message = 10;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>optional string message = 10;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
