// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: db_service.proto

package com.example.grocerystoreorganizer.grpc;

/**
 * Protobuf type {@code grocery.database.ParsePriceTagImageResponse}
 */
public  final class ParsePriceTagImageResponse extends
    com.google.protobuf.GeneratedMessageLite<
        ParsePriceTagImageResponse, ParsePriceTagImageResponse.Builder> implements
    // @@protoc_insertion_point(message_implements:grocery.database.ParsePriceTagImageResponse)
    ParsePriceTagImageResponseOrBuilder {
  private ParsePriceTagImageResponse() {
    upc_ = "";
    message_ = "";
  }
  private int bitField0_;
  public static final int AMBIGUOUS_FIELD_NUMBER = 1;
  private boolean ambiguous_;
  /**
   * <code>bool ambiguous = 1;</code>
   * @return The ambiguous.
   */
  @java.lang.Override
  public boolean getAmbiguous() {
    return ambiguous_;
  }
  /**
   * <code>bool ambiguous = 1;</code>
   * @param value The ambiguous to set.
   */
  private void setAmbiguous(boolean value) {
    
    ambiguous_ = value;
  }
  /**
   * <code>bool ambiguous = 1;</code>
   */
  private void clearAmbiguous() {
    
    ambiguous_ = false;
  }

  public static final int UNPARSABLE_FIELD_NUMBER = 2;
  private boolean unparsable_;
  /**
   * <code>bool unparsable = 2;</code>
   * @return The unparsable.
   */
  @java.lang.Override
  public boolean getUnparsable() {
    return unparsable_;
  }
  /**
   * <code>bool unparsable = 2;</code>
   * @param value The unparsable to set.
   */
  private void setUnparsable(boolean value) {
    
    unparsable_ = value;
  }
  /**
   * <code>bool unparsable = 2;</code>
   */
  private void clearUnparsable() {
    
    unparsable_ = false;
  }

  public static final int UPCPARSABLE_FIELD_NUMBER = 3;
  private boolean upcParsable_;
  /**
   * <code>bool upcParsable = 3;</code>
   * @return The upcParsable.
   */
  @java.lang.Override
  public boolean getUpcParsable() {
    return upcParsable_;
  }
  /**
   * <code>bool upcParsable = 3;</code>
   * @param value The upcParsable to set.
   */
  private void setUpcParsable(boolean value) {
    
    upcParsable_ = value;
  }
  /**
   * <code>bool upcParsable = 3;</code>
   */
  private void clearUpcParsable() {
    
    upcParsable_ = false;
  }

  public static final int UPC_FIELD_NUMBER = 4;
  private java.lang.String upc_;
  /**
   * <code>optional string upc = 4;</code>
   * @return Whether the upc field is set.
   */
  @java.lang.Override
  public boolean hasUpc() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>optional string upc = 4;</code>
   * @return The upc.
   */
  @java.lang.Override
  public java.lang.String getUpc() {
    return upc_;
  }
  /**
   * <code>optional string upc = 4;</code>
   * @return The bytes for upc.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getUpcBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(upc_);
  }
  /**
   * <code>optional string upc = 4;</code>
   * @param value The upc to set.
   */
  private void setUpc(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  bitField0_ |= 0x00000001;
    upc_ = value;
  }
  /**
   * <code>optional string upc = 4;</code>
   */
  private void clearUpc() {
    bitField0_ = (bitField0_ & ~0x00000001);
    upc_ = getDefaultInstance().getUpc();
  }
  /**
   * <code>optional string upc = 4;</code>
   * @param value The bytes for upc to set.
   */
  private void setUpcBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    upc_ = value.toStringUtf8();
    bitField0_ |= 0x00000001;
  }

  public static final int PRICETOTAL_FIELD_NUMBER = 5;
  private double priceTotal_;
  /**
   * <code>optional double priceTotal = 5;</code>
   * @return Whether the priceTotal field is set.
   */
  @java.lang.Override
  public boolean hasPriceTotal() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>optional double priceTotal = 5;</code>
   * @return The priceTotal.
   */
  @java.lang.Override
  public double getPriceTotal() {
    return priceTotal_;
  }
  /**
   * <code>optional double priceTotal = 5;</code>
   * @param value The priceTotal to set.
   */
  private void setPriceTotal(double value) {
    bitField0_ |= 0x00000002;
    priceTotal_ = value;
  }
  /**
   * <code>optional double priceTotal = 5;</code>
   */
  private void clearPriceTotal() {
    bitField0_ = (bitField0_ & ~0x00000002);
    priceTotal_ = 0D;
  }

  public static final int PACKCOUNT_FIELD_NUMBER = 6;
  private int packCount_;
  /**
   * <code>optional int32 packCount = 6;</code>
   * @return Whether the packCount field is set.
   */
  @java.lang.Override
  public boolean hasPackCount() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <code>optional int32 packCount = 6;</code>
   * @return The packCount.
   */
  @java.lang.Override
  public int getPackCount() {
    return packCount_;
  }
  /**
   * <code>optional int32 packCount = 6;</code>
   * @param value The packCount to set.
   */
  private void setPackCount(int value) {
    bitField0_ |= 0x00000004;
    packCount_ = value;
  }
  /**
   * <code>optional int32 packCount = 6;</code>
   */
  private void clearPackCount() {
    bitField0_ = (bitField0_ & ~0x00000004);
    packCount_ = 0;
  }

  public static final int NETQUANTITY_FIELD_NUMBER = 7;
  private double netQuantity_;
  /**
   * <code>optional double netQuantity = 7;</code>
   * @return Whether the netQuantity field is set.
   */
  @java.lang.Override
  public boolean hasNetQuantity() {
    return ((bitField0_ & 0x00000008) != 0);
  }
  /**
   * <code>optional double netQuantity = 7;</code>
   * @return The netQuantity.
   */
  @java.lang.Override
  public double getNetQuantity() {
    return netQuantity_;
  }
  /**
   * <code>optional double netQuantity = 7;</code>
   * @param value The netQuantity to set.
   */
  private void setNetQuantity(double value) {
    bitField0_ |= 0x00000008;
    netQuantity_ = value;
  }
  /**
   * <code>optional double netQuantity = 7;</code>
   */
  private void clearNetQuantity() {
    bitField0_ = (bitField0_ & ~0x00000008);
    netQuantity_ = 0D;
  }

  public static final int QUANTITYUNIT_FIELD_NUMBER = 8;
  private int quantityUnit_;
  /**
   * <code>optional .grocery.database.ProductUnit quantityUnit = 8;</code>
   * @return Whether the quantityUnit field is set.
   */
  @java.lang.Override
  public boolean hasQuantityUnit() {
    return ((bitField0_ & 0x00000010) != 0);
  }
  /**
   * <code>optional .grocery.database.ProductUnit quantityUnit = 8;</code>
   * @return The enum numeric value on the wire for quantityUnit.
   */
  @java.lang.Override
  public int getQuantityUnitValue() {
    return quantityUnit_;
  }
  /**
   * <code>optional .grocery.database.ProductUnit quantityUnit = 8;</code>
   * @return The quantityUnit.
   */
  @java.lang.Override
  public com.example.grocerystoreorganizer.grpc.ProductUnit getQuantityUnit() {
    com.example.grocerystoreorganizer.grpc.ProductUnit result = com.example.grocerystoreorganizer.grpc.ProductUnit.forNumber(quantityUnit_);
    return result == null ? com.example.grocerystoreorganizer.grpc.ProductUnit.UNRECOGNIZED : result;
  }
  /**
   * <code>optional .grocery.database.ProductUnit quantityUnit = 8;</code>
   * @param value The enum numeric value on the wire for quantityUnit to set.
   */
  private void setQuantityUnitValue(int value) {
    bitField0_ |= 0x00000010;  quantityUnit_ = value;
  }
  /**
   * <code>optional .grocery.database.ProductUnit quantityUnit = 8;</code>
   * @param value The quantityUnit to set.
   */
  private void setQuantityUnit(com.example.grocerystoreorganizer.grpc.ProductUnit value) {
    quantityUnit_ = value.getNumber();
    bitField0_ |= 0x00000010;
  }
  /**
   * <code>optional .grocery.database.ProductUnit quantityUnit = 8;</code>
   */
  private void clearQuantityUnit() {
    bitField0_ = (bitField0_ & ~0x00000010);
    quantityUnit_ = 0;
  }

  public static final int ISVARIABLEWEIGHT_FIELD_NUMBER = 9;
  private boolean isVariableWeight_;
  /**
   * <code>bool isVariableWeight = 9;</code>
   * @return The isVariableWeight.
   */
  @java.lang.Override
  public boolean getIsVariableWeight() {
    return isVariableWeight_;
  }
  /**
   * <code>bool isVariableWeight = 9;</code>
   * @param value The isVariableWeight to set.
   */
  private void setIsVariableWeight(boolean value) {
    
    isVariableWeight_ = value;
  }
  /**
   * <code>bool isVariableWeight = 9;</code>
   */
  private void clearIsVariableWeight() {
    
    isVariableWeight_ = false;
  }

  public static final int MESSAGE_FIELD_NUMBER = 10;
  private java.lang.String message_;
  /**
   * <code>optional string message = 10;</code>
   * @return Whether the message field is set.
   */
  @java.lang.Override
  public boolean hasMessage() {
    return ((bitField0_ & 0x00000020) != 0);
  }
  /**
   * <code>optional string message = 10;</code>
   * @return The message.
   */
  @java.lang.Override
  public java.lang.String getMessage() {
    return message_;
  }
  /**
   * <code>optional string message = 10;</code>
   * @return The bytes for message.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getMessageBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(message_);
  }
  /**
   * <code>optional string message = 10;</code>
   * @param value The message to set.
   */
  private void setMessage(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  bitField0_ |= 0x00000020;
    message_ = value;
  }
  /**
   * <code>optional string message = 10;</code>
   */
  private void clearMessage() {
    bitField0_ = (bitField0_ & ~0x00000020);
    message_ = getDefaultInstance().getMessage();
  }
  /**
   * <code>optional string message = 10;</code>
   * @param value The bytes for message to set.
   */
  private void setMessageBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    message_ = value.toStringUtf8();
    bitField0_ |= 0x00000020;
  }

  public static com.example.grocerystoreorganizer.grpc.ParsePriceTagImageResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.example.grocerystoreorganizer.grpc.ParsePriceTagImageResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.example.grocerystoreorganizer.grpc.ParsePriceTagImageResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.example.grocerystoreorganizer.grpc.ParsePriceTagImageResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.example.grocerystoreorganizer.grpc.ParsePriceTagImageResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.example.grocerystoreorganizer.grpc.ParsePriceTagImageResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.example.grocerystoreorganizer.grpc.ParsePriceTagImageResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.example.grocerystoreorganizer.grpc.ParsePriceTagImageResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.example.grocerystoreorganizer.grpc.ParsePriceTagImageResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static com.example.grocerystoreorganizer.grpc.ParsePriceTagImageResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.example.grocerystoreorganizer.grpc.ParsePriceTagImageResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.example.grocerystoreorganizer.grpc.ParsePriceTagImageResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(com.example.grocerystoreorganizer.grpc.ParsePriceTagImageResponse prototype) {
    return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code grocery.database.ParsePriceTagImageResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.example.grocerystoreorganizer.grpc.ParsePriceTagImageResponse, Builder> implements
      // @@protoc_insertion_point(builder_implements:grocery.database.ParsePriceTagImageResponse)
      com.example.grocerystoreorganizer.grpc.ParsePriceTagImageResponseOrBuilder {
    // Construct using com.example.grocerystoreorganizer.grpc.ParsePriceTagImageResponse.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>bool ambiguous = 1;</code>
     * @return The ambiguous.
     */
    @java.lang.Override
    public boolean getAmbiguous() {
      return instance.getAmbiguous();
    }
    /**
     * <code>bool ambiguous = 1;</code>
     * @param value The ambiguous to set.
     * @return This builder for chaining.
     */
    public Builder setAmbiguous(boolean value) {
      copyOnWrite();
      instance.setAmbiguous(value);
      return this;
    }
    /**
     * <code>bool ambiguous = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearAmbiguous() {
      copyOnWrite();
      instance.clearAmbiguous();
      return this;
    }

    /**
     * <code>bool unparsable = 2;</code>
     * @return The unparsable.
     */
    @java.lang.Override
    public boolean getUnparsable() {
      return instance.getUnparsable();
    }
    /**
     * <code>bool unparsable = 2;</code>
     * @param value The unparsable to set.
     * @return This builder for chaining.
     */
    public Builder setUnparsable(boolean value) {
      copyOnWrite();
      instance.setUnparsable(value);
      return this;
    }
    /**
     * <code>bool unparsable = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearUnparsable() {
      copyOnWrite();
      instance.clearUnparsable();
      return this;
    }

    /**
     * <code>bool upcParsable = 3;</code>
     * @return The upcParsable.
     */
    @java.lang.Override
    public boolean getUpcParsable() {
      return instance.getUpcParsable();
    }
    /**
     * <code>bool upcParsable = 3;</code>
     * @param value The upcParsable to set.
     * @return This builder for chaining.
     */
    public Builder setUpcParsable(boolean value) {
      copyOnWrite();
      instance.setUpcParsable(value);
      return this;
    }
    /**
     * <code>bool upcParsable = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearUpcParsable() {
      copyOnWrite();
      instance.clearUpcParsable();
      return this;
    }

    /**
     * <code>optional string upc = 4;</code>
     * @return Whether the upc field is set.
     */
    @java.lang.Override
    public boolean hasUpc() {
      return instance.hasUpc();
    }
    /**
     * <code>optional string upc = 4;</code>
     * @return The upc.
     */
    @java.lang.Override
    public java.lang.String getUpc() {
      return instance.getUpc();
    }
    /**
     * <code>optional string upc = 4;</code>
     * @return The bytes for upc.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getUpcBytes() {
      return instance.getUpcBytes();
    }
    /**
     * <code>optional string upc = 4;</code>
     * @param value The upc to set.
     * @return This builder for chaining.
     */
    public Builder setUpc(
        java.lang.String value) {
      copyOnWrite();
      instance.setUpc(value);
      return this;
    }
    /**
     * <code>optional string upc = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearUpc() {
      copyOnWrite();
      instance.clearUpc();
      return this;
    }
    /**
     * <code>optional string upc = 4;</code>
     * @param value The bytes for upc to set.
     * @return This builder for chaining.
     */
    public Builder setUpcBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setUpcBytes(value);
      return this;
    }

    /**
     * <code>optional double priceTotal = 5;</code>
     * @return Whether the priceTotal field is set.
     */
    @java.lang.Override
    public boolean hasPriceTotal() {
      return instance.hasPriceTotal();
    }
    /**
     * <code>optional double priceTotal = 5;</code>
     * @return The priceTotal.
     */
    @java.lang.Override
    public double getPriceTotal() {
      return instance.getPriceTotal();
    }
    /**
     * <code>optional double priceTotal = 5;</code>
     * @param value The priceTotal to set.
     * @return This builder for chaining.
     */
    public Builder setPriceTotal(double value) {
      copyOnWrite();
      instance.setPriceTotal(value);
      return this;
    }
    /**
     * <code>optional double priceTotal = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearPriceTotal() {
      copyOnWrite();
      instance.clearPriceTotal();
      return this;
    }

    /**
     * <code>optional int32 packCount = 6;</code>
     * @return Whether the packCount field is set.
     */
    @java.lang.Override
    public boolean hasPackCount() {
      return instance.hasPackCount();
    }
    /**
     * <code>optional int32 packCount = 6;</code>
     * @return The packCount.
     */
    @java.lang.Override
    public int getPackCount() {
      return instance.getPackCount();
    }
    /**
     * <code>optional int32 packCount = 6;</code>
     * @param value The packCount to set.
     * @return This builder for chaining.
     */
    public Builder setPackCount(int value) {
      copyOnWrite();
      instance.setPackCount(value);
      return this;
    }
    /**
     * <code>optional int32 packCount = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearPackCount() {
      copyOnWrite();
      instance.clearPackCount();
      return this;
    }

    /**
     * <code>optional double netQuantity = 7;</code>
     * @return Whether the netQuantity field is set.
     */
    @java.lang.Override
    public boolean hasNetQuantity() {
      return instance.hasNetQuantity();
    }
    /**
     * <code>optional double netQuantity = 7;</code>
     * @return The netQuantity.
     */
    @java.lang.Override
    public double getNetQuantity() {
      return instance.getNetQuantity();
    }
    /**
     * <code>optional double netQuantity = 7;</code>
     * @param value The netQuantity to set.
     * @return This builder for chaining.
     */
    public Builder setNetQuantity(double value) {
      copyOnWrite();
      instance.setNetQuantity(value);
      return this;
    }
    /**
     * <code>optional double netQuantity = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearNetQuantity() {
      copyOnWrite();
      instance.clearNetQuantity();
      return this;
    }

    /**
     * <code>optional .grocery.database.ProductUnit quantityUnit = 8;</code>
     * @return Whether the quantityUnit field is set.
     */
    @java.lang.Override
    public boolean hasQuantityUnit() {
      return instance.hasQuantityUnit();
    }
    /**
     * <code>optional .grocery.database.ProductUnit quantityUnit = 8;</code>
     * @return The enum numeric value on the wire for quantityUnit.
     */
    @java.lang.Override
    public int getQuantityUnitValue() {
      return instance.getQuantityUnitValue();
    }
    /**
     * <code>optional .grocery.database.ProductUnit quantityUnit = 8;</code>
     * @param value The quantityUnit to set.
     * @return This builder for chaining.
     */
    public Builder setQuantityUnitValue(int value) {
      copyOnWrite();
      instance.setQuantityUnitValue(value);
      return this;
    }
    /**
     * <code>optional .grocery.database.ProductUnit quantityUnit = 8;</code>
     * @return The quantityUnit.
     */
    @java.lang.Override
    public com.example.grocerystoreorganizer.grpc.ProductUnit getQuantityUnit() {
      return instance.getQuantityUnit();
    }
    /**
     * <code>optional .grocery.database.ProductUnit quantityUnit = 8;</code>
     * @param value The enum numeric value on the wire for quantityUnit to set.
     * @return This builder for chaining.
     */
    public Builder setQuantityUnit(com.example.grocerystoreorganizer.grpc.ProductUnit value) {
      copyOnWrite();
      instance.setQuantityUnit(value);
      return this;
    }
    /**
     * <code>optional .grocery.database.ProductUnit quantityUnit = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearQuantityUnit() {
      copyOnWrite();
      instance.clearQuantityUnit();
      return this;
    }

    /**
     * <code>bool isVariableWeight = 9;</code>
     * @return The isVariableWeight.
     */
    @java.lang.Override
    public boolean getIsVariableWeight() {
      return instance.getIsVariableWeight();
    }
    /**
     * <code>bool isVariableWeight = 9;</code>
     * @param value The isVariableWeight to set.
     * @return This builder for chaining.
     */
    public Builder setIsVariableWeight(boolean value) {
      copyOnWrite();
      instance.setIsVariableWeight(value);
      return this;
    }
    /**
     * <code>bool isVariableWeight = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearIsVariableWeight() {
      copyOnWrite();
      instance.clearIsVariableWeight();
      return this;
    }

    /**
     * <code>optional string message = 10;</code>
     * @return Whether the message field is set.
     */
    @java.lang.Override
    public boolean hasMessage() {
      return instance.hasMessage();
    }
    /**
     * <code>optional string message = 10;</code>
     * @return The message.
     */
    @java.lang.Override
    public java.lang.String getMessage() {
      return instance.getMessage();
    }
    /**
     * <code>optional string message = 10;</code>
     * @return The bytes for message.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getMessageBytes() {
      return instance.getMessageBytes();
    }
    /**
     * <code>optional string message = 10;</code>
     * @param value The message to set.
     * @return This builder for chaining.
     */
    public Builder setMessage(
        java.lang.String value) {
      copyOnWrite();
      instance.setMessage(value);
      return this;
    }
    /**
     * <code>optional string message = 10;</code>
     * @return This builder for chaining.
     */
    public Builder clearMessage() {
      copyOnWrite();
      instance.clearMessage();
      return this;
    }
    /**
     * <code>optional string message = 10;</code>
     * @param value The bytes for message to set.
     * @return This builder for chaining.
     */
    public Builder setMessageBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setMessageBytes(value);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:grocery.database.ParsePriceTagImageResponse)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.example.grocerystoreorganizer.grpc.ParsePriceTagImageResponse();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "bitField0_",
            "ambiguous_",
            "unparsable_",
            "upcParsable_",
            "upc_",
            "priceTotal_",
            "packCount_",
            "netQuantity_",
            "quantityUnit_",
            "isVariableWeight_",
            "message_",
          };
          java.lang.String info =
              "\u0000\n\u0000\u0001\u0001\n\n\u0000\u0000\u0000\u0001\u0007\u0002\u0007\u0003\u0007" +
              "\u0004\u1208\u0000\u0005\u1000\u0001\u0006\u1004\u0002\u0007\u1000\u0003\b\u100c" +
              "\u0004\t\u0007\n\u1208\u0005";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<com.example.grocerystoreorganizer.grpc.ParsePriceTagImageResponse> parser = PARSER;
        if (parser == null) {
          synchronized (com.example.grocerystoreorganizer.grpc.ParsePriceTagImageResponse.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<com.example.grocerystoreorganizer.grpc.ParsePriceTagImageResponse>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:grocery.database.ParsePriceTagImageResponse)
  private static final com.example.grocerystoreorganizer.grpc.ParsePriceTagImageResponse DEFAULT_INSTANCE;
  static {
    ParsePriceTagImageResponse defaultInstance = new ParsePriceTagImageResponse();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      ParsePriceTagImageResponse.class, defaultInstance);
  }

  public static com.example.grocerystoreorganizer.grpc.ParsePriceTagImageResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<ParsePriceTagImageResponse> PARSER;

  public static com.google.protobuf.Parser<ParsePriceTagImageResponse> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

