// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: db_service.proto

package com.example.grocerystoreorganizer.grpc;

/**
 * Protobuf type {@code grocery.database.ParsePriceTagImageRequest}
 */
public  final class ParsePriceTagImageRequest extends
    com.google.protobuf.GeneratedMessageLite<
        ParsePriceTagImageRequest, ParsePriceTagImageRequest.Builder> implements
    // @@protoc_insertion_point(message_implements:grocery.database.ParsePriceTagImageRequest)
    ParsePriceTagImageRequestOrBuilder {
  private ParsePriceTagImageRequest() {
    imageJpeg_ = com.google.protobuf.ByteString.EMPTY;
    imageFilename_ = "";
  }
  private int bitField0_;
  public static final int IMAGEJPEG_FIELD_NUMBER = 1;
  private com.google.protobuf.ByteString imageJpeg_;
  /**
   * <code>bytes imageJpeg = 1;</code>
   * @return The imageJpeg.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getImageJpeg() {
    return imageJpeg_;
  }
  /**
   * <code>bytes imageJpeg = 1;</code>
   * @param value The imageJpeg to set.
   */
  private void setImageJpeg(com.google.protobuf.ByteString value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    imageJpeg_ = value;
  }
  /**
   * <code>bytes imageJpeg = 1;</code>
   */
  private void clearImageJpeg() {
    
    imageJpeg_ = getDefaultInstance().getImageJpeg();
  }

  public static final int IMAGEFILENAME_FIELD_NUMBER = 2;
  private java.lang.String imageFilename_;
  /**
   * <code>optional string imageFilename = 2;</code>
   * @return Whether the imageFilename field is set.
   */
  @java.lang.Override
  public boolean hasImageFilename() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>optional string imageFilename = 2;</code>
   * @return The imageFilename.
   */
  @java.lang.Override
  public java.lang.String getImageFilename() {
    return imageFilename_;
  }
  /**
   * <code>optional string imageFilename = 2;</code>
   * @return The bytes for imageFilename.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getImageFilenameBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(imageFilename_);
  }
  /**
   * <code>optional string imageFilename = 2;</code>
   * @param value The imageFilename to set.
   */
  private void setImageFilename(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  bitField0_ |= 0x00000001;
    imageFilename_ = value;
  }
  /**
   * <code>optional string imageFilename = 2;</code>
   */
  private void clearImageFilename() {
    bitField0_ = (bitField0_ & ~0x00000001);
    imageFilename_ = getDefaultInstance().getImageFilename();
  }
  /**
   * <code>optional string imageFilename = 2;</code>
   * @param value The bytes for imageFilename to set.
   */
  private void setImageFilenameBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    imageFilename_ = value.toStringUtf8();
    bitField0_ |= 0x00000001;
  }

  public static com.example.grocerystoreorganizer.grpc.ParsePriceTagImageRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.example.grocerystoreorganizer.grpc.ParsePriceTagImageRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.example.grocerystoreorganizer.grpc.ParsePriceTagImageRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.example.grocerystoreorganizer.grpc.ParsePriceTagImageRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.example.grocerystoreorganizer.grpc.ParsePriceTagImageRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.example.grocerystoreorganizer.grpc.ParsePriceTagImageRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.example.grocerystoreorganizer.grpc.ParsePriceTagImageRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.example.grocerystoreorganizer.grpc.ParsePriceTagImageRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.example.grocerystoreorganizer.grpc.ParsePriceTagImageRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static com.example.grocerystoreorganizer.grpc.ParsePriceTagImageRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.example.grocerystoreorganizer.grpc.ParsePriceTagImageRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.example.grocerystoreorganizer.grpc.ParsePriceTagImageRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(com.example.grocerystoreorganizer.grpc.ParsePriceTagImageRequest prototype) {
    return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code grocery.database.ParsePriceTagImageRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.example.grocerystoreorganizer.grpc.ParsePriceTagImageRequest, Builder> implements
      // @@protoc_insertion_point(builder_implements:grocery.database.ParsePriceTagImageRequest)
      com.example.grocerystoreorganizer.grpc.ParsePriceTagImageRequestOrBuilder {
    // Construct using com.example.grocerystoreorganizer.grpc.ParsePriceTagImageRequest.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>bytes imageJpeg = 1;</code>
     * @return The imageJpeg.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getImageJpeg() {
      return instance.getImageJpeg();
    }
    /**
     * <code>bytes imageJpeg = 1;</code>
     * @param value The imageJpeg to set.
     * @return This builder for chaining.
     */
    public Builder setImageJpeg(com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setImageJpeg(value);
      return this;
    }
    /**
     * <code>bytes imageJpeg = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearImageJpeg() {
      copyOnWrite();
      instance.clearImageJpeg();
      return this;
    }

    /**
     * <code>optional string imageFilename = 2;</code>
     * @return Whether the imageFilename field is set.
     */
    @java.lang.Override
    public boolean hasImageFilename() {
      return instance.hasImageFilename();
    }
    /**
     * <code>optional string imageFilename = 2;</code>
     * @return The imageFilename.
     */
    @java.lang.Override
    public java.lang.String getImageFilename() {
      return instance.getImageFilename();
    }
    /**
     * <code>optional string imageFilename = 2;</code>
     * @return The bytes for imageFilename.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getImageFilenameBytes() {
      return instance.getImageFilenameBytes();
    }
    /**
     * <code>optional string imageFilename = 2;</code>
     * @param value The imageFilename to set.
     * @return This builder for chaining.
     */
    public Builder setImageFilename(
        java.lang.String value) {
      copyOnWrite();
      instance.setImageFilename(value);
      return this;
    }
    /**
     * <code>optional string imageFilename = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearImageFilename() {
      copyOnWrite();
      instance.clearImageFilename();
      return this;
    }
    /**
     * <code>optional string imageFilename = 2;</code>
     * @param value The bytes for imageFilename to set.
     * @return This builder for chaining.
     */
    public Builder setImageFilenameBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setImageFilenameBytes(value);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:grocery.database.ParsePriceTagImageRequest)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.example.grocerystoreorganizer.grpc.ParsePriceTagImageRequest();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "bitField0_",
            "imageJpeg_",
            "imageFilename_",
          };
          java.lang.String info =
              "\u0000\u0002\u0000\u0001\u0001\u0002\u0002\u0000\u0000\u0000\u0001\n\u0002\u1208" +
              "\u0000";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<com.example.grocerystoreorganizer.grpc.ParsePriceTagImageRequest> parser = PARSER;
        if (parser == null) {
          synchronized (com.example.grocerystoreorganizer.grpc.ParsePriceTagImageRequest.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<com.example.grocerystoreorganizer.grpc.ParsePriceTagImageRequest>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:grocery.database.ParsePriceTagImageRequest)
  private static final com.example.grocerystoreorganizer.grpc.ParsePriceTagImageRequest DEFAULT_INSTANCE;
  static {
    ParsePriceTagImageRequest defaultInstance = new ParsePriceTagImageRequest();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      ParsePriceTagImageRequest.class, defaultInstance);
  }

  public static com.example.grocerystoreorganizer.grpc.ParsePriceTagImageRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<ParsePriceTagImageRequest> PARSER;

  public static com.google.protobuf.Parser<ParsePriceTagImageRequest> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

