// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: db_service.proto

package com.example.grocerystoreorganizer.grpc;

/**
 * Protobuf type {@code grocery.database.PriceObservationResponse}
 */
public  final class PriceObservationResponse extends
    com.google.protobuf.GeneratedMessageLite<
        PriceObservationResponse, PriceObservationResponse.Builder> implements
    // @@protoc_insertion_point(message_implements:grocery.database.PriceObservationResponse)
    PriceObservationResponseOrBuilder {
  private PriceObservationResponse() {
  }
  private int bitField0_;
  public static final int OBSERVATIONID_FIELD_NUMBER = 1;
  private int observationId_;
  /**
   * <code>optional uint32 observationId = 1;</code>
   * @return Whether the observationId field is set.
   */
  @java.lang.Override
  public boolean hasObservationId() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>optional uint32 observationId = 1;</code>
   * @return The observationId.
   */
  @java.lang.Override
  public int getObservationId() {
    return observationId_;
  }
  /**
   * <code>optional uint32 observationId = 1;</code>
   * @param value The observationId to set.
   */
  private void setObservationId(int value) {
    bitField0_ |= 0x00000001;
    observationId_ = value;
  }
  /**
   * <code>optional uint32 observationId = 1;</code>
   */
  private void clearObservationId() {
    bitField0_ = (bitField0_ & ~0x00000001);
    observationId_ = 0;
  }

  public static com.example.grocerystoreorganizer.grpc.PriceObservationResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.example.grocerystoreorganizer.grpc.PriceObservationResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.example.grocerystoreorganizer.grpc.PriceObservationResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.example.grocerystoreorganizer.grpc.PriceObservationResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.example.grocerystoreorganizer.grpc.PriceObservationResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.example.grocerystoreorganizer.grpc.PriceObservationResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.example.grocerystoreorganizer.grpc.PriceObservationResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.example.grocerystoreorganizer.grpc.PriceObservationResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.example.grocerystoreorganizer.grpc.PriceObservationResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static com.example.grocerystoreorganizer.grpc.PriceObservationResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.example.grocerystoreorganizer.grpc.PriceObservationResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.example.grocerystoreorganizer.grpc.PriceObservationResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(com.example.grocerystoreorganizer.grpc.PriceObservationResponse prototype) {
    return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code grocery.database.PriceObservationResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.example.grocerystoreorganizer.grpc.PriceObservationResponse, Builder> implements
      // @@protoc_insertion_point(builder_implements:grocery.database.PriceObservationResponse)
      com.example.grocerystoreorganizer.grpc.PriceObservationResponseOrBuilder {
    // Construct using com.example.grocerystoreorganizer.grpc.PriceObservationResponse.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>optional uint32 observationId = 1;</code>
     * @return Whether the observationId field is set.
     */
    @java.lang.Override
    public boolean hasObservationId() {
      return instance.hasObservationId();
    }
    /**
     * <code>optional uint32 observationId = 1;</code>
     * @return The observationId.
     */
    @java.lang.Override
    public int getObservationId() {
      return instance.getObservationId();
    }
    /**
     * <code>optional uint32 observationId = 1;</code>
     * @param value The observationId to set.
     * @return This builder for chaining.
     */
    public Builder setObservationId(int value) {
      copyOnWrite();
      instance.setObservationId(value);
      return this;
    }
    /**
     * <code>optional uint32 observationId = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearObservationId() {
      copyOnWrite();
      instance.clearObservationId();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:grocery.database.PriceObservationResponse)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.example.grocerystoreorganizer.grpc.PriceObservationResponse();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "bitField0_",
            "observationId_",
          };
          java.lang.String info =
              "\u0000\u0001\u0000\u0001\u0001\u0001\u0001\u0000\u0000\u0000\u0001\u100b\u0000";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<com.example.grocerystoreorganizer.grpc.PriceObservationResponse> parser = PARSER;
        if (parser == null) {
          synchronized (com.example.grocerystoreorganizer.grpc.PriceObservationResponse.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<com.example.grocerystoreorganizer.grpc.PriceObservationResponse>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:grocery.database.PriceObservationResponse)
  private static final com.example.grocerystoreorganizer.grpc.PriceObservationResponse DEFAULT_INSTANCE;
  static {
    PriceObservationResponse defaultInstance = new PriceObservationResponse();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      PriceObservationResponse.class, defaultInstance);
  }

  public static com.example.grocerystoreorganizer.grpc.PriceObservationResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<PriceObservationResponse> PARSER;

  public static com.google.protobuf.Parser<PriceObservationResponse> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

