// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: db_service.proto

package com.example.grocerystoreorganizer.grpc;

public interface PriceObservationResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:grocery.database.PriceObservationResponse)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>optional uint32 observationId = 1;</code>
   * @return Whether the observationId field is set.
   */
  boolean hasObservationId();
  /**
   * <code>optional uint32 observationId = 1;</code>
   * @return The observationId.
   */
  int getObservationId();
}
