// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: db_service.proto

package com.example.grocerystoreorganizer.grpc;

/**
 * Protobuf type {@code grocery.database.PriceObservationRequest}
 */
public  final class PriceObservationRequest extends
    com.google.protobuf.GeneratedMessageLite<
        PriceObservationRequest, PriceObservationRequest.Builder> implements
    // @@protoc_insertion_point(message_implements:grocery.database.PriceObservationRequest)
    PriceObservationRequestOrBuilder {
  private PriceObservationRequest() {
    observedAt_ = "";
    trainingImageJpeg_ = com.google.protobuf.ByteString.EMPTY;
    trainingImageFilename_ = "";
  }
  private int bitField0_;
  public static final int STORE_FIELD_NUMBER = 1;
  private com.example.grocerystoreorganizer.grpc.StoreInfo store_;
  /**
   * <code>.grocery.database.StoreInfo store = 1;</code>
   */
  @java.lang.Override
  public boolean hasStore() {
    return store_ != null;
  }
  /**
   * <code>.grocery.database.StoreInfo store = 1;</code>
   */
  @java.lang.Override
  public com.example.grocerystoreorganizer.grpc.StoreInfo getStore() {
    return store_ == null ? com.example.grocerystoreorganizer.grpc.StoreInfo.getDefaultInstance() : store_;
  }
  /**
   * <code>.grocery.database.StoreInfo store = 1;</code>
   */
  private void setStore(com.example.grocerystoreorganizer.grpc.StoreInfo value) {
    value.getClass();
  store_ = value;
    
    }
  /**
   * <code>.grocery.database.StoreInfo store = 1;</code>
   */
  @java.lang.SuppressWarnings({"ReferenceEquality"})
  private void mergeStore(com.example.grocerystoreorganizer.grpc.StoreInfo value) {
    value.getClass();
  if (store_ != null &&
        store_ != com.example.grocerystoreorganizer.grpc.StoreInfo.getDefaultInstance()) {
      store_ =
        com.example.grocerystoreorganizer.grpc.StoreInfo.newBuilder(store_).mergeFrom(value).buildPartial();
    } else {
      store_ = value;
    }
    
  }
  /**
   * <code>.grocery.database.StoreInfo store = 1;</code>
   */
  private void clearStore() {  store_ = null;
    
  }

  public static final int UPC_FIELD_NUMBER = 2;
  private com.example.grocerystoreorganizer.grpc.UpcInfo upc_;
  /**
   * <code>.grocery.database.UpcInfo upc = 2;</code>
   */
  @java.lang.Override
  public boolean hasUpc() {
    return upc_ != null;
  }
  /**
   * <code>.grocery.database.UpcInfo upc = 2;</code>
   */
  @java.lang.Override
  public com.example.grocerystoreorganizer.grpc.UpcInfo getUpc() {
    return upc_ == null ? com.example.grocerystoreorganizer.grpc.UpcInfo.getDefaultInstance() : upc_;
  }
  /**
   * <code>.grocery.database.UpcInfo upc = 2;</code>
   */
  private void setUpc(com.example.grocerystoreorganizer.grpc.UpcInfo value) {
    value.getClass();
  upc_ = value;
    
    }
  /**
   * <code>.grocery.database.UpcInfo upc = 2;</code>
   */
  @java.lang.SuppressWarnings({"ReferenceEquality"})
  private void mergeUpc(com.example.grocerystoreorganizer.grpc.UpcInfo value) {
    value.getClass();
  if (upc_ != null &&
        upc_ != com.example.grocerystoreorganizer.grpc.UpcInfo.getDefaultInstance()) {
      upc_ =
        com.example.grocerystoreorganizer.grpc.UpcInfo.newBuilder(upc_).mergeFrom(value).buildPartial();
    } else {
      upc_ = value;
    }
    
  }
  /**
   * <code>.grocery.database.UpcInfo upc = 2;</code>
   */
  private void clearUpc() {  upc_ = null;
    
  }

  public static final int PRICETOTAL_FIELD_NUMBER = 3;
  private double priceTotal_;
  /**
   * <code>double priceTotal = 3;</code>
   * @return The priceTotal.
   */
  @java.lang.Override
  public double getPriceTotal() {
    return priceTotal_;
  }
  /**
   * <code>double priceTotal = 3;</code>
   * @param value The priceTotal to set.
   */
  private void setPriceTotal(double value) {
    
    priceTotal_ = value;
  }
  /**
   * <code>double priceTotal = 3;</code>
   */
  private void clearPriceTotal() {
    
    priceTotal_ = 0D;
  }

  public static final int OBSERVEDAT_FIELD_NUMBER = 4;
  private java.lang.String observedAt_;
  /**
   * <code>string observedAt = 4;</code>
   * @return The observedAt.
   */
  @java.lang.Override
  public java.lang.String getObservedAt() {
    return observedAt_;
  }
  /**
   * <code>string observedAt = 4;</code>
   * @return The bytes for observedAt.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getObservedAtBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(observedAt_);
  }
  /**
   * <code>string observedAt = 4;</code>
   * @param value The observedAt to set.
   */
  private void setObservedAt(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    observedAt_ = value;
  }
  /**
   * <code>string observedAt = 4;</code>
   */
  private void clearObservedAt() {
    
    observedAt_ = getDefaultInstance().getObservedAt();
  }
  /**
   * <code>string observedAt = 4;</code>
   * @param value The bytes for observedAt to set.
   */
  private void setObservedAtBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    observedAt_ = value.toStringUtf8();
    
  }

  public static final int ISSALE_FIELD_NUMBER = 5;
  private boolean isSale_;
  /**
   * <code>bool isSale = 5;</code>
   * @return The isSale.
   */
  @java.lang.Override
  public boolean getIsSale() {
    return isSale_;
  }
  /**
   * <code>bool isSale = 5;</code>
   * @param value The isSale to set.
   */
  private void setIsSale(boolean value) {
    
    isSale_ = value;
  }
  /**
   * <code>bool isSale = 5;</code>
   */
  private void clearIsSale() {
    
    isSale_ = false;
  }

  public static final int SALEINFO_FIELD_NUMBER = 6;
  private com.example.grocerystoreorganizer.grpc.SaleInfo saleInfo_;
  /**
   * <code>optional .grocery.database.SaleInfo saleInfo = 6;</code>
   */
  @java.lang.Override
  public boolean hasSaleInfo() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>optional .grocery.database.SaleInfo saleInfo = 6;</code>
   */
  @java.lang.Override
  public com.example.grocerystoreorganizer.grpc.SaleInfo getSaleInfo() {
    return saleInfo_ == null ? com.example.grocerystoreorganizer.grpc.SaleInfo.getDefaultInstance() : saleInfo_;
  }
  /**
   * <code>optional .grocery.database.SaleInfo saleInfo = 6;</code>
   */
  private void setSaleInfo(com.example.grocerystoreorganizer.grpc.SaleInfo value) {
    value.getClass();
  saleInfo_ = value;
    bitField0_ |= 0x00000001;
    }
  /**
   * <code>optional .grocery.database.SaleInfo saleInfo = 6;</code>
   */
  @java.lang.SuppressWarnings({"ReferenceEquality"})
  private void mergeSaleInfo(com.example.grocerystoreorganizer.grpc.SaleInfo value) {
    value.getClass();
  if (saleInfo_ != null &&
        saleInfo_ != com.example.grocerystoreorganizer.grpc.SaleInfo.getDefaultInstance()) {
      saleInfo_ =
        com.example.grocerystoreorganizer.grpc.SaleInfo.newBuilder(saleInfo_).mergeFrom(value).buildPartial();
    } else {
      saleInfo_ = value;
    }
    bitField0_ |= 0x00000001;
  }
  /**
   * <code>optional .grocery.database.SaleInfo saleInfo = 6;</code>
   */
  private void clearSaleInfo() {  saleInfo_ = null;
    bitField0_ = (bitField0_ & ~0x00000001);
  }

  public static final int TRAININGIMAGEJPEG_FIELD_NUMBER = 7;
  private com.google.protobuf.ByteString trainingImageJpeg_;
  /**
   * <code>optional bytes trainingImageJpeg = 7;</code>
   * @return Whether the trainingImageJpeg field is set.
   */
  @java.lang.Override
  public boolean hasTrainingImageJpeg() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>optional bytes trainingImageJpeg = 7;</code>
   * @return The trainingImageJpeg.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getTrainingImageJpeg() {
    return trainingImageJpeg_;
  }
  /**
   * <code>optional bytes trainingImageJpeg = 7;</code>
   * @param value The trainingImageJpeg to set.
   */
  private void setTrainingImageJpeg(com.google.protobuf.ByteString value) {
    java.lang.Class<?> valueClass = value.getClass();
  bitField0_ |= 0x00000002;
    trainingImageJpeg_ = value;
  }
  /**
   * <code>optional bytes trainingImageJpeg = 7;</code>
   */
  private void clearTrainingImageJpeg() {
    bitField0_ = (bitField0_ & ~0x00000002);
    trainingImageJpeg_ = getDefaultInstance().getTrainingImageJpeg();
  }

  public static final int TRAININGIMAGEFILENAME_FIELD_NUMBER = 8;
  private java.lang.String trainingImageFilename_;
  /**
   * <code>optional string trainingImageFilename = 8;</code>
   * @return Whether the trainingImageFilename field is set.
   */
  @java.lang.Override
  public boolean hasTrainingImageFilename() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <code>optional string trainingImageFilename = 8;</code>
   * @return The trainingImageFilename.
   */
  @java.lang.Override
  public java.lang.String getTrainingImageFilename() {
    return trainingImageFilename_;
  }
  /**
   * <code>optional string trainingImageFilename = 8;</code>
   * @return The bytes for trainingImageFilename.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTrainingImageFilenameBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(trainingImageFilename_);
  }
  /**
   * <code>optional string trainingImageFilename = 8;</code>
   * @param value The trainingImageFilename to set.
   */
  private void setTrainingImageFilename(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  bitField0_ |= 0x00000004;
    trainingImageFilename_ = value;
  }
  /**
   * <code>optional string trainingImageFilename = 8;</code>
   */
  private void clearTrainingImageFilename() {
    bitField0_ = (bitField0_ & ~0x00000004);
    trainingImageFilename_ = getDefaultInstance().getTrainingImageFilename();
  }
  /**
   * <code>optional string trainingImageFilename = 8;</code>
   * @param value The bytes for trainingImageFilename to set.
   */
  private void setTrainingImageFilenameBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    trainingImageFilename_ = value.toStringUtf8();
    bitField0_ |= 0x00000004;
  }

  public static final int TRAININGIMAGEUPCPRESENT_FIELD_NUMBER = 9;
  private boolean trainingImageUpcPresent_;
  /**
   * <code>optional bool trainingImageUpcPresent = 9;</code>
   * @return Whether the trainingImageUpcPresent field is set.
   */
  @java.lang.Override
  public boolean hasTrainingImageUpcPresent() {
    return ((bitField0_ & 0x00000008) != 0);
  }
  /**
   * <code>optional bool trainingImageUpcPresent = 9;</code>
   * @return The trainingImageUpcPresent.
   */
  @java.lang.Override
  public boolean getTrainingImageUpcPresent() {
    return trainingImageUpcPresent_;
  }
  /**
   * <code>optional bool trainingImageUpcPresent = 9;</code>
   * @param value The trainingImageUpcPresent to set.
   */
  private void setTrainingImageUpcPresent(boolean value) {
    bitField0_ |= 0x00000008;
    trainingImageUpcPresent_ = value;
  }
  /**
   * <code>optional bool trainingImageUpcPresent = 9;</code>
   */
  private void clearTrainingImageUpcPresent() {
    bitField0_ = (bitField0_ & ~0x00000008);
    trainingImageUpcPresent_ = false;
  }

  public static com.example.grocerystoreorganizer.grpc.PriceObservationRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.example.grocerystoreorganizer.grpc.PriceObservationRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.example.grocerystoreorganizer.grpc.PriceObservationRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.example.grocerystoreorganizer.grpc.PriceObservationRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.example.grocerystoreorganizer.grpc.PriceObservationRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.example.grocerystoreorganizer.grpc.PriceObservationRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.example.grocerystoreorganizer.grpc.PriceObservationRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.example.grocerystoreorganizer.grpc.PriceObservationRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.example.grocerystoreorganizer.grpc.PriceObservationRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static com.example.grocerystoreorganizer.grpc.PriceObservationRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.example.grocerystoreorganizer.grpc.PriceObservationRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.example.grocerystoreorganizer.grpc.PriceObservationRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(com.example.grocerystoreorganizer.grpc.PriceObservationRequest prototype) {
    return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code grocery.database.PriceObservationRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.example.grocerystoreorganizer.grpc.PriceObservationRequest, Builder> implements
      // @@protoc_insertion_point(builder_implements:grocery.database.PriceObservationRequest)
      com.example.grocerystoreorganizer.grpc.PriceObservationRequestOrBuilder {
    // Construct using com.example.grocerystoreorganizer.grpc.PriceObservationRequest.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>.grocery.database.StoreInfo store = 1;</code>
     */
    @java.lang.Override
    public boolean hasStore() {
      return instance.hasStore();
    }
    /**
     * <code>.grocery.database.StoreInfo store = 1;</code>
     */
    @java.lang.Override
    public com.example.grocerystoreorganizer.grpc.StoreInfo getStore() {
      return instance.getStore();
    }
    /**
     * <code>.grocery.database.StoreInfo store = 1;</code>
     */
    public Builder setStore(com.example.grocerystoreorganizer.grpc.StoreInfo value) {
      copyOnWrite();
      instance.setStore(value);
      return this;
      }
    /**
     * <code>.grocery.database.StoreInfo store = 1;</code>
     */
    public Builder setStore(
        com.example.grocerystoreorganizer.grpc.StoreInfo.Builder builderForValue) {
      copyOnWrite();
      instance.setStore(builderForValue.build());
      return this;
    }
    /**
     * <code>.grocery.database.StoreInfo store = 1;</code>
     */
    public Builder mergeStore(com.example.grocerystoreorganizer.grpc.StoreInfo value) {
      copyOnWrite();
      instance.mergeStore(value);
      return this;
    }
    /**
     * <code>.grocery.database.StoreInfo store = 1;</code>
     */
    public Builder clearStore() {  copyOnWrite();
      instance.clearStore();
      return this;
    }

    /**
     * <code>.grocery.database.UpcInfo upc = 2;</code>
     */
    @java.lang.Override
    public boolean hasUpc() {
      return instance.hasUpc();
    }
    /**
     * <code>.grocery.database.UpcInfo upc = 2;</code>
     */
    @java.lang.Override
    public com.example.grocerystoreorganizer.grpc.UpcInfo getUpc() {
      return instance.getUpc();
    }
    /**
     * <code>.grocery.database.UpcInfo upc = 2;</code>
     */
    public Builder setUpc(com.example.grocerystoreorganizer.grpc.UpcInfo value) {
      copyOnWrite();
      instance.setUpc(value);
      return this;
      }
    /**
     * <code>.grocery.database.UpcInfo upc = 2;</code>
     */
    public Builder setUpc(
        com.example.grocerystoreorganizer.grpc.UpcInfo.Builder builderForValue) {
      copyOnWrite();
      instance.setUpc(builderForValue.build());
      return this;
    }
    /**
     * <code>.grocery.database.UpcInfo upc = 2;</code>
     */
    public Builder mergeUpc(com.example.grocerystoreorganizer.grpc.UpcInfo value) {
      copyOnWrite();
      instance.mergeUpc(value);
      return this;
    }
    /**
     * <code>.grocery.database.UpcInfo upc = 2;</code>
     */
    public Builder clearUpc() {  copyOnWrite();
      instance.clearUpc();
      return this;
    }

    /**
     * <code>double priceTotal = 3;</code>
     * @return The priceTotal.
     */
    @java.lang.Override
    public double getPriceTotal() {
      return instance.getPriceTotal();
    }
    /**
     * <code>double priceTotal = 3;</code>
     * @param value The priceTotal to set.
     * @return This builder for chaining.
     */
    public Builder setPriceTotal(double value) {
      copyOnWrite();
      instance.setPriceTotal(value);
      return this;
    }
    /**
     * <code>double priceTotal = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearPriceTotal() {
      copyOnWrite();
      instance.clearPriceTotal();
      return this;
    }

    /**
     * <code>string observedAt = 4;</code>
     * @return The observedAt.
     */
    @java.lang.Override
    public java.lang.String getObservedAt() {
      return instance.getObservedAt();
    }
    /**
     * <code>string observedAt = 4;</code>
     * @return The bytes for observedAt.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getObservedAtBytes() {
      return instance.getObservedAtBytes();
    }
    /**
     * <code>string observedAt = 4;</code>
     * @param value The observedAt to set.
     * @return This builder for chaining.
     */
    public Builder setObservedAt(
        java.lang.String value) {
      copyOnWrite();
      instance.setObservedAt(value);
      return this;
    }
    /**
     * <code>string observedAt = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearObservedAt() {
      copyOnWrite();
      instance.clearObservedAt();
      return this;
    }
    /**
     * <code>string observedAt = 4;</code>
     * @param value The bytes for observedAt to set.
     * @return This builder for chaining.
     */
    public Builder setObservedAtBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setObservedAtBytes(value);
      return this;
    }

    /**
     * <code>bool isSale = 5;</code>
     * @return The isSale.
     */
    @java.lang.Override
    public boolean getIsSale() {
      return instance.getIsSale();
    }
    /**
     * <code>bool isSale = 5;</code>
     * @param value The isSale to set.
     * @return This builder for chaining.
     */
    public Builder setIsSale(boolean value) {
      copyOnWrite();
      instance.setIsSale(value);
      return this;
    }
    /**
     * <code>bool isSale = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearIsSale() {
      copyOnWrite();
      instance.clearIsSale();
      return this;
    }

    /**
     * <code>optional .grocery.database.SaleInfo saleInfo = 6;</code>
     */
    @java.lang.Override
    public boolean hasSaleInfo() {
      return instance.hasSaleInfo();
    }
    /**
     * <code>optional .grocery.database.SaleInfo saleInfo = 6;</code>
     */
    @java.lang.Override
    public com.example.grocerystoreorganizer.grpc.SaleInfo getSaleInfo() {
      return instance.getSaleInfo();
    }
    /**
     * <code>optional .grocery.database.SaleInfo saleInfo = 6;</code>
     */
    public Builder setSaleInfo(com.example.grocerystoreorganizer.grpc.SaleInfo value) {
      copyOnWrite();
      instance.setSaleInfo(value);
      return this;
      }
    /**
     * <code>optional .grocery.database.SaleInfo saleInfo = 6;</code>
     */
    public Builder setSaleInfo(
        com.example.grocerystoreorganizer.grpc.SaleInfo.Builder builderForValue) {
      copyOnWrite();
      instance.setSaleInfo(builderForValue.build());
      return this;
    }
    /**
     * <code>optional .grocery.database.SaleInfo saleInfo = 6;</code>
     */
    public Builder mergeSaleInfo(com.example.grocerystoreorganizer.grpc.SaleInfo value) {
      copyOnWrite();
      instance.mergeSaleInfo(value);
      return this;
    }
    /**
     * <code>optional .grocery.database.SaleInfo saleInfo = 6;</code>
     */
    public Builder clearSaleInfo() {  copyOnWrite();
      instance.clearSaleInfo();
      return this;
    }

    /**
     * <code>optional bytes trainingImageJpeg = 7;</code>
     * @return Whether the trainingImageJpeg field is set.
     */
    @java.lang.Override
    public boolean hasTrainingImageJpeg() {
      return instance.hasTrainingImageJpeg();
    }
    /**
     * <code>optional bytes trainingImageJpeg = 7;</code>
     * @return The trainingImageJpeg.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getTrainingImageJpeg() {
      return instance.getTrainingImageJpeg();
    }
    /**
     * <code>optional bytes trainingImageJpeg = 7;</code>
     * @param value The trainingImageJpeg to set.
     * @return This builder for chaining.
     */
    public Builder setTrainingImageJpeg(com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setTrainingImageJpeg(value);
      return this;
    }
    /**
     * <code>optional bytes trainingImageJpeg = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearTrainingImageJpeg() {
      copyOnWrite();
      instance.clearTrainingImageJpeg();
      return this;
    }

    /**
     * <code>optional string trainingImageFilename = 8;</code>
     * @return Whether the trainingImageFilename field is set.
     */
    @java.lang.Override
    public boolean hasTrainingImageFilename() {
      return instance.hasTrainingImageFilename();
    }
    /**
     * <code>optional string trainingImageFilename = 8;</code>
     * @return The trainingImageFilename.
     */
    @java.lang.Override
    public java.lang.String getTrainingImageFilename() {
      return instance.getTrainingImageFilename();
    }
    /**
     * <code>optional string trainingImageFilename = 8;</code>
     * @return The bytes for trainingImageFilename.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTrainingImageFilenameBytes() {
      return instance.getTrainingImageFilenameBytes();
    }
    /**
     * <code>optional string trainingImageFilename = 8;</code>
     * @param value The trainingImageFilename to set.
     * @return This builder for chaining.
     */
    public Builder setTrainingImageFilename(
        java.lang.String value) {
      copyOnWrite();
      instance.setTrainingImageFilename(value);
      return this;
    }
    /**
     * <code>optional string trainingImageFilename = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearTrainingImageFilename() {
      copyOnWrite();
      instance.clearTrainingImageFilename();
      return this;
    }
    /**
     * <code>optional string trainingImageFilename = 8;</code>
     * @param value The bytes for trainingImageFilename to set.
     * @return This builder for chaining.
     */
    public Builder setTrainingImageFilenameBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setTrainingImageFilenameBytes(value);
      return this;
    }

    /**
     * <code>optional bool trainingImageUpcPresent = 9;</code>
     * @return Whether the trainingImageUpcPresent field is set.
     */
    @java.lang.Override
    public boolean hasTrainingImageUpcPresent() {
      return instance.hasTrainingImageUpcPresent();
    }
    /**
     * <code>optional bool trainingImageUpcPresent = 9;</code>
     * @return The trainingImageUpcPresent.
     */
    @java.lang.Override
    public boolean getTrainingImageUpcPresent() {
      return instance.getTrainingImageUpcPresent();
    }
    /**
     * <code>optional bool trainingImageUpcPresent = 9;</code>
     * @param value The trainingImageUpcPresent to set.
     * @return This builder for chaining.
     */
    public Builder setTrainingImageUpcPresent(boolean value) {
      copyOnWrite();
      instance.setTrainingImageUpcPresent(value);
      return this;
    }
    /**
     * <code>optional bool trainingImageUpcPresent = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearTrainingImageUpcPresent() {
      copyOnWrite();
      instance.clearTrainingImageUpcPresent();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:grocery.database.PriceObservationRequest)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.example.grocerystoreorganizer.grpc.PriceObservationRequest();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "bitField0_",
            "store_",
            "upc_",
            "priceTotal_",
            "observedAt_",
            "isSale_",
            "saleInfo_",
            "trainingImageJpeg_",
            "trainingImageFilename_",
            "trainingImageUpcPresent_",
          };
          java.lang.String info =
              "\u0000\t\u0000\u0001\u0001\t\t\u0000\u0000\u0000\u0001\t\u0002\t\u0003\u0000\u0004" +
              "\u0208\u0005\u0007\u0006\u1009\u0000\u0007\u100a\u0001\b\u1208\u0002\t\u1007\u0003" +
              "";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<com.example.grocerystoreorganizer.grpc.PriceObservationRequest> parser = PARSER;
        if (parser == null) {
          synchronized (com.example.grocerystoreorganizer.grpc.PriceObservationRequest.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<com.example.grocerystoreorganizer.grpc.PriceObservationRequest>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:grocery.database.PriceObservationRequest)
  private static final com.example.grocerystoreorganizer.grpc.PriceObservationRequest DEFAULT_INSTANCE;
  static {
    PriceObservationRequest defaultInstance = new PriceObservationRequest();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      PriceObservationRequest.class, defaultInstance);
  }

  public static com.example.grocerystoreorganizer.grpc.PriceObservationRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<PriceObservationRequest> PARSER;

  public static com.google.protobuf.Parser<PriceObservationRequest> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

