// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: db_service.proto

package com.example.grocerystoreorganizer.grpc;

public interface PriceObservationRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:grocery.database.PriceObservationRequest)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>.grocery.database.StoreInfo store = 1;</code>
   * @return Whether the store field is set.
   */
  boolean hasStore();
  /**
   * <code>.grocery.database.StoreInfo store = 1;</code>
   * @return The store.
   */
  com.example.grocerystoreorganizer.grpc.StoreInfo getStore();

  /**
   * <code>.grocery.database.UpcInfo upc = 2;</code>
   * @return Whether the upc field is set.
   */
  boolean hasUpc();
  /**
   * <code>.grocery.database.UpcInfo upc = 2;</code>
   * @return The upc.
   */
  com.example.grocerystoreorganizer.grpc.UpcInfo getUpc();

  /**
   * <code>double priceTotal = 3;</code>
   * @return The priceTotal.
   */
  double getPriceTotal();

  /**
   * <code>string observedAt = 4;</code>
   * @return The observedAt.
   */
  java.lang.String getObservedAt();
  /**
   * <code>string observedAt = 4;</code>
   * @return The bytes for observedAt.
   */
  com.google.protobuf.ByteString
      getObservedAtBytes();

  /**
   * <code>bool isSale = 5;</code>
   * @return The isSale.
   */
  boolean getIsSale();

  /**
   * <code>optional .grocery.database.SaleInfo saleInfo = 6;</code>
   * @return Whether the saleInfo field is set.
   */
  boolean hasSaleInfo();
  /**
   * <code>optional .grocery.database.SaleInfo saleInfo = 6;</code>
   * @return The saleInfo.
   */
  com.example.grocerystoreorganizer.grpc.SaleInfo getSaleInfo();
}
