// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: db_service.proto

package com.example.grocerystoreorganizer.grpc;

public interface ProductInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:grocery.database.ProductInfo)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>uint32 productId = 1;</code>
   * @return The productId.
   */
  int getProductId();

  /**
   * <code>string productName = 2;</code>
   * @return The productName.
   */
  java.lang.String getProductName();
  /**
   * <code>string productName = 2;</code>
   * @return The bytes for productName.
   */
  com.google.protobuf.ByteString
      getProductNameBytes();

  /**
   * <code>optional string productCategory = 3;</code>
   * @return Whether the productCategory field is set.
   */
  boolean hasProductCategory();
  /**
   * <code>optional string productCategory = 3;</code>
   * @return The productCategory.
   */
  java.lang.String getProductCategory();
  /**
   * <code>optional string productCategory = 3;</code>
   * @return The bytes for productCategory.
   */
  com.google.protobuf.ByteString
      getProductCategoryBytes();

  /**
   * <code>string updatedAt = 4;</code>
   * @return The updatedAt.
   */
  java.lang.String getUpdatedAt();
  /**
   * <code>string updatedAt = 4;</code>
   * @return The bytes for updatedAt.
   */
  com.google.protobuf.ByteString
      getUpdatedAtBytes();
}
