// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: db_service.proto

package com.example.grocerystoreorganizer.grpc;

/**
 * Protobuf enum {@code grocery.database.ProductUnit}
 */
public enum ProductUnit
    implements com.google.protobuf.Internal.EnumLite {
  /**
   * <code>OZ = 0;</code>
   */
  OZ(0),
  /**
   * <code>LB = 1;</code>
   */
  LB(1),
  /**
   * <code>EA = 2;</code>
   */
  EA(2),
  /**
   * <code>KG = 3;</code>
   */
  KG(3),
  /**
   * <code>G = 4;</code>
   */
  G(4),
  /**
   * <code>LIT = 5;</code>
   */
  LIT(5),
  /**
   * <code>ML = 6;</code>
   */
  ML(6),
  /**
   * <code>GAL = 7;</code>
   */
  GAL(7),
  /**
   * <code>QT = 8;</code>
   */
  QT(8),
  /**
   * <code>PT = 9;</code>
   */
  PT(9),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>OZ = 0;</code>
   */
  public static final int OZ_VALUE = 0;
  /**
   * <code>LB = 1;</code>
   */
  public static final int LB_VALUE = 1;
  /**
   * <code>EA = 2;</code>
   */
  public static final int EA_VALUE = 2;
  /**
   * <code>KG = 3;</code>
   */
  public static final int KG_VALUE = 3;
  /**
   * <code>G = 4;</code>
   */
  public static final int G_VALUE = 4;
  /**
   * <code>LIT = 5;</code>
   */
  public static final int LIT_VALUE = 5;
  /**
   * <code>ML = 6;</code>
   */
  public static final int ML_VALUE = 6;
  /**
   * <code>GAL = 7;</code>
   */
  public static final int GAL_VALUE = 7;
  /**
   * <code>QT = 8;</code>
   */
  public static final int QT_VALUE = 8;
  /**
   * <code>PT = 9;</code>
   */
  public static final int PT_VALUE = 9;


  @java.lang.Override
  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The number of the enum to look for.
   * @return The enum associated with the given number.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static ProductUnit valueOf(int value) {
    return forNumber(value);
  }

  public static ProductUnit forNumber(int value) {
    switch (value) {
      case 0: return OZ;
      case 1: return LB;
      case 2: return EA;
      case 3: return KG;
      case 4: return G;
      case 5: return LIT;
      case 6: return ML;
      case 7: return GAL;
      case 8: return QT;
      case 9: return PT;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<ProductUnit>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      ProductUnit> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<ProductUnit>() {
          @java.lang.Override
          public ProductUnit findValueByNumber(int number) {
            return ProductUnit.forNumber(number);
          }
        };

  public static com.google.protobuf.Internal.EnumVerifier 
      internalGetVerifier() {
    return ProductUnitVerifier.INSTANCE;
  }

  private static final class ProductUnitVerifier implements 
       com.google.protobuf.Internal.EnumVerifier { 
          static final com.google.protobuf.Internal.EnumVerifier           INSTANCE = new ProductUnitVerifier();
          @java.lang.Override
          public boolean isInRange(int number) {
            return ProductUnit.forNumber(number) != null;
          }
        };

  private final int value;

  private ProductUnit(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:grocery.database.ProductUnit)
}

