// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: db_service.proto

package com.example.grocerystoreorganizer.grpc;

/**
 * Protobuf type {@code grocery.database.ProductInfo}
 */
public  final class ProductInfo extends
    com.google.protobuf.GeneratedMessageLite<
        ProductInfo, ProductInfo.Builder> implements
    // @@protoc_insertion_point(message_implements:grocery.database.ProductInfo)
    ProductInfoOrBuilder {
  private ProductInfo() {
    productName_ = "";
    productCategory_ = "";
    updatedAt_ = "";
  }
  private int bitField0_;
  public static final int PRODUCTID_FIELD_NUMBER = 1;
  private int productId_;
  /**
   * <code>uint32 productId = 1;</code>
   * @return The productId.
   */
  @java.lang.Override
  public int getProductId() {
    return productId_;
  }
  /**
   * <code>uint32 productId = 1;</code>
   * @param value The productId to set.
   */
  private void setProductId(int value) {
    
    productId_ = value;
  }
  /**
   * <code>uint32 productId = 1;</code>
   */
  private void clearProductId() {
    
    productId_ = 0;
  }

  public static final int PRODUCTNAME_FIELD_NUMBER = 2;
  private java.lang.String productName_;
  /**
   * <code>string productName = 2;</code>
   * @return The productName.
   */
  @java.lang.Override
  public java.lang.String getProductName() {
    return productName_;
  }
  /**
   * <code>string productName = 2;</code>
   * @return The bytes for productName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getProductNameBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(productName_);
  }
  /**
   * <code>string productName = 2;</code>
   * @param value The productName to set.
   */
  private void setProductName(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    productName_ = value;
  }
  /**
   * <code>string productName = 2;</code>
   */
  private void clearProductName() {
    
    productName_ = getDefaultInstance().getProductName();
  }
  /**
   * <code>string productName = 2;</code>
   * @param value The bytes for productName to set.
   */
  private void setProductNameBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    productName_ = value.toStringUtf8();
    
  }

  public static final int PRODUCTCATEGORY_FIELD_NUMBER = 3;
  private java.lang.String productCategory_;
  /**
   * <code>optional string productCategory = 3;</code>
   * @return Whether the productCategory field is set.
   */
  @java.lang.Override
  public boolean hasProductCategory() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>optional string productCategory = 3;</code>
   * @return The productCategory.
   */
  @java.lang.Override
  public java.lang.String getProductCategory() {
    return productCategory_;
  }
  /**
   * <code>optional string productCategory = 3;</code>
   * @return The bytes for productCategory.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getProductCategoryBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(productCategory_);
  }
  /**
   * <code>optional string productCategory = 3;</code>
   * @param value The productCategory to set.
   */
  private void setProductCategory(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  bitField0_ |= 0x00000001;
    productCategory_ = value;
  }
  /**
   * <code>optional string productCategory = 3;</code>
   */
  private void clearProductCategory() {
    bitField0_ = (bitField0_ & ~0x00000001);
    productCategory_ = getDefaultInstance().getProductCategory();
  }
  /**
   * <code>optional string productCategory = 3;</code>
   * @param value The bytes for productCategory to set.
   */
  private void setProductCategoryBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    productCategory_ = value.toStringUtf8();
    bitField0_ |= 0x00000001;
  }

  public static final int UPDATEDAT_FIELD_NUMBER = 4;
  private java.lang.String updatedAt_;
  /**
   * <code>string updatedAt = 4;</code>
   * @return The updatedAt.
   */
  @java.lang.Override
  public java.lang.String getUpdatedAt() {
    return updatedAt_;
  }
  /**
   * <code>string updatedAt = 4;</code>
   * @return The bytes for updatedAt.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getUpdatedAtBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(updatedAt_);
  }
  /**
   * <code>string updatedAt = 4;</code>
   * @param value The updatedAt to set.
   */
  private void setUpdatedAt(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    updatedAt_ = value;
  }
  /**
   * <code>string updatedAt = 4;</code>
   */
  private void clearUpdatedAt() {
    
    updatedAt_ = getDefaultInstance().getUpdatedAt();
  }
  /**
   * <code>string updatedAt = 4;</code>
   * @param value The bytes for updatedAt to set.
   */
  private void setUpdatedAtBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    updatedAt_ = value.toStringUtf8();
    
  }

  public static com.example.grocerystoreorganizer.grpc.ProductInfo parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.example.grocerystoreorganizer.grpc.ProductInfo parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.example.grocerystoreorganizer.grpc.ProductInfo parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.example.grocerystoreorganizer.grpc.ProductInfo parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.example.grocerystoreorganizer.grpc.ProductInfo parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.example.grocerystoreorganizer.grpc.ProductInfo parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.example.grocerystoreorganizer.grpc.ProductInfo parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.example.grocerystoreorganizer.grpc.ProductInfo parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.example.grocerystoreorganizer.grpc.ProductInfo parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static com.example.grocerystoreorganizer.grpc.ProductInfo parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.example.grocerystoreorganizer.grpc.ProductInfo parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.example.grocerystoreorganizer.grpc.ProductInfo parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(com.example.grocerystoreorganizer.grpc.ProductInfo prototype) {
    return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code grocery.database.ProductInfo}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.example.grocerystoreorganizer.grpc.ProductInfo, Builder> implements
      // @@protoc_insertion_point(builder_implements:grocery.database.ProductInfo)
      com.example.grocerystoreorganizer.grpc.ProductInfoOrBuilder {
    // Construct using com.example.grocerystoreorganizer.grpc.ProductInfo.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>uint32 productId = 1;</code>
     * @return The productId.
     */
    @java.lang.Override
    public int getProductId() {
      return instance.getProductId();
    }
    /**
     * <code>uint32 productId = 1;</code>
     * @param value The productId to set.
     * @return This builder for chaining.
     */
    public Builder setProductId(int value) {
      copyOnWrite();
      instance.setProductId(value);
      return this;
    }
    /**
     * <code>uint32 productId = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearProductId() {
      copyOnWrite();
      instance.clearProductId();
      return this;
    }

    /**
     * <code>string productName = 2;</code>
     * @return The productName.
     */
    @java.lang.Override
    public java.lang.String getProductName() {
      return instance.getProductName();
    }
    /**
     * <code>string productName = 2;</code>
     * @return The bytes for productName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getProductNameBytes() {
      return instance.getProductNameBytes();
    }
    /**
     * <code>string productName = 2;</code>
     * @param value The productName to set.
     * @return This builder for chaining.
     */
    public Builder setProductName(
        java.lang.String value) {
      copyOnWrite();
      instance.setProductName(value);
      return this;
    }
    /**
     * <code>string productName = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearProductName() {
      copyOnWrite();
      instance.clearProductName();
      return this;
    }
    /**
     * <code>string productName = 2;</code>
     * @param value The bytes for productName to set.
     * @return This builder for chaining.
     */
    public Builder setProductNameBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setProductNameBytes(value);
      return this;
    }

    /**
     * <code>optional string productCategory = 3;</code>
     * @return Whether the productCategory field is set.
     */
    @java.lang.Override
    public boolean hasProductCategory() {
      return instance.hasProductCategory();
    }
    /**
     * <code>optional string productCategory = 3;</code>
     * @return The productCategory.
     */
    @java.lang.Override
    public java.lang.String getProductCategory() {
      return instance.getProductCategory();
    }
    /**
     * <code>optional string productCategory = 3;</code>
     * @return The bytes for productCategory.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getProductCategoryBytes() {
      return instance.getProductCategoryBytes();
    }
    /**
     * <code>optional string productCategory = 3;</code>
     * @param value The productCategory to set.
     * @return This builder for chaining.
     */
    public Builder setProductCategory(
        java.lang.String value) {
      copyOnWrite();
      instance.setProductCategory(value);
      return this;
    }
    /**
     * <code>optional string productCategory = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearProductCategory() {
      copyOnWrite();
      instance.clearProductCategory();
      return this;
    }
    /**
     * <code>optional string productCategory = 3;</code>
     * @param value The bytes for productCategory to set.
     * @return This builder for chaining.
     */
    public Builder setProductCategoryBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setProductCategoryBytes(value);
      return this;
    }

    /**
     * <code>string updatedAt = 4;</code>
     * @return The updatedAt.
     */
    @java.lang.Override
    public java.lang.String getUpdatedAt() {
      return instance.getUpdatedAt();
    }
    /**
     * <code>string updatedAt = 4;</code>
     * @return The bytes for updatedAt.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getUpdatedAtBytes() {
      return instance.getUpdatedAtBytes();
    }
    /**
     * <code>string updatedAt = 4;</code>
     * @param value The updatedAt to set.
     * @return This builder for chaining.
     */
    public Builder setUpdatedAt(
        java.lang.String value) {
      copyOnWrite();
      instance.setUpdatedAt(value);
      return this;
    }
    /**
     * <code>string updatedAt = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearUpdatedAt() {
      copyOnWrite();
      instance.clearUpdatedAt();
      return this;
    }
    /**
     * <code>string updatedAt = 4;</code>
     * @param value The bytes for updatedAt to set.
     * @return This builder for chaining.
     */
    public Builder setUpdatedAtBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setUpdatedAtBytes(value);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:grocery.database.ProductInfo)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.example.grocerystoreorganizer.grpc.ProductInfo();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "bitField0_",
            "productId_",
            "productName_",
            "productCategory_",
            "updatedAt_",
          };
          java.lang.String info =
              "\u0000\u0004\u0000\u0001\u0001\u0004\u0004\u0000\u0000\u0000\u0001\u000b\u0002\u0208" +
              "\u0003\u1208\u0000\u0004\u0208";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<com.example.grocerystoreorganizer.grpc.ProductInfo> parser = PARSER;
        if (parser == null) {
          synchronized (com.example.grocerystoreorganizer.grpc.ProductInfo.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<com.example.grocerystoreorganizer.grpc.ProductInfo>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:grocery.database.ProductInfo)
  private static final com.example.grocerystoreorganizer.grpc.ProductInfo DEFAULT_INSTANCE;
  static {
    ProductInfo defaultInstance = new ProductInfo();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      ProductInfo.class, defaultInstance);
  }

  public static com.example.grocerystoreorganizer.grpc.ProductInfo getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<ProductInfo> PARSER;

  public static com.google.protobuf.Parser<ProductInfo> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

