// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: db_service.proto

package com.example.grocerystoreorganizer.grpc;

/**
 * Protobuf type {@code grocery.database.SaleInfo}
 */
public  final class SaleInfo extends
    com.google.protobuf.GeneratedMessageLite<
        SaleInfo, SaleInfo.Builder> implements
    // @@protoc_insertion_point(message_implements:grocery.database.SaleInfo)
    SaleInfoOrBuilder {
  private SaleInfo() {
    startDate_ = "";
    expirationDate_ = "";
  }
  private int bitField0_;
  public static final int STARTDATE_FIELD_NUMBER = 1;
  private java.lang.String startDate_;
  /**
   * <code>string startDate = 1;</code>
   * @return The startDate.
   */
  @java.lang.Override
  public java.lang.String getStartDate() {
    return startDate_;
  }
  /**
   * <code>string startDate = 1;</code>
   * @return The bytes for startDate.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getStartDateBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(startDate_);
  }
  /**
   * <code>string startDate = 1;</code>
   * @param value The startDate to set.
   */
  private void setStartDate(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    startDate_ = value;
  }
  /**
   * <code>string startDate = 1;</code>
   */
  private void clearStartDate() {
    
    startDate_ = getDefaultInstance().getStartDate();
  }
  /**
   * <code>string startDate = 1;</code>
   * @param value The bytes for startDate to set.
   */
  private void setStartDateBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    startDate_ = value.toStringUtf8();
    
  }

  public static final int EXPIRATIONDATE_FIELD_NUMBER = 2;
  private java.lang.String expirationDate_;
  /**
   * <code>optional string expirationDate = 2;</code>
   * @return Whether the expirationDate field is set.
   */
  @java.lang.Override
  public boolean hasExpirationDate() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>optional string expirationDate = 2;</code>
   * @return The expirationDate.
   */
  @java.lang.Override
  public java.lang.String getExpirationDate() {
    return expirationDate_;
  }
  /**
   * <code>optional string expirationDate = 2;</code>
   * @return The bytes for expirationDate.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getExpirationDateBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(expirationDate_);
  }
  /**
   * <code>optional string expirationDate = 2;</code>
   * @param value The expirationDate to set.
   */
  private void setExpirationDate(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  bitField0_ |= 0x00000001;
    expirationDate_ = value;
  }
  /**
   * <code>optional string expirationDate = 2;</code>
   */
  private void clearExpirationDate() {
    bitField0_ = (bitField0_ & ~0x00000001);
    expirationDate_ = getDefaultInstance().getExpirationDate();
  }
  /**
   * <code>optional string expirationDate = 2;</code>
   * @param value The bytes for expirationDate to set.
   */
  private void setExpirationDateBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    expirationDate_ = value.toStringUtf8();
    bitField0_ |= 0x00000001;
  }

  public static final int MINIMUMQUANTITY_FIELD_NUMBER = 3;
  private int minimumQuantity_;
  /**
   * <code>optional int32 minimumQuantity = 3;</code>
   * @return Whether the minimumQuantity field is set.
   */
  @java.lang.Override
  public boolean hasMinimumQuantity() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>optional int32 minimumQuantity = 3;</code>
   * @return The minimumQuantity.
   */
  @java.lang.Override
  public int getMinimumQuantity() {
    return minimumQuantity_;
  }
  /**
   * <code>optional int32 minimumQuantity = 3;</code>
   * @param value The minimumQuantity to set.
   */
  private void setMinimumQuantity(int value) {
    bitField0_ |= 0x00000002;
    minimumQuantity_ = value;
  }
  /**
   * <code>optional int32 minimumQuantity = 3;</code>
   */
  private void clearMinimumQuantity() {
    bitField0_ = (bitField0_ & ~0x00000002);
    minimumQuantity_ = 0;
  }

  public static final int LIMITQUANTITY_FIELD_NUMBER = 4;
  private int limitQuantity_;
  /**
   * <code>optional int32 limitQuantity = 4;</code>
   * @return Whether the limitQuantity field is set.
   */
  @java.lang.Override
  public boolean hasLimitQuantity() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <code>optional int32 limitQuantity = 4;</code>
   * @return The limitQuantity.
   */
  @java.lang.Override
  public int getLimitQuantity() {
    return limitQuantity_;
  }
  /**
   * <code>optional int32 limitQuantity = 4;</code>
   * @param value The limitQuantity to set.
   */
  private void setLimitQuantity(int value) {
    bitField0_ |= 0x00000004;
    limitQuantity_ = value;
  }
  /**
   * <code>optional int32 limitQuantity = 4;</code>
   */
  private void clearLimitQuantity() {
    bitField0_ = (bitField0_ & ~0x00000004);
    limitQuantity_ = 0;
  }

  public static com.example.grocerystoreorganizer.grpc.SaleInfo parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.example.grocerystoreorganizer.grpc.SaleInfo parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.example.grocerystoreorganizer.grpc.SaleInfo parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.example.grocerystoreorganizer.grpc.SaleInfo parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.example.grocerystoreorganizer.grpc.SaleInfo parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.example.grocerystoreorganizer.grpc.SaleInfo parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.example.grocerystoreorganizer.grpc.SaleInfo parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.example.grocerystoreorganizer.grpc.SaleInfo parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.example.grocerystoreorganizer.grpc.SaleInfo parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static com.example.grocerystoreorganizer.grpc.SaleInfo parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.example.grocerystoreorganizer.grpc.SaleInfo parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.example.grocerystoreorganizer.grpc.SaleInfo parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(com.example.grocerystoreorganizer.grpc.SaleInfo prototype) {
    return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code grocery.database.SaleInfo}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.example.grocerystoreorganizer.grpc.SaleInfo, Builder> implements
      // @@protoc_insertion_point(builder_implements:grocery.database.SaleInfo)
      com.example.grocerystoreorganizer.grpc.SaleInfoOrBuilder {
    // Construct using com.example.grocerystoreorganizer.grpc.SaleInfo.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>string startDate = 1;</code>
     * @return The startDate.
     */
    @java.lang.Override
    public java.lang.String getStartDate() {
      return instance.getStartDate();
    }
    /**
     * <code>string startDate = 1;</code>
     * @return The bytes for startDate.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getStartDateBytes() {
      return instance.getStartDateBytes();
    }
    /**
     * <code>string startDate = 1;</code>
     * @param value The startDate to set.
     * @return This builder for chaining.
     */
    public Builder setStartDate(
        java.lang.String value) {
      copyOnWrite();
      instance.setStartDate(value);
      return this;
    }
    /**
     * <code>string startDate = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearStartDate() {
      copyOnWrite();
      instance.clearStartDate();
      return this;
    }
    /**
     * <code>string startDate = 1;</code>
     * @param value The bytes for startDate to set.
     * @return This builder for chaining.
     */
    public Builder setStartDateBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setStartDateBytes(value);
      return this;
    }

    /**
     * <code>optional string expirationDate = 2;</code>
     * @return Whether the expirationDate field is set.
     */
    @java.lang.Override
    public boolean hasExpirationDate() {
      return instance.hasExpirationDate();
    }
    /**
     * <code>optional string expirationDate = 2;</code>
     * @return The expirationDate.
     */
    @java.lang.Override
    public java.lang.String getExpirationDate() {
      return instance.getExpirationDate();
    }
    /**
     * <code>optional string expirationDate = 2;</code>
     * @return The bytes for expirationDate.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getExpirationDateBytes() {
      return instance.getExpirationDateBytes();
    }
    /**
     * <code>optional string expirationDate = 2;</code>
     * @param value The expirationDate to set.
     * @return This builder for chaining.
     */
    public Builder setExpirationDate(
        java.lang.String value) {
      copyOnWrite();
      instance.setExpirationDate(value);
      return this;
    }
    /**
     * <code>optional string expirationDate = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearExpirationDate() {
      copyOnWrite();
      instance.clearExpirationDate();
      return this;
    }
    /**
     * <code>optional string expirationDate = 2;</code>
     * @param value The bytes for expirationDate to set.
     * @return This builder for chaining.
     */
    public Builder setExpirationDateBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setExpirationDateBytes(value);
      return this;
    }

    /**
     * <code>optional int32 minimumQuantity = 3;</code>
     * @return Whether the minimumQuantity field is set.
     */
    @java.lang.Override
    public boolean hasMinimumQuantity() {
      return instance.hasMinimumQuantity();
    }
    /**
     * <code>optional int32 minimumQuantity = 3;</code>
     * @return The minimumQuantity.
     */
    @java.lang.Override
    public int getMinimumQuantity() {
      return instance.getMinimumQuantity();
    }
    /**
     * <code>optional int32 minimumQuantity = 3;</code>
     * @param value The minimumQuantity to set.
     * @return This builder for chaining.
     */
    public Builder setMinimumQuantity(int value) {
      copyOnWrite();
      instance.setMinimumQuantity(value);
      return this;
    }
    /**
     * <code>optional int32 minimumQuantity = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearMinimumQuantity() {
      copyOnWrite();
      instance.clearMinimumQuantity();
      return this;
    }

    /**
     * <code>optional int32 limitQuantity = 4;</code>
     * @return Whether the limitQuantity field is set.
     */
    @java.lang.Override
    public boolean hasLimitQuantity() {
      return instance.hasLimitQuantity();
    }
    /**
     * <code>optional int32 limitQuantity = 4;</code>
     * @return The limitQuantity.
     */
    @java.lang.Override
    public int getLimitQuantity() {
      return instance.getLimitQuantity();
    }
    /**
     * <code>optional int32 limitQuantity = 4;</code>
     * @param value The limitQuantity to set.
     * @return This builder for chaining.
     */
    public Builder setLimitQuantity(int value) {
      copyOnWrite();
      instance.setLimitQuantity(value);
      return this;
    }
    /**
     * <code>optional int32 limitQuantity = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearLimitQuantity() {
      copyOnWrite();
      instance.clearLimitQuantity();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:grocery.database.SaleInfo)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.example.grocerystoreorganizer.grpc.SaleInfo();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "bitField0_",
            "startDate_",
            "expirationDate_",
            "minimumQuantity_",
            "limitQuantity_",
          };
          java.lang.String info =
              "\u0000\u0004\u0000\u0001\u0001\u0004\u0004\u0000\u0000\u0000\u0001\u0208\u0002\u1208" +
              "\u0000\u0003\u1004\u0001\u0004\u1004\u0002";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<com.example.grocerystoreorganizer.grpc.SaleInfo> parser = PARSER;
        if (parser == null) {
          synchronized (com.example.grocerystoreorganizer.grpc.SaleInfo.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<com.example.grocerystoreorganizer.grpc.SaleInfo>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:grocery.database.SaleInfo)
  private static final com.example.grocerystoreorganizer.grpc.SaleInfo DEFAULT_INSTANCE;
  static {
    SaleInfo defaultInstance = new SaleInfo();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      SaleInfo.class, defaultInstance);
  }

  public static com.example.grocerystoreorganizer.grpc.SaleInfo getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<SaleInfo> PARSER;

  public static com.google.protobuf.Parser<SaleInfo> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

