// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: db_service.proto

package com.example.grocerystoreorganizer.grpc;

public interface SaleInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:grocery.database.SaleInfo)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>string startDate = 1;</code>
   * @return The startDate.
   */
  java.lang.String getStartDate();
  /**
   * <code>string startDate = 1;</code>
   * @return The bytes for startDate.
   */
  com.google.protobuf.ByteString
      getStartDateBytes();

  /**
   * <code>optional string expirationDate = 2;</code>
   * @return Whether the expirationDate field is set.
   */
  boolean hasExpirationDate();
  /**
   * <code>optional string expirationDate = 2;</code>
   * @return The expirationDate.
   */
  java.lang.String getExpirationDate();
  /**
   * <code>optional string expirationDate = 2;</code>
   * @return The bytes for expirationDate.
   */
  com.google.protobuf.ByteString
      getExpirationDateBytes();

  /**
   * <code>optional int32 minimumQuantity = 3;</code>
   * @return Whether the minimumQuantity field is set.
   */
  boolean hasMinimumQuantity();
  /**
   * <code>optional int32 minimumQuantity = 3;</code>
   * @return The minimumQuantity.
   */
  int getMinimumQuantity();

  /**
   * <code>optional int32 limitQuantity = 4;</code>
   * @return Whether the limitQuantity field is set.
   */
  boolean hasLimitQuantity();
  /**
   * <code>optional int32 limitQuantity = 4;</code>
   * @return The limitQuantity.
   */
  int getLimitQuantity();
}
