// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: db_service.proto

package com.example.grocerystoreorganizer.grpc;

/**
 * Protobuf type {@code grocery.database.StoreInfo}
 */
public  final class StoreInfo extends
    com.google.protobuf.GeneratedMessageLite<
        StoreInfo, StoreInfo.Builder> implements
    // @@protoc_insertion_point(message_implements:grocery.database.StoreInfo)
    StoreInfoOrBuilder {
  private StoreInfo() {
    storeAddress_ = "";
    storeName_ = "";
  }
  private int bitField0_;
  public static final int STOREADDRESS_FIELD_NUMBER = 1;
  private java.lang.String storeAddress_;
  /**
   * <code>string storeAddress = 1;</code>
   * @return The storeAddress.
   */
  @java.lang.Override
  public java.lang.String getStoreAddress() {
    return storeAddress_;
  }
  /**
   * <code>string storeAddress = 1;</code>
   * @return The bytes for storeAddress.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getStoreAddressBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(storeAddress_);
  }
  /**
   * <code>string storeAddress = 1;</code>
   * @param value The storeAddress to set.
   */
  private void setStoreAddress(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    storeAddress_ = value;
  }
  /**
   * <code>string storeAddress = 1;</code>
   */
  private void clearStoreAddress() {
    
    storeAddress_ = getDefaultInstance().getStoreAddress();
  }
  /**
   * <code>string storeAddress = 1;</code>
   * @param value The bytes for storeAddress to set.
   */
  private void setStoreAddressBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    storeAddress_ = value.toStringUtf8();
    
  }

  public static final int LOCATION_FIELD_NUMBER = 2;
  private com.example.grocerystoreorganizer.grpc.Coordinate location_;
  /**
   * <code>.grocery.database.Coordinate location = 2;</code>
   */
  @java.lang.Override
  public boolean hasLocation() {
    return location_ != null;
  }
  /**
   * <code>.grocery.database.Coordinate location = 2;</code>
   */
  @java.lang.Override
  public com.example.grocerystoreorganizer.grpc.Coordinate getLocation() {
    return location_ == null ? com.example.grocerystoreorganizer.grpc.Coordinate.getDefaultInstance() : location_;
  }
  /**
   * <code>.grocery.database.Coordinate location = 2;</code>
   */
  private void setLocation(com.example.grocerystoreorganizer.grpc.Coordinate value) {
    value.getClass();
  location_ = value;
    
    }
  /**
   * <code>.grocery.database.Coordinate location = 2;</code>
   */
  @java.lang.SuppressWarnings({"ReferenceEquality"})
  private void mergeLocation(com.example.grocerystoreorganizer.grpc.Coordinate value) {
    value.getClass();
  if (location_ != null &&
        location_ != com.example.grocerystoreorganizer.grpc.Coordinate.getDefaultInstance()) {
      location_ =
        com.example.grocerystoreorganizer.grpc.Coordinate.newBuilder(location_).mergeFrom(value).buildPartial();
    } else {
      location_ = value;
    }
    
  }
  /**
   * <code>.grocery.database.Coordinate location = 2;</code>
   */
  private void clearLocation() {  location_ = null;
    
  }

  public static final int STORENAME_FIELD_NUMBER = 3;
  private java.lang.String storeName_;
  /**
   * <code>optional string storeName = 3;</code>
   * @return Whether the storeName field is set.
   */
  @java.lang.Override
  public boolean hasStoreName() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>optional string storeName = 3;</code>
   * @return The storeName.
   */
  @java.lang.Override
  public java.lang.String getStoreName() {
    return storeName_;
  }
  /**
   * <code>optional string storeName = 3;</code>
   * @return The bytes for storeName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getStoreNameBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(storeName_);
  }
  /**
   * <code>optional string storeName = 3;</code>
   * @param value The storeName to set.
   */
  private void setStoreName(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  bitField0_ |= 0x00000001;
    storeName_ = value;
  }
  /**
   * <code>optional string storeName = 3;</code>
   */
  private void clearStoreName() {
    bitField0_ = (bitField0_ & ~0x00000001);
    storeName_ = getDefaultInstance().getStoreName();
  }
  /**
   * <code>optional string storeName = 3;</code>
   * @param value The bytes for storeName to set.
   */
  private void setStoreNameBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    storeName_ = value.toStringUtf8();
    bitField0_ |= 0x00000001;
  }

  public static com.example.grocerystoreorganizer.grpc.StoreInfo parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.example.grocerystoreorganizer.grpc.StoreInfo parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.example.grocerystoreorganizer.grpc.StoreInfo parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.example.grocerystoreorganizer.grpc.StoreInfo parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.example.grocerystoreorganizer.grpc.StoreInfo parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.example.grocerystoreorganizer.grpc.StoreInfo parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.example.grocerystoreorganizer.grpc.StoreInfo parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.example.grocerystoreorganizer.grpc.StoreInfo parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.example.grocerystoreorganizer.grpc.StoreInfo parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static com.example.grocerystoreorganizer.grpc.StoreInfo parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.example.grocerystoreorganizer.grpc.StoreInfo parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.example.grocerystoreorganizer.grpc.StoreInfo parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(com.example.grocerystoreorganizer.grpc.StoreInfo prototype) {
    return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code grocery.database.StoreInfo}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.example.grocerystoreorganizer.grpc.StoreInfo, Builder> implements
      // @@protoc_insertion_point(builder_implements:grocery.database.StoreInfo)
      com.example.grocerystoreorganizer.grpc.StoreInfoOrBuilder {
    // Construct using com.example.grocerystoreorganizer.grpc.StoreInfo.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>string storeAddress = 1;</code>
     * @return The storeAddress.
     */
    @java.lang.Override
    public java.lang.String getStoreAddress() {
      return instance.getStoreAddress();
    }
    /**
     * <code>string storeAddress = 1;</code>
     * @return The bytes for storeAddress.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getStoreAddressBytes() {
      return instance.getStoreAddressBytes();
    }
    /**
     * <code>string storeAddress = 1;</code>
     * @param value The storeAddress to set.
     * @return This builder for chaining.
     */
    public Builder setStoreAddress(
        java.lang.String value) {
      copyOnWrite();
      instance.setStoreAddress(value);
      return this;
    }
    /**
     * <code>string storeAddress = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearStoreAddress() {
      copyOnWrite();
      instance.clearStoreAddress();
      return this;
    }
    /**
     * <code>string storeAddress = 1;</code>
     * @param value The bytes for storeAddress to set.
     * @return This builder for chaining.
     */
    public Builder setStoreAddressBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setStoreAddressBytes(value);
      return this;
    }

    /**
     * <code>.grocery.database.Coordinate location = 2;</code>
     */
    @java.lang.Override
    public boolean hasLocation() {
      return instance.hasLocation();
    }
    /**
     * <code>.grocery.database.Coordinate location = 2;</code>
     */
    @java.lang.Override
    public com.example.grocerystoreorganizer.grpc.Coordinate getLocation() {
      return instance.getLocation();
    }
    /**
     * <code>.grocery.database.Coordinate location = 2;</code>
     */
    public Builder setLocation(com.example.grocerystoreorganizer.grpc.Coordinate value) {
      copyOnWrite();
      instance.setLocation(value);
      return this;
      }
    /**
     * <code>.grocery.database.Coordinate location = 2;</code>
     */
    public Builder setLocation(
        com.example.grocerystoreorganizer.grpc.Coordinate.Builder builderForValue) {
      copyOnWrite();
      instance.setLocation(builderForValue.build());
      return this;
    }
    /**
     * <code>.grocery.database.Coordinate location = 2;</code>
     */
    public Builder mergeLocation(com.example.grocerystoreorganizer.grpc.Coordinate value) {
      copyOnWrite();
      instance.mergeLocation(value);
      return this;
    }
    /**
     * <code>.grocery.database.Coordinate location = 2;</code>
     */
    public Builder clearLocation() {  copyOnWrite();
      instance.clearLocation();
      return this;
    }

    /**
     * <code>optional string storeName = 3;</code>
     * @return Whether the storeName field is set.
     */
    @java.lang.Override
    public boolean hasStoreName() {
      return instance.hasStoreName();
    }
    /**
     * <code>optional string storeName = 3;</code>
     * @return The storeName.
     */
    @java.lang.Override
    public java.lang.String getStoreName() {
      return instance.getStoreName();
    }
    /**
     * <code>optional string storeName = 3;</code>
     * @return The bytes for storeName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getStoreNameBytes() {
      return instance.getStoreNameBytes();
    }
    /**
     * <code>optional string storeName = 3;</code>
     * @param value The storeName to set.
     * @return This builder for chaining.
     */
    public Builder setStoreName(
        java.lang.String value) {
      copyOnWrite();
      instance.setStoreName(value);
      return this;
    }
    /**
     * <code>optional string storeName = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearStoreName() {
      copyOnWrite();
      instance.clearStoreName();
      return this;
    }
    /**
     * <code>optional string storeName = 3;</code>
     * @param value The bytes for storeName to set.
     * @return This builder for chaining.
     */
    public Builder setStoreNameBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setStoreNameBytes(value);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:grocery.database.StoreInfo)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.example.grocerystoreorganizer.grpc.StoreInfo();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "bitField0_",
            "storeAddress_",
            "location_",
            "storeName_",
          };
          java.lang.String info =
              "\u0000\u0003\u0000\u0001\u0001\u0003\u0003\u0000\u0000\u0000\u0001\u0208\u0002\t" +
              "\u0003\u1208\u0000";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<com.example.grocerystoreorganizer.grpc.StoreInfo> parser = PARSER;
        if (parser == null) {
          synchronized (com.example.grocerystoreorganizer.grpc.StoreInfo.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<com.example.grocerystoreorganizer.grpc.StoreInfo>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:grocery.database.StoreInfo)
  private static final com.example.grocerystoreorganizer.grpc.StoreInfo DEFAULT_INSTANCE;
  static {
    StoreInfo defaultInstance = new StoreInfo();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      StoreInfo.class, defaultInstance);
  }

  public static com.example.grocerystoreorganizer.grpc.StoreInfo getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<StoreInfo> PARSER;

  public static com.google.protobuf.Parser<StoreInfo> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

