// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: db_service.proto

package com.example.grocerystoreorganizer.grpc;

public interface UnmatchedOptimizationItemOrBuilder extends
    // @@protoc_insertion_point(interface_extends:grocery.database.UnmatchedOptimizationItem)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>int32 itemId = 1;</code>
   * @return The itemId.
   */
  int getItemId();

  /**
   * <code>string productName = 2;</code>
   * @return The productName.
   */
  java.lang.String getProductName();
  /**
   * <code>string productName = 2;</code>
   * @return The bytes for productName.
   */
  com.google.protobuf.ByteString
      getProductNameBytes();

  /**
   * <code>string reason = 3;</code>
   * @return The reason.
   */
  java.lang.String getReason();
  /**
   * <code>string reason = 3;</code>
   * @return The bytes for reason.
   */
  com.google.protobuf.ByteString
      getReasonBytes();
}
