// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: db_service.proto

package com.example.grocerystoreorganizer.grpc;

/**
 * Protobuf type {@code grocery.database.UnmatchedOptimizationItem}
 */
public  final class UnmatchedOptimizationItem extends
    com.google.protobuf.GeneratedMessageLite<
        UnmatchedOptimizationItem, UnmatchedOptimizationItem.Builder> implements
    // @@protoc_insertion_point(message_implements:grocery.database.UnmatchedOptimizationItem)
    UnmatchedOptimizationItemOrBuilder {
  private UnmatchedOptimizationItem() {
    productName_ = "";
    reason_ = "";
  }
  public static final int ITEMID_FIELD_NUMBER = 1;
  private int itemId_;
  /**
   * <code>int32 itemId = 1;</code>
   * @return The itemId.
   */
  @java.lang.Override
  public int getItemId() {
    return itemId_;
  }
  /**
   * <code>int32 itemId = 1;</code>
   * @param value The itemId to set.
   */
  private void setItemId(int value) {
    
    itemId_ = value;
  }
  /**
   * <code>int32 itemId = 1;</code>
   */
  private void clearItemId() {
    
    itemId_ = 0;
  }

  public static final int PRODUCTNAME_FIELD_NUMBER = 2;
  private java.lang.String productName_;
  /**
   * <code>string productName = 2;</code>
   * @return The productName.
   */
  @java.lang.Override
  public java.lang.String getProductName() {
    return productName_;
  }
  /**
   * <code>string productName = 2;</code>
   * @return The bytes for productName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getProductNameBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(productName_);
  }
  /**
   * <code>string productName = 2;</code>
   * @param value The productName to set.
   */
  private void setProductName(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    productName_ = value;
  }
  /**
   * <code>string productName = 2;</code>
   */
  private void clearProductName() {
    
    productName_ = getDefaultInstance().getProductName();
  }
  /**
   * <code>string productName = 2;</code>
   * @param value The bytes for productName to set.
   */
  private void setProductNameBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    productName_ = value.toStringUtf8();
    
  }

  public static final int REASON_FIELD_NUMBER = 3;
  private java.lang.String reason_;
  /**
   * <code>string reason = 3;</code>
   * @return The reason.
   */
  @java.lang.Override
  public java.lang.String getReason() {
    return reason_;
  }
  /**
   * <code>string reason = 3;</code>
   * @return The bytes for reason.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getReasonBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(reason_);
  }
  /**
   * <code>string reason = 3;</code>
   * @param value The reason to set.
   */
  private void setReason(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    reason_ = value;
  }
  /**
   * <code>string reason = 3;</code>
   */
  private void clearReason() {
    
    reason_ = getDefaultInstance().getReason();
  }
  /**
   * <code>string reason = 3;</code>
   * @param value The bytes for reason to set.
   */
  private void setReasonBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    reason_ = value.toStringUtf8();
    
  }

  public static com.example.grocerystoreorganizer.grpc.UnmatchedOptimizationItem parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.example.grocerystoreorganizer.grpc.UnmatchedOptimizationItem parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.example.grocerystoreorganizer.grpc.UnmatchedOptimizationItem parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.example.grocerystoreorganizer.grpc.UnmatchedOptimizationItem parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.example.grocerystoreorganizer.grpc.UnmatchedOptimizationItem parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.example.grocerystoreorganizer.grpc.UnmatchedOptimizationItem parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.example.grocerystoreorganizer.grpc.UnmatchedOptimizationItem parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.example.grocerystoreorganizer.grpc.UnmatchedOptimizationItem parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.example.grocerystoreorganizer.grpc.UnmatchedOptimizationItem parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static com.example.grocerystoreorganizer.grpc.UnmatchedOptimizationItem parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.example.grocerystoreorganizer.grpc.UnmatchedOptimizationItem parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.example.grocerystoreorganizer.grpc.UnmatchedOptimizationItem parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(com.example.grocerystoreorganizer.grpc.UnmatchedOptimizationItem prototype) {
    return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code grocery.database.UnmatchedOptimizationItem}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.example.grocerystoreorganizer.grpc.UnmatchedOptimizationItem, Builder> implements
      // @@protoc_insertion_point(builder_implements:grocery.database.UnmatchedOptimizationItem)
      com.example.grocerystoreorganizer.grpc.UnmatchedOptimizationItemOrBuilder {
    // Construct using com.example.grocerystoreorganizer.grpc.UnmatchedOptimizationItem.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>int32 itemId = 1;</code>
     * @return The itemId.
     */
    @java.lang.Override
    public int getItemId() {
      return instance.getItemId();
    }
    /**
     * <code>int32 itemId = 1;</code>
     * @param value The itemId to set.
     * @return This builder for chaining.
     */
    public Builder setItemId(int value) {
      copyOnWrite();
      instance.setItemId(value);
      return this;
    }
    /**
     * <code>int32 itemId = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearItemId() {
      copyOnWrite();
      instance.clearItemId();
      return this;
    }

    /**
     * <code>string productName = 2;</code>
     * @return The productName.
     */
    @java.lang.Override
    public java.lang.String getProductName() {
      return instance.getProductName();
    }
    /**
     * <code>string productName = 2;</code>
     * @return The bytes for productName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getProductNameBytes() {
      return instance.getProductNameBytes();
    }
    /**
     * <code>string productName = 2;</code>
     * @param value The productName to set.
     * @return This builder for chaining.
     */
    public Builder setProductName(
        java.lang.String value) {
      copyOnWrite();
      instance.setProductName(value);
      return this;
    }
    /**
     * <code>string productName = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearProductName() {
      copyOnWrite();
      instance.clearProductName();
      return this;
    }
    /**
     * <code>string productName = 2;</code>
     * @param value The bytes for productName to set.
     * @return This builder for chaining.
     */
    public Builder setProductNameBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setProductNameBytes(value);
      return this;
    }

    /**
     * <code>string reason = 3;</code>
     * @return The reason.
     */
    @java.lang.Override
    public java.lang.String getReason() {
      return instance.getReason();
    }
    /**
     * <code>string reason = 3;</code>
     * @return The bytes for reason.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getReasonBytes() {
      return instance.getReasonBytes();
    }
    /**
     * <code>string reason = 3;</code>
     * @param value The reason to set.
     * @return This builder for chaining.
     */
    public Builder setReason(
        java.lang.String value) {
      copyOnWrite();
      instance.setReason(value);
      return this;
    }
    /**
     * <code>string reason = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearReason() {
      copyOnWrite();
      instance.clearReason();
      return this;
    }
    /**
     * <code>string reason = 3;</code>
     * @param value The bytes for reason to set.
     * @return This builder for chaining.
     */
    public Builder setReasonBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setReasonBytes(value);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:grocery.database.UnmatchedOptimizationItem)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.example.grocerystoreorganizer.grpc.UnmatchedOptimizationItem();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "itemId_",
            "productName_",
            "reason_",
          };
          java.lang.String info =
              "\u0000\u0003\u0000\u0000\u0001\u0003\u0003\u0000\u0000\u0000\u0001\u0004\u0002\u0208" +
              "\u0003\u0208";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<com.example.grocerystoreorganizer.grpc.UnmatchedOptimizationItem> parser = PARSER;
        if (parser == null) {
          synchronized (com.example.grocerystoreorganizer.grpc.UnmatchedOptimizationItem.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<com.example.grocerystoreorganizer.grpc.UnmatchedOptimizationItem>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:grocery.database.UnmatchedOptimizationItem)
  private static final com.example.grocerystoreorganizer.grpc.UnmatchedOptimizationItem DEFAULT_INSTANCE;
  static {
    UnmatchedOptimizationItem defaultInstance = new UnmatchedOptimizationItem();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      UnmatchedOptimizationItem.class, defaultInstance);
  }

  public static com.example.grocerystoreorganizer.grpc.UnmatchedOptimizationItem getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<UnmatchedOptimizationItem> PARSER;

  public static com.google.protobuf.Parser<UnmatchedOptimizationItem> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

