// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: db_service.proto

package com.example.grocerystoreorganizer.grpc;

public interface UpcInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:grocery.database.UpcInfo)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>string upc = 1;</code>
   * @return The upc.
   */
  java.lang.String getUpc();
  /**
   * <code>string upc = 1;</code>
   * @return The bytes for upc.
   */
  com.google.protobuf.ByteString
      getUpcBytes();

  /**
   * <code>string productName = 2;</code>
   * @return The productName.
   */
  java.lang.String getProductName();
  /**
   * <code>string productName = 2;</code>
   * @return The bytes for productName.
   */
  com.google.protobuf.ByteString
      getProductNameBytes();

  /**
   * <code>optional string productCategory = 3;</code>
   * @return Whether the productCategory field is set.
   */
  boolean hasProductCategory();
  /**
   * <code>optional string productCategory = 3;</code>
   * @return The productCategory.
   */
  java.lang.String getProductCategory();
  /**
   * <code>optional string productCategory = 3;</code>
   * @return The bytes for productCategory.
   */
  com.google.protobuf.ByteString
      getProductCategoryBytes();

  /**
   * <code>string variantLabel = 4;</code>
   * @return The variantLabel.
   */
  java.lang.String getVariantLabel();
  /**
   * <code>string variantLabel = 4;</code>
   * @return The bytes for variantLabel.
   */
  com.google.protobuf.ByteString
      getVariantLabelBytes();

  /**
   * <code>int32 packCount = 5;</code>
   * @return The packCount.
   */
  int getPackCount();

  /**
   * <code>double netQuantity = 6;</code>
   * @return The netQuantity.
   */
  double getNetQuantity();

  /**
   * <code>.grocery.database.ProductUnit quantityUnit = 7;</code>
   * @return The enum numeric value on the wire for quantityUnit.
   */
  int getQuantityUnitValue();
  /**
   * <code>.grocery.database.ProductUnit quantityUnit = 7;</code>
   * @return The quantityUnit.
   */
  com.example.grocerystoreorganizer.grpc.ProductUnit getQuantityUnit();

  /**
   * <code>bool isVariableWeight = 8;</code>
   * @return The isVariableWeight.
   */
  boolean getIsVariableWeight();

  /**
   * <code>string updatedAt = 9;</code>
   * @return The updatedAt.
   */
  java.lang.String getUpdatedAt();
  /**
   * <code>string updatedAt = 9;</code>
   * @return The bytes for updatedAt.
   */
  com.google.protobuf.ByteString
      getUpdatedAtBytes();
}
