// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: db_service.proto

package com.example.grocerystoreorganizer.grpc;

/**
 * Protobuf type {@code grocery.database.UpcInfo}
 */
public  final class UpcInfo extends
    com.google.protobuf.GeneratedMessageLite<
        UpcInfo, UpcInfo.Builder> implements
    // @@protoc_insertion_point(message_implements:grocery.database.UpcInfo)
    UpcInfoOrBuilder {
  private UpcInfo() {
    upc_ = "";
    productName_ = "";
    productCategory_ = "";
    variantLabel_ = "";
    updatedAt_ = "";
  }
  private int bitField0_;
  public static final int UPC_FIELD_NUMBER = 1;
  private java.lang.String upc_;
  /**
   * <code>string upc = 1;</code>
   * @return The upc.
   */
  @java.lang.Override
  public java.lang.String getUpc() {
    return upc_;
  }
  /**
   * <code>string upc = 1;</code>
   * @return The bytes for upc.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getUpcBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(upc_);
  }
  /**
   * <code>string upc = 1;</code>
   * @param value The upc to set.
   */
  private void setUpc(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    upc_ = value;
  }
  /**
   * <code>string upc = 1;</code>
   */
  private void clearUpc() {
    
    upc_ = getDefaultInstance().getUpc();
  }
  /**
   * <code>string upc = 1;</code>
   * @param value The bytes for upc to set.
   */
  private void setUpcBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    upc_ = value.toStringUtf8();
    
  }

  public static final int PRODUCTNAME_FIELD_NUMBER = 2;
  private java.lang.String productName_;
  /**
   * <code>string productName = 2;</code>
   * @return The productName.
   */
  @java.lang.Override
  public java.lang.String getProductName() {
    return productName_;
  }
  /**
   * <code>string productName = 2;</code>
   * @return The bytes for productName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getProductNameBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(productName_);
  }
  /**
   * <code>string productName = 2;</code>
   * @param value The productName to set.
   */
  private void setProductName(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    productName_ = value;
  }
  /**
   * <code>string productName = 2;</code>
   */
  private void clearProductName() {
    
    productName_ = getDefaultInstance().getProductName();
  }
  /**
   * <code>string productName = 2;</code>
   * @param value The bytes for productName to set.
   */
  private void setProductNameBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    productName_ = value.toStringUtf8();
    
  }

  public static final int PRODUCTCATEGORY_FIELD_NUMBER = 3;
  private java.lang.String productCategory_;
  /**
   * <code>optional string productCategory = 3;</code>
   * @return Whether the productCategory field is set.
   */
  @java.lang.Override
  public boolean hasProductCategory() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>optional string productCategory = 3;</code>
   * @return The productCategory.
   */
  @java.lang.Override
  public java.lang.String getProductCategory() {
    return productCategory_;
  }
  /**
   * <code>optional string productCategory = 3;</code>
   * @return The bytes for productCategory.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getProductCategoryBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(productCategory_);
  }
  /**
   * <code>optional string productCategory = 3;</code>
   * @param value The productCategory to set.
   */
  private void setProductCategory(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  bitField0_ |= 0x00000001;
    productCategory_ = value;
  }
  /**
   * <code>optional string productCategory = 3;</code>
   */
  private void clearProductCategory() {
    bitField0_ = (bitField0_ & ~0x00000001);
    productCategory_ = getDefaultInstance().getProductCategory();
  }
  /**
   * <code>optional string productCategory = 3;</code>
   * @param value The bytes for productCategory to set.
   */
  private void setProductCategoryBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    productCategory_ = value.toStringUtf8();
    bitField0_ |= 0x00000001;
  }

  public static final int VARIANTLABEL_FIELD_NUMBER = 4;
  private java.lang.String variantLabel_;
  /**
   * <code>string variantLabel = 4;</code>
   * @return The variantLabel.
   */
  @java.lang.Override
  public java.lang.String getVariantLabel() {
    return variantLabel_;
  }
  /**
   * <code>string variantLabel = 4;</code>
   * @return The bytes for variantLabel.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getVariantLabelBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(variantLabel_);
  }
  /**
   * <code>string variantLabel = 4;</code>
   * @param value The variantLabel to set.
   */
  private void setVariantLabel(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    variantLabel_ = value;
  }
  /**
   * <code>string variantLabel = 4;</code>
   */
  private void clearVariantLabel() {
    
    variantLabel_ = getDefaultInstance().getVariantLabel();
  }
  /**
   * <code>string variantLabel = 4;</code>
   * @param value The bytes for variantLabel to set.
   */
  private void setVariantLabelBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    variantLabel_ = value.toStringUtf8();
    
  }

  public static final int PACKCOUNT_FIELD_NUMBER = 5;
  private int packCount_;
  /**
   * <code>int32 packCount = 5;</code>
   * @return The packCount.
   */
  @java.lang.Override
  public int getPackCount() {
    return packCount_;
  }
  /**
   * <code>int32 packCount = 5;</code>
   * @param value The packCount to set.
   */
  private void setPackCount(int value) {
    
    packCount_ = value;
  }
  /**
   * <code>int32 packCount = 5;</code>
   */
  private void clearPackCount() {
    
    packCount_ = 0;
  }

  public static final int NETQUANTITY_FIELD_NUMBER = 6;
  private double netQuantity_;
  /**
   * <code>double netQuantity = 6;</code>
   * @return The netQuantity.
   */
  @java.lang.Override
  public double getNetQuantity() {
    return netQuantity_;
  }
  /**
   * <code>double netQuantity = 6;</code>
   * @param value The netQuantity to set.
   */
  private void setNetQuantity(double value) {
    
    netQuantity_ = value;
  }
  /**
   * <code>double netQuantity = 6;</code>
   */
  private void clearNetQuantity() {
    
    netQuantity_ = 0D;
  }

  public static final int QUANTITYUNIT_FIELD_NUMBER = 7;
  private int quantityUnit_;
  /**
   * <code>.grocery.database.ProductUnit quantityUnit = 7;</code>
   * @return The enum numeric value on the wire for quantityUnit.
   */
  @java.lang.Override
  public int getQuantityUnitValue() {
    return quantityUnit_;
  }
  /**
   * <code>.grocery.database.ProductUnit quantityUnit = 7;</code>
   * @return The quantityUnit.
   */
  @java.lang.Override
  public com.example.grocerystoreorganizer.grpc.ProductUnit getQuantityUnit() {
    com.example.grocerystoreorganizer.grpc.ProductUnit result = com.example.grocerystoreorganizer.grpc.ProductUnit.forNumber(quantityUnit_);
    return result == null ? com.example.grocerystoreorganizer.grpc.ProductUnit.UNRECOGNIZED : result;
  }
  /**
   * <code>.grocery.database.ProductUnit quantityUnit = 7;</code>
   * @param value The enum numeric value on the wire for quantityUnit to set.
   */
  private void setQuantityUnitValue(int value) {
      quantityUnit_ = value;
  }
  /**
   * <code>.grocery.database.ProductUnit quantityUnit = 7;</code>
   * @param value The quantityUnit to set.
   */
  private void setQuantityUnit(com.example.grocerystoreorganizer.grpc.ProductUnit value) {
    quantityUnit_ = value.getNumber();
    
  }
  /**
   * <code>.grocery.database.ProductUnit quantityUnit = 7;</code>
   */
  private void clearQuantityUnit() {
    
    quantityUnit_ = 0;
  }

  public static final int ISVARIABLEWEIGHT_FIELD_NUMBER = 8;
  private boolean isVariableWeight_;
  /**
   * <code>bool isVariableWeight = 8;</code>
   * @return The isVariableWeight.
   */
  @java.lang.Override
  public boolean getIsVariableWeight() {
    return isVariableWeight_;
  }
  /**
   * <code>bool isVariableWeight = 8;</code>
   * @param value The isVariableWeight to set.
   */
  private void setIsVariableWeight(boolean value) {
    
    isVariableWeight_ = value;
  }
  /**
   * <code>bool isVariableWeight = 8;</code>
   */
  private void clearIsVariableWeight() {
    
    isVariableWeight_ = false;
  }

  public static final int UPDATEDAT_FIELD_NUMBER = 9;
  private java.lang.String updatedAt_;
  /**
   * <code>string updatedAt = 9;</code>
   * @return The updatedAt.
   */
  @java.lang.Override
  public java.lang.String getUpdatedAt() {
    return updatedAt_;
  }
  /**
   * <code>string updatedAt = 9;</code>
   * @return The bytes for updatedAt.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getUpdatedAtBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(updatedAt_);
  }
  /**
   * <code>string updatedAt = 9;</code>
   * @param value The updatedAt to set.
   */
  private void setUpdatedAt(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    updatedAt_ = value;
  }
  /**
   * <code>string updatedAt = 9;</code>
   */
  private void clearUpdatedAt() {
    
    updatedAt_ = getDefaultInstance().getUpdatedAt();
  }
  /**
   * <code>string updatedAt = 9;</code>
   * @param value The bytes for updatedAt to set.
   */
  private void setUpdatedAtBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    updatedAt_ = value.toStringUtf8();
    
  }

  public static com.example.grocerystoreorganizer.grpc.UpcInfo parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.example.grocerystoreorganizer.grpc.UpcInfo parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.example.grocerystoreorganizer.grpc.UpcInfo parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.example.grocerystoreorganizer.grpc.UpcInfo parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.example.grocerystoreorganizer.grpc.UpcInfo parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.example.grocerystoreorganizer.grpc.UpcInfo parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.example.grocerystoreorganizer.grpc.UpcInfo parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.example.grocerystoreorganizer.grpc.UpcInfo parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.example.grocerystoreorganizer.grpc.UpcInfo parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static com.example.grocerystoreorganizer.grpc.UpcInfo parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.example.grocerystoreorganizer.grpc.UpcInfo parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.example.grocerystoreorganizer.grpc.UpcInfo parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(com.example.grocerystoreorganizer.grpc.UpcInfo prototype) {
    return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code grocery.database.UpcInfo}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.example.grocerystoreorganizer.grpc.UpcInfo, Builder> implements
      // @@protoc_insertion_point(builder_implements:grocery.database.UpcInfo)
      com.example.grocerystoreorganizer.grpc.UpcInfoOrBuilder {
    // Construct using com.example.grocerystoreorganizer.grpc.UpcInfo.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>string upc = 1;</code>
     * @return The upc.
     */
    @java.lang.Override
    public java.lang.String getUpc() {
      return instance.getUpc();
    }
    /**
     * <code>string upc = 1;</code>
     * @return The bytes for upc.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getUpcBytes() {
      return instance.getUpcBytes();
    }
    /**
     * <code>string upc = 1;</code>
     * @param value The upc to set.
     * @return This builder for chaining.
     */
    public Builder setUpc(
        java.lang.String value) {
      copyOnWrite();
      instance.setUpc(value);
      return this;
    }
    /**
     * <code>string upc = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearUpc() {
      copyOnWrite();
      instance.clearUpc();
      return this;
    }
    /**
     * <code>string upc = 1;</code>
     * @param value The bytes for upc to set.
     * @return This builder for chaining.
     */
    public Builder setUpcBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setUpcBytes(value);
      return this;
    }

    /**
     * <code>string productName = 2;</code>
     * @return The productName.
     */
    @java.lang.Override
    public java.lang.String getProductName() {
      return instance.getProductName();
    }
    /**
     * <code>string productName = 2;</code>
     * @return The bytes for productName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getProductNameBytes() {
      return instance.getProductNameBytes();
    }
    /**
     * <code>string productName = 2;</code>
     * @param value The productName to set.
     * @return This builder for chaining.
     */
    public Builder setProductName(
        java.lang.String value) {
      copyOnWrite();
      instance.setProductName(value);
      return this;
    }
    /**
     * <code>string productName = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearProductName() {
      copyOnWrite();
      instance.clearProductName();
      return this;
    }
    /**
     * <code>string productName = 2;</code>
     * @param value The bytes for productName to set.
     * @return This builder for chaining.
     */
    public Builder setProductNameBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setProductNameBytes(value);
      return this;
    }

    /**
     * <code>optional string productCategory = 3;</code>
     * @return Whether the productCategory field is set.
     */
    @java.lang.Override
    public boolean hasProductCategory() {
      return instance.hasProductCategory();
    }
    /**
     * <code>optional string productCategory = 3;</code>
     * @return The productCategory.
     */
    @java.lang.Override
    public java.lang.String getProductCategory() {
      return instance.getProductCategory();
    }
    /**
     * <code>optional string productCategory = 3;</code>
     * @return The bytes for productCategory.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getProductCategoryBytes() {
      return instance.getProductCategoryBytes();
    }
    /**
     * <code>optional string productCategory = 3;</code>
     * @param value The productCategory to set.
     * @return This builder for chaining.
     */
    public Builder setProductCategory(
        java.lang.String value) {
      copyOnWrite();
      instance.setProductCategory(value);
      return this;
    }
    /**
     * <code>optional string productCategory = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearProductCategory() {
      copyOnWrite();
      instance.clearProductCategory();
      return this;
    }
    /**
     * <code>optional string productCategory = 3;</code>
     * @param value The bytes for productCategory to set.
     * @return This builder for chaining.
     */
    public Builder setProductCategoryBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setProductCategoryBytes(value);
      return this;
    }

    /**
     * <code>string variantLabel = 4;</code>
     * @return The variantLabel.
     */
    @java.lang.Override
    public java.lang.String getVariantLabel() {
      return instance.getVariantLabel();
    }
    /**
     * <code>string variantLabel = 4;</code>
     * @return The bytes for variantLabel.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getVariantLabelBytes() {
      return instance.getVariantLabelBytes();
    }
    /**
     * <code>string variantLabel = 4;</code>
     * @param value The variantLabel to set.
     * @return This builder for chaining.
     */
    public Builder setVariantLabel(
        java.lang.String value) {
      copyOnWrite();
      instance.setVariantLabel(value);
      return this;
    }
    /**
     * <code>string variantLabel = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearVariantLabel() {
      copyOnWrite();
      instance.clearVariantLabel();
      return this;
    }
    /**
     * <code>string variantLabel = 4;</code>
     * @param value The bytes for variantLabel to set.
     * @return This builder for chaining.
     */
    public Builder setVariantLabelBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setVariantLabelBytes(value);
      return this;
    }

    /**
     * <code>int32 packCount = 5;</code>
     * @return The packCount.
     */
    @java.lang.Override
    public int getPackCount() {
      return instance.getPackCount();
    }
    /**
     * <code>int32 packCount = 5;</code>
     * @param value The packCount to set.
     * @return This builder for chaining.
     */
    public Builder setPackCount(int value) {
      copyOnWrite();
      instance.setPackCount(value);
      return this;
    }
    /**
     * <code>int32 packCount = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearPackCount() {
      copyOnWrite();
      instance.clearPackCount();
      return this;
    }

    /**
     * <code>double netQuantity = 6;</code>
     * @return The netQuantity.
     */
    @java.lang.Override
    public double getNetQuantity() {
      return instance.getNetQuantity();
    }
    /**
     * <code>double netQuantity = 6;</code>
     * @param value The netQuantity to set.
     * @return This builder for chaining.
     */
    public Builder setNetQuantity(double value) {
      copyOnWrite();
      instance.setNetQuantity(value);
      return this;
    }
    /**
     * <code>double netQuantity = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearNetQuantity() {
      copyOnWrite();
      instance.clearNetQuantity();
      return this;
    }

    /**
     * <code>.grocery.database.ProductUnit quantityUnit = 7;</code>
     * @return The enum numeric value on the wire for quantityUnit.
     */
    @java.lang.Override
    public int getQuantityUnitValue() {
      return instance.getQuantityUnitValue();
    }
    /**
     * <code>.grocery.database.ProductUnit quantityUnit = 7;</code>
     * @param value The quantityUnit to set.
     * @return This builder for chaining.
     */
    public Builder setQuantityUnitValue(int value) {
      copyOnWrite();
      instance.setQuantityUnitValue(value);
      return this;
    }
    /**
     * <code>.grocery.database.ProductUnit quantityUnit = 7;</code>
     * @return The quantityUnit.
     */
    @java.lang.Override
    public com.example.grocerystoreorganizer.grpc.ProductUnit getQuantityUnit() {
      return instance.getQuantityUnit();
    }
    /**
     * <code>.grocery.database.ProductUnit quantityUnit = 7;</code>
     * @param value The enum numeric value on the wire for quantityUnit to set.
     * @return This builder for chaining.
     */
    public Builder setQuantityUnit(com.example.grocerystoreorganizer.grpc.ProductUnit value) {
      copyOnWrite();
      instance.setQuantityUnit(value);
      return this;
    }
    /**
     * <code>.grocery.database.ProductUnit quantityUnit = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearQuantityUnit() {
      copyOnWrite();
      instance.clearQuantityUnit();
      return this;
    }

    /**
     * <code>bool isVariableWeight = 8;</code>
     * @return The isVariableWeight.
     */
    @java.lang.Override
    public boolean getIsVariableWeight() {
      return instance.getIsVariableWeight();
    }
    /**
     * <code>bool isVariableWeight = 8;</code>
     * @param value The isVariableWeight to set.
     * @return This builder for chaining.
     */
    public Builder setIsVariableWeight(boolean value) {
      copyOnWrite();
      instance.setIsVariableWeight(value);
      return this;
    }
    /**
     * <code>bool isVariableWeight = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearIsVariableWeight() {
      copyOnWrite();
      instance.clearIsVariableWeight();
      return this;
    }

    /**
     * <code>string updatedAt = 9;</code>
     * @return The updatedAt.
     */
    @java.lang.Override
    public java.lang.String getUpdatedAt() {
      return instance.getUpdatedAt();
    }
    /**
     * <code>string updatedAt = 9;</code>
     * @return The bytes for updatedAt.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getUpdatedAtBytes() {
      return instance.getUpdatedAtBytes();
    }
    /**
     * <code>string updatedAt = 9;</code>
     * @param value The updatedAt to set.
     * @return This builder for chaining.
     */
    public Builder setUpdatedAt(
        java.lang.String value) {
      copyOnWrite();
      instance.setUpdatedAt(value);
      return this;
    }
    /**
     * <code>string updatedAt = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearUpdatedAt() {
      copyOnWrite();
      instance.clearUpdatedAt();
      return this;
    }
    /**
     * <code>string updatedAt = 9;</code>
     * @param value The bytes for updatedAt to set.
     * @return This builder for chaining.
     */
    public Builder setUpdatedAtBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setUpdatedAtBytes(value);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:grocery.database.UpcInfo)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.example.grocerystoreorganizer.grpc.UpcInfo();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "bitField0_",
            "upc_",
            "productName_",
            "productCategory_",
            "variantLabel_",
            "packCount_",
            "netQuantity_",
            "quantityUnit_",
            "isVariableWeight_",
            "updatedAt_",
          };
          java.lang.String info =
              "\u0000\t\u0000\u0001\u0001\t\t\u0000\u0000\u0000\u0001\u0208\u0002\u0208\u0003\u1208" +
              "\u0000\u0004\u0208\u0005\u0004\u0006\u0000\u0007\f\b\u0007\t\u0208";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<com.example.grocerystoreorganizer.grpc.UpcInfo> parser = PARSER;
        if (parser == null) {
          synchronized (com.example.grocerystoreorganizer.grpc.UpcInfo.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<com.example.grocerystoreorganizer.grpc.UpcInfo>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:grocery.database.UpcInfo)
  private static final com.example.grocerystoreorganizer.grpc.UpcInfo DEFAULT_INSTANCE;
  static {
    UpcInfo defaultInstance = new UpcInfo();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      UpcInfo.class, defaultInstance);
  }

  public static com.example.grocerystoreorganizer.grpc.UpcInfo getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<UpcInfo> PARSER;

  public static com.google.protobuf.Parser<UpcInfo> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

