// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: db_service.proto

package com.example.grocerystoreorganizer.grpc;

/**
 * Protobuf type {@code grocery.database.UpcRequest}
 */
public  final class UpcRequest extends
    com.google.protobuf.GeneratedMessageLite<
        UpcRequest, UpcRequest.Builder> implements
    // @@protoc_insertion_point(message_implements:grocery.database.UpcRequest)
    UpcRequestOrBuilder {
  private UpcRequest() {
    upc_ = "";
  }
  public static final int UPC_FIELD_NUMBER = 1;
  private java.lang.String upc_;
  /**
   * <code>string upc = 1;</code>
   * @return The upc.
   */
  @java.lang.Override
  public java.lang.String getUpc() {
    return upc_;
  }
  /**
   * <code>string upc = 1;</code>
   * @return The bytes for upc.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getUpcBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(upc_);
  }
  /**
   * <code>string upc = 1;</code>
   * @param value The upc to set.
   */
  private void setUpc(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    upc_ = value;
  }
  /**
   * <code>string upc = 1;</code>
   */
  private void clearUpc() {
    
    upc_ = getDefaultInstance().getUpc();
  }
  /**
   * <code>string upc = 1;</code>
   * @param value The bytes for upc to set.
   */
  private void setUpcBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    upc_ = value.toStringUtf8();
    
  }

  public static com.example.grocerystoreorganizer.grpc.UpcRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.example.grocerystoreorganizer.grpc.UpcRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.example.grocerystoreorganizer.grpc.UpcRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.example.grocerystoreorganizer.grpc.UpcRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.example.grocerystoreorganizer.grpc.UpcRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.example.grocerystoreorganizer.grpc.UpcRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.example.grocerystoreorganizer.grpc.UpcRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.example.grocerystoreorganizer.grpc.UpcRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.example.grocerystoreorganizer.grpc.UpcRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static com.example.grocerystoreorganizer.grpc.UpcRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.example.grocerystoreorganizer.grpc.UpcRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.example.grocerystoreorganizer.grpc.UpcRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(com.example.grocerystoreorganizer.grpc.UpcRequest prototype) {
    return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code grocery.database.UpcRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.example.grocerystoreorganizer.grpc.UpcRequest, Builder> implements
      // @@protoc_insertion_point(builder_implements:grocery.database.UpcRequest)
      com.example.grocerystoreorganizer.grpc.UpcRequestOrBuilder {
    // Construct using com.example.grocerystoreorganizer.grpc.UpcRequest.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>string upc = 1;</code>
     * @return The upc.
     */
    @java.lang.Override
    public java.lang.String getUpc() {
      return instance.getUpc();
    }
    /**
     * <code>string upc = 1;</code>
     * @return The bytes for upc.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getUpcBytes() {
      return instance.getUpcBytes();
    }
    /**
     * <code>string upc = 1;</code>
     * @param value The upc to set.
     * @return This builder for chaining.
     */
    public Builder setUpc(
        java.lang.String value) {
      copyOnWrite();
      instance.setUpc(value);
      return this;
    }
    /**
     * <code>string upc = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearUpc() {
      copyOnWrite();
      instance.clearUpc();
      return this;
    }
    /**
     * <code>string upc = 1;</code>
     * @param value The bytes for upc to set.
     * @return This builder for chaining.
     */
    public Builder setUpcBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setUpcBytes(value);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:grocery.database.UpcRequest)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.example.grocerystoreorganizer.grpc.UpcRequest();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "upc_",
          };
          java.lang.String info =
              "\u0000\u0001\u0000\u0000\u0001\u0001\u0001\u0000\u0000\u0000\u0001\u0208";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<com.example.grocerystoreorganizer.grpc.UpcRequest> parser = PARSER;
        if (parser == null) {
          synchronized (com.example.grocerystoreorganizer.grpc.UpcRequest.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<com.example.grocerystoreorganizer.grpc.UpcRequest>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:grocery.database.UpcRequest)
  private static final com.example.grocerystoreorganizer.grpc.UpcRequest DEFAULT_INSTANCE;
  static {
    UpcRequest defaultInstance = new UpcRequest();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      UpcRequest.class, defaultInstance);
  }

  public static com.example.grocerystoreorganizer.grpc.UpcRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<UpcRequest> PARSER;

  public static com.google.protobuf.Parser<UpcRequest> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

