// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: db_service.proto

package com.example.grocerystoreorganizer.grpc;

public interface UpcRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:grocery.database.UpcRequest)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>string upc = 1;</code>
   * @return The upc.
   */
  java.lang.String getUpc();
  /**
   * <code>string upc = 1;</code>
   * @return The bytes for upc.
   */
  com.google.protobuf.ByteString
      getUpcBytes();
}
