// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: db_service.proto

package com.example.grocerystoreorganizer.grpc;

public interface UpcResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:grocery.database.UpcResponse)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>bool found = 1;</code>
   * @return The found.
   */
  boolean getFound();

  /**
   * <code>optional .grocery.database.UpcInfo info = 2;</code>
   * @return Whether the info field is set.
   */
  boolean hasInfo();
  /**
   * <code>optional .grocery.database.UpcInfo info = 2;</code>
   * @return The info.
   */
  com.example.grocerystoreorganizer.grpc.UpcInfo getInfo();
}
