// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: db_service.proto

package com.example.grocerystoreorganizer.grpc;

/**
 * Protobuf type {@code grocery.database.UpcResponse}
 */
public  final class UpcResponse extends
    com.google.protobuf.GeneratedMessageLite<
        UpcResponse, UpcResponse.Builder> implements
    // @@protoc_insertion_point(message_implements:grocery.database.UpcResponse)
    UpcResponseOrBuilder {
  private UpcResponse() {
  }
  private int bitField0_;
  public static final int FOUND_FIELD_NUMBER = 1;
  private boolean found_;
  /**
   * <code>bool found = 1;</code>
   * @return The found.
   */
  @java.lang.Override
  public boolean getFound() {
    return found_;
  }
  /**
   * <code>bool found = 1;</code>
   * @param value The found to set.
   */
  private void setFound(boolean value) {
    
    found_ = value;
  }
  /**
   * <code>bool found = 1;</code>
   */
  private void clearFound() {
    
    found_ = false;
  }

  public static final int INFO_FIELD_NUMBER = 2;
  private com.example.grocerystoreorganizer.grpc.UpcInfo info_;
  /**
   * <code>optional .grocery.database.UpcInfo info = 2;</code>
   */
  @java.lang.Override
  public boolean hasInfo() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>optional .grocery.database.UpcInfo info = 2;</code>
   */
  @java.lang.Override
  public com.example.grocerystoreorganizer.grpc.UpcInfo getInfo() {
    return info_ == null ? com.example.grocerystoreorganizer.grpc.UpcInfo.getDefaultInstance() : info_;
  }
  /**
   * <code>optional .grocery.database.UpcInfo info = 2;</code>
   */
  private void setInfo(com.example.grocerystoreorganizer.grpc.UpcInfo value) {
    value.getClass();
  info_ = value;
    bitField0_ |= 0x00000001;
    }
  /**
   * <code>optional .grocery.database.UpcInfo info = 2;</code>
   */
  @java.lang.SuppressWarnings({"ReferenceEquality"})
  private void mergeInfo(com.example.grocerystoreorganizer.grpc.UpcInfo value) {
    value.getClass();
  if (info_ != null &&
        info_ != com.example.grocerystoreorganizer.grpc.UpcInfo.getDefaultInstance()) {
      info_ =
        com.example.grocerystoreorganizer.grpc.UpcInfo.newBuilder(info_).mergeFrom(value).buildPartial();
    } else {
      info_ = value;
    }
    bitField0_ |= 0x00000001;
  }
  /**
   * <code>optional .grocery.database.UpcInfo info = 2;</code>
   */
  private void clearInfo() {  info_ = null;
    bitField0_ = (bitField0_ & ~0x00000001);
  }

  public static com.example.grocerystoreorganizer.grpc.UpcResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.example.grocerystoreorganizer.grpc.UpcResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.example.grocerystoreorganizer.grpc.UpcResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.example.grocerystoreorganizer.grpc.UpcResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.example.grocerystoreorganizer.grpc.UpcResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.example.grocerystoreorganizer.grpc.UpcResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.example.grocerystoreorganizer.grpc.UpcResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.example.grocerystoreorganizer.grpc.UpcResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.example.grocerystoreorganizer.grpc.UpcResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static com.example.grocerystoreorganizer.grpc.UpcResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.example.grocerystoreorganizer.grpc.UpcResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.example.grocerystoreorganizer.grpc.UpcResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(com.example.grocerystoreorganizer.grpc.UpcResponse prototype) {
    return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code grocery.database.UpcResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.example.grocerystoreorganizer.grpc.UpcResponse, Builder> implements
      // @@protoc_insertion_point(builder_implements:grocery.database.UpcResponse)
      com.example.grocerystoreorganizer.grpc.UpcResponseOrBuilder {
    // Construct using com.example.grocerystoreorganizer.grpc.UpcResponse.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>bool found = 1;</code>
     * @return The found.
     */
    @java.lang.Override
    public boolean getFound() {
      return instance.getFound();
    }
    /**
     * <code>bool found = 1;</code>
     * @param value The found to set.
     * @return This builder for chaining.
     */
    public Builder setFound(boolean value) {
      copyOnWrite();
      instance.setFound(value);
      return this;
    }
    /**
     * <code>bool found = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearFound() {
      copyOnWrite();
      instance.clearFound();
      return this;
    }

    /**
     * <code>optional .grocery.database.UpcInfo info = 2;</code>
     */
    @java.lang.Override
    public boolean hasInfo() {
      return instance.hasInfo();
    }
    /**
     * <code>optional .grocery.database.UpcInfo info = 2;</code>
     */
    @java.lang.Override
    public com.example.grocerystoreorganizer.grpc.UpcInfo getInfo() {
      return instance.getInfo();
    }
    /**
     * <code>optional .grocery.database.UpcInfo info = 2;</code>
     */
    public Builder setInfo(com.example.grocerystoreorganizer.grpc.UpcInfo value) {
      copyOnWrite();
      instance.setInfo(value);
      return this;
      }
    /**
     * <code>optional .grocery.database.UpcInfo info = 2;</code>
     */
    public Builder setInfo(
        com.example.grocerystoreorganizer.grpc.UpcInfo.Builder builderForValue) {
      copyOnWrite();
      instance.setInfo(builderForValue.build());
      return this;
    }
    /**
     * <code>optional .grocery.database.UpcInfo info = 2;</code>
     */
    public Builder mergeInfo(com.example.grocerystoreorganizer.grpc.UpcInfo value) {
      copyOnWrite();
      instance.mergeInfo(value);
      return this;
    }
    /**
     * <code>optional .grocery.database.UpcInfo info = 2;</code>
     */
    public Builder clearInfo() {  copyOnWrite();
      instance.clearInfo();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:grocery.database.UpcResponse)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.example.grocerystoreorganizer.grpc.UpcResponse();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "bitField0_",
            "found_",
            "info_",
          };
          java.lang.String info =
              "\u0000\u0002\u0000\u0001\u0001\u0002\u0002\u0000\u0000\u0000\u0001\u0007\u0002\u1009" +
              "\u0000";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<com.example.grocerystoreorganizer.grpc.UpcResponse> parser = PARSER;
        if (parser == null) {
          synchronized (com.example.grocerystoreorganizer.grpc.UpcResponse.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<com.example.grocerystoreorganizer.grpc.UpcResponse>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:grocery.database.UpcResponse)
  private static final com.example.grocerystoreorganizer.grpc.UpcResponse DEFAULT_INSTANCE;
  static {
    UpcResponse defaultInstance = new UpcResponse();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      UpcResponse.class, defaultInstance);
  }

  public static com.example.grocerystoreorganizer.grpc.UpcResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<UpcResponse> PARSER;

  public static com.google.protobuf.Parser<UpcResponse> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

